'use client';
import React, { useState } from 'react';
import { FileText } from 'lucide-react';
import { get } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { ResourcePage } from '@/components/shared/resource-page';
import { Modal } from '@/components/ui/dialog';
import { KV, Section } from '@/components/shared/page';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { DropdownMenuItem } from '@/components/ui/dropdown';
import { fmtDate, fmtMoney, fmtNum } from '@/lib/utils';
import { Attachments } from '@/components/shared/attachments';

export default function SuppliersPage() {
  const { currency } = useAuth(); const [stmt, setStmt] = useState<any>(null);
  return <>
    <ResourcePage title="Suppliers" subtitle="Vendor master with payment terms, credit limits, statements and price history." path="/suppliers" permissions={{ view: 'suppliers.view', create: 'suppliers.manage', edit: 'suppliers.manage' }} defaultSort="name" dialogSize="lg" searchPlaceholder="Search name, code, phone, email…"
      filters={[{ key: 'active', label: 'Active', type: 'select', options: [{ value: 'true', label: 'Active' }, { value: 'false', label: 'Inactive' }] }]}
      columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Supplier', render: (r) => <div><div className="font-medium">{r.name}</div><div className="text-xs text-muted-foreground">{r.contact_name} {r.phone && `· ${r.phone}`}</div></div> }, { key: 'categories', label: 'Categories', render: (r) => (r.categories ?? []).map((c: string) => <Badge key={c} tone="muted" className="mr-1">{c}</Badge>) }, { key: 'payment_terms_days', label: 'Terms', render: (r) => `${r.payment_terms_days} days` }, { key: 'credit_limit', label: 'Credit limit', type: 'money' }, { key: 'outstanding', label: 'Outstanding', type: 'money' }, { key: 'open_pos', label: 'Open POs', type: 'number', decimals: 0 }, { key: 'last_order_date', label: 'Last order', type: 'date' }, { key: 'rating', label: 'Rating', render: (r) => (r.rating ? '★'.repeat(r.rating) : '—') }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'code', label: 'Code (auto if blank)' }, { name: 'name', label: 'Name', required: true }, { name: 'contact_name', label: 'Contact person' }, { name: 'phone', label: 'Phone' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'tax_number', label: 'Tax / PIN number' }, { name: 'address', label: 'Address', type: 'textarea', col: 2 }, { name: 'payment_terms_days', label: 'Payment terms (days)', type: 'number', default: 30 }, { name: 'currency', label: 'Currency', default: 'KES' }, { name: 'credit_limit', label: 'Credit limit', type: 'money' }, { name: 'opening_balance', label: 'Opening balance owed', type: 'money' }, { name: 'bank_name', label: 'Bank' }, { name: 'bank_branch', label: 'Branch' }, { name: 'bank_account', label: 'Account number' }, { name: 'categories', label: 'Supply categories', type: 'tags', placeholder: 'FOOD, BEVERAGE, LINEN' }, { name: 'rating', label: 'Rating (0–5)', type: 'number' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }, { name: 'notes', label: 'Notes', type: 'textarea', col: 2 }]}
      extraActions={(row) => <DropdownMenuItem onClick={async () => setStmt({ ...(await get(`/suppliers/${row.id}/statement`)), products: await get(`/suppliers/${row.id}/products`) })}><FileText />Statement & prices</DropdownMenuItem>} />
    <Modal open={!!stmt} onOpenChange={(o) => !o && setStmt(null)} title={stmt ? `${stmt.supplier.name} · statement` : ''} size="xl">{stmt && <div className="space-y-4">
      <KV cols={4} items={[['Outstanding', fmtMoney(stmt.aging?.total, currency)], ['Current', fmtMoney(stmt.aging?.current, currency)], ['1–30 days', fmtMoney(stmt.aging?.d30, currency)], ['31–60 days', fmtMoney(stmt.aging?.d60, currency)], ['61–90 days', fmtMoney(stmt.aging?.d90, currency)], ['90+ days', fmtMoney(stmt.aging?.d90plus, currency)], ['Terms', `${stmt.supplier.payment_terms_days} days`], ['Credit limit', fmtMoney(stmt.supplier.credit_limit, currency)]]} />
      <Section title="Invoices"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left py-1">Invoice</th><th className="text-left">Supplier ref</th><th className="text-left">Date</th><th className="text-left">Due</th><th className="text-right">Total</th><th className="text-right">Paid</th><th className="text-right">Balance</th><th /></tr></thead><tbody className="divide-y">{(stmt.invoices ?? []).map((i: any) => <tr key={i.id}><td className="py-1">{i.number}</td><td>{i.supplier_invoice_no}</td><td>{fmtDate(i.invoice_date)}</td><td className={Number(i.days_overdue) > 0 && Number(i.balance) > 0 ? 'text-destructive' : ''}>{fmtDate(i.due_date)}{Number(i.days_overdue) > 0 && Number(i.balance) > 0 && ` (+${i.days_overdue}d)`}</td><td className="text-right tabular">{fmtMoney(i.total, currency)}</td><td className="text-right tabular">{fmtMoney(i.paid_total, currency)}</td><td className="text-right tabular font-medium">{fmtMoney(i.balance, currency)}</td><td><StatusBadge status={i.status} /></td></tr>)}</tbody></table></Section>
      <div className="grid gap-4 lg:grid-cols-2"><Section title="Payments"><ul className="divide-y text-sm">{(stmt.payments ?? []).map((p: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{fmtDate(p.business_date)} · {p.number} · {p.method}{p.reference && ` · ${p.reference}`}</span><span className="tabular">{fmtMoney(p.amount, currency)}</span></li>)}{(stmt.payments ?? []).length === 0 && <li className="py-2 text-muted-foreground">No payments yet.</li>}</ul></Section>
        <Section title="Price history"><ul className="divide-y text-sm">{(Array.isArray(stmt.products) ? stmt.products : stmt.products?.data ?? []).map((p: any) => <li key={p.id} className="flex justify-between py-1"><span>{p.name} <span className="text-xs text-muted-foreground">{p.sku}</span></span><span className="tabular text-xs">avg {fmtMoney(p.avg_price, currency)}/{p.unit} · {fmtNum(p.total_qty, 1)} bought · last {fmtDate(p.last_ordered)}</span></li>)}</ul></Section></div>
      <Attachments entity="supplier" entityId={stmt.supplier.id} title="Contracts & documents" />
    </div>}</Modal>
  </>;
}
