'use client';
import React, { useState } from 'react';
import { Plus, Lock, Unlock, CalendarPlus } from 'lucide-react';
import { post } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section } from '@/components/shared/page';
import { ResourcePage } from '@/components/shared/resource-page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { FormDialog, ConfirmDialog } from '@/components/shared/form';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtDate, fmtDateTime, fmtNum, titleCase, today } from '@/lib/utils';

const acctLabel = (a: any) => `${a.code} · ${a.name}`;
const METHOD_TYPES = ['CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'VOUCHER', 'CORPORATE_CREDIT', 'GUEST_DEPOSIT', 'ROOM_CHARGE', 'OTHER'];
function Periods() {
  const { can } = useAuth(); const { data, refetch } = useApi<any[]>('/accounting-periods'); const [gen, setGen] = useState(false); const [add, setAdd] = useState(false); const [close, setClose] = useState<any>(null); const [reopen, setReopen] = useState<any>(null);
  const done = { invalidate: ['/accounting-periods'], onSuccess: () => { setGen(false); setAdd(false); setClose(null); setReopen(null); refetch(); } };
  const genM = useAction((v: any) => post('/accounting-periods/generate', v), { success: 'Periods generated', ...done }); const addM = useAction((v: any) => post('/accounting-periods', v), { success: 'Period created', ...done }); const closeM = useAction((v: any) => post(`/accounting-periods/${close.id}/close`, v), { success: 'Period closed', ...done }); const reopenM = useAction((v: any) => post(`/accounting-periods/${reopen.id}/reopen`, v), { success: 'Period reopened', ...done });
  const manage = can('accounting.periods');
  return <Section title="Accounting periods" description="Journals cannot be posted into closed periods; locked periods cannot be reopened." actions={manage && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setGen(true)}><CalendarPlus />Generate year</Button><Button size="sm" onClick={() => setAdd(true)}><Plus />Period</Button></div>}>
    <table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Period</th><th className="p-2 text-left">From</th><th className="p-2 text-left">To</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Closed</th><th /></tr></thead><tbody className="divide-y">{(data ?? []).map((p: any) => <tr key={p.id}><td className="p-2 font-medium">{p.name}</td><td className="p-2">{fmtDate(p.start_date)}</td><td className="p-2">{fmtDate(p.end_date)}</td><td className="p-2"><StatusBadge status={p.status} /></td><td className="p-2 text-xs">{p.closed_at ? `${fmtDateTime(p.closed_at)} · ${p.closed_by_name ?? ''}` : '—'}</td><td className="p-2 text-right">{manage && p.status === 'OPEN' && <Button size="sm" variant="ghost" onClick={() => setClose(p)}><Lock />Close</Button>}{manage && p.status === 'CLOSED' && <Button size="sm" variant="ghost" onClick={() => setReopen(p)}><Unlock />Reopen</Button>}</td></tr>)}{(data ?? []).length === 0 && <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">No periods defined — journals post freely. Generate a year to enable period control.</td></tr>}</tbody></table>
    <FormDialog open={gen} onOpenChange={setGen} title="Generate monthly periods" fields={[{ name: 'year', label: 'Year', type: 'number', required: true, default: Number(today().slice(0, 4)) }]} onSubmit={(v) => genM.mutateAsync({ year: Number(v.year) })} />
    <FormDialog open={add} onOpenChange={setAdd} title="New period" fields={[{ name: 'name', label: 'Name', required: true, col: 2 }, { name: 'start_date', label: 'Start', type: 'date', required: true }, { name: 'end_date', label: 'End', type: 'date', required: true }]} onSubmit={(v) => addM.mutateAsync(v)} />
    <ConfirmDialog open={!!close} onOpenChange={(o) => !o && setClose(null)} title={`Close ${close?.name}`} description="No further journals can be posted with an entry date inside this period. Tick 'lock' to make it permanent." confirmLabel="Close period" fields={[{ name: 'lock', label: 'Lock permanently (cannot be reopened)', type: 'switch' }]} onConfirm={(v) => closeM.mutateAsync({ lock: !!v.lock })} />
    <ConfirmDialog open={!!reopen} onOpenChange={(o) => !o && setReopen(null)} title={`Reopen ${reopen?.name}`} destructive confirmLabel="Reopen" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => reopenM.mutateAsync(v)} />
  </Section>;
}
function Currencies() {
  const { can, currency } = useAuth(); const { data: cur, refetch } = useApi<any[]>('/currencies'); const { data: rates, refetch: refetchRates } = useApi<any>('/currencies/rates', { pageSize: 50 }); const [add, setAdd] = useState(false); const [rate, setRate] = useState(false);
  const addM = useAction((v: any) => post('/currencies', { ...v, decimals: Number(v.decimals ?? 2) }), { success: 'Currency added', onSuccess: () => { setAdd(false); refetch(); } }); const rateM = useAction((v: any) => post('/currencies/rates', { ...v, rate: Number(v.rate) }), { success: 'Rate recorded', onSuccess: () => { setRate(false); refetch(); refetchRates(); } });
  const rateRows: any[] = rates?.data ?? (Array.isArray(rates) ? rates : []);
  return <div className="grid gap-4 md:grid-cols-2"><Section title="Currencies" actions={can('settings.edit') && <Button size="sm" onClick={() => setAdd(true)}><Plus />Currency</Button>}><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Code</th><th className="p-2 text-left">Name</th><th className="p-2 text-left">Symbol</th><th className="p-2 text-right">Rate → {currency}</th><th className="p-2">Active</th></tr></thead><tbody className="divide-y">{(cur ?? []).map((c: any) => <tr key={c.code}><td className="p-2 font-mono">{c.code}</td><td className="p-2">{c.name}</td><td className="p-2">{c.symbol}</td><td className="p-2 text-right tabular">{c.code === currency ? '1 (base)' : c.latest_rate ? fmtNum(c.latest_rate, 4) : <span className="text-muted-foreground">—</span>}</td><td className="p-2 text-center">{c.is_active ? '✓' : ''}</td></tr>)}</tbody></table></Section>
    <Section title="Exchange rates" description="Effective-dated; conversions use the latest rate on or before the transaction date." actions={can('settings.edit') && <Button size="sm" onClick={() => setRate(true)}><Plus />Rate</Button>}><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Effective</th><th className="p-2 text-left">Pair</th><th className="p-2 text-right">Rate</th><th className="p-2 text-left">By</th></tr></thead><tbody className="divide-y">{rateRows.map((r: any) => <tr key={r.id}><td className="p-2">{fmtDate(r.effective_date)}</td><td className="p-2 font-mono">{r.from_currency} → {r.to_currency}</td><td className="p-2 text-right tabular">{fmtNum(r.rate, 4)}</td><td className="p-2 text-xs">{r.created_by_name}</td></tr>)}</tbody></table></Section>
    <FormDialog open={add} onOpenChange={setAdd} title="Add currency" fields={[{ name: 'code', label: 'ISO code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'symbol', label: 'Symbol', required: true }, { name: 'decimals', label: 'Decimals', type: 'number', default: 2 }]} onSubmit={(v) => addM.mutateAsync({ ...v, code: String(v.code).toUpperCase() })} />
    <FormDialog open={rate} onOpenChange={setRate} title="Record exchange rate" fields={[{ name: 'from_currency', label: 'From', type: 'select', options: (cur ?? []).map((c: any) => c.code), required: true }, { name: 'to_currency', label: 'To', type: 'select', options: (cur ?? []).map((c: any) => c.code), default: currency, required: true }, { name: 'rate', label: 'Rate (1 from = ? to)', type: 'number', required: true }, { name: 'effective_date', label: 'Effective date', type: 'date', default: today() }]} onSubmit={(v) => rateM.mutateAsync(v)} />
  </div>;
}
export default function FinanceSetupPage() {
  return <div className="space-y-4">
    <PageHeader title="Finance setup" subtitle="Taxes, payment methods, currencies and accounting periods. All of it is data — nothing about tax or tender types is hard-coded." />
    <Tabs defaultValue="taxes"><TabsList><TabsTrigger value="taxes">Taxes</TabsTrigger><TabsTrigger value="methods">Payment methods</TabsTrigger><TabsTrigger value="currencies">Currencies & FX</TabsTrigger><TabsTrigger value="periods">Periods</TabsTrigger></TabsList>
      <TabsContent value="taxes"><ResourcePage embedded path="/taxes" title="Tax" entity="tax" permissions={{ view: 'settings.view', create: 'settings.edit', edit: 'settings.edit' }} defaultSort="code" fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'rate', label: 'Rate %', type: 'number', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['VAT', 'LEVY', 'SERVICE_CHARGE', 'WITHHOLDING', 'OTHER'], default: 'VAT' }, { name: 'account_id', label: 'Tax GL account', type: 'lookup', source: '/accounts', sourceQuery: { header: 'false', pageSize: 500 }, sourceLabel: acctLabel, required: true }, { name: 'applies_to', label: 'Applies to (categories)', type: 'tags' }, { name: 'is_inclusive', label: 'Prices include this tax', type: 'switch', default: true }, { name: 'is_recoverable', label: 'Recoverable (input tax)', type: 'switch', default: true }, { name: 'fiscal_code', label: 'Fiscal / e-invoicing code' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'rate', label: 'Rate', render: (r) => `${fmtNum(r.rate, 2)}%` }, { key: 'type', label: 'Type', render: (r) => titleCase(r.type) }, { key: 'is_inclusive', label: 'Inclusive', type: 'bool' }, { key: 'account_code', label: 'GL', render: (r) => `${r.account_code ?? ''} ${r.account_name ?? ''}` }, { key: 'applies_to', label: 'Applies to', render: (r) => (r.applies_to ?? []).map((a: string) => <Badge key={a} tone="muted" className="mr-1">{a}</Badge>) }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
      <TabsContent value="methods"><ResourcePage embedded path="/payment-methods" title="Payment method" entity="payment_method" permissions={{ view: 'settings.view', create: 'settings.edit', edit: 'settings.edit' }} defaultSort="code" fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select', options: METHOD_TYPES, required: true }, { name: 'account_id', label: 'Settlement GL account (cash/bank/clearing)', type: 'lookup', source: '/accounts', sourceQuery: { header: 'false', pageSize: 500 }, sourceLabel: acctLabel }, { name: 'requires_reference', label: 'Requires reference number', type: 'switch' }, { name: 'is_cash_drawer', label: 'Counts in cash drawer', type: 'switch' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'type', label: 'Type', render: (r) => titleCase(r.type) }, { key: 'account_code', label: 'GL', render: (r) => `${r.account_code ?? ''} ${r.account_name ?? ''}` }, { key: 'requires_reference', label: 'Ref req.', type: 'bool' }, { key: 'is_cash_drawer', label: 'Cash drawer', type: 'bool' }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
      <TabsContent value="currencies"><Currencies /></TabsContent>
      <TabsContent value="periods"><Periods /></TabsContent>
    </Tabs>
  </div>;
}
