'use client';
import React, { Suspense, useEffect, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { Plus, Banknote, FileMinus } from 'lucide-react';
import { post, put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { DataTable } from '@/components/shared/data-table';
import { ResourcePage } from '@/components/shared/resource-page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Input, Label } from '@/components/ui/input';
import { FormDialog, LookupSelect } from '@/components/shared/form';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtDate, fmtMoney, fmtNum, titleCase, today, addDays } from '@/lib/utils';

const CUSTOMER_TYPES = ['CORPORATE', 'TRAVEL_AGENT', 'OTA', 'GOVERNMENT', 'GROUP', 'INDIVIDUAL', 'OTHER'];
const customerFields = [{ name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select' as const, options: CUSTOMER_TYPES, default: 'CORPORATE' }, { name: 'code', label: 'Code (auto if blank)' }, { name: 'tax_number', label: 'Tax / PIN number' }, { name: 'contact_name', label: 'Contact person' }, { name: 'phone', label: 'Phone' }, { name: 'email', label: 'Email' }, { name: 'address', label: 'Address' }, { name: 'credit_limit', label: 'Credit limit', type: 'money' as const, default: 0 }, { name: 'payment_terms_days', label: 'Payment terms (days)', type: 'number' as const, default: 30 }, { name: 'commission_percent', label: 'Commission %', type: 'number' as const, default: 0 }, { name: 'currency', label: 'Currency', default: 'KES' }, { name: 'notes', label: 'Notes', type: 'textarea' as const, col: 2 as const }, { name: 'is_active', label: 'Active', type: 'switch' as const, default: true }];

/** Receipt against a city-ledger account with optional invoice allocations (oldest first by default). */
function ReceiptDialog({ open, onOpenChange, customer, invoiceId }: { open: boolean; onOpenChange: (o: boolean) => void; customer?: any; invoiceId?: string | null }) {
  const { currency } = useAuth(); const [customerId, setCustomerId] = useState(customer?.id ?? ''); const [f, setF] = useState<any>({ amount: '', payment_method_id: '', reference: '', notes: '' }); const [alloc, setAlloc] = useState<Record<string, string>>({});
  useEffect(() => { setCustomerId(customer?.id ?? ''); }, [customer, open]);
  const { data: openInv } = useApi<any>(open && customerId ? '/receivables/open-invoices' : null, { customer_id: customerId, pageSize: 200 });
  const invoices: any[] = openInv?.data ?? (Array.isArray(openInv) ? openInv : []);
  useEffect(() => { if (invoiceId && invoices.length) { const inv = invoices.find((i) => i.id === invoiceId); if (inv && !alloc[inv.id]) { setAlloc({ [inv.id]: String(inv.balance) }); setF((x: any) => ({ ...x, amount: x.amount || String(inv.balance) })); } } }, [invoiceId, invoices]); // eslint-disable-line react-hooks/exhaustive-deps
  const allocated = Object.values(alloc).reduce((s, v) => s + Number(v || 0), 0);
  const autoAllocate = () => { let left = Number(f.amount || 0); const a: Record<string, string> = {}; for (const inv of invoices) { if (left <= 0) break; const x = Math.min(left, Number(inv.balance)); if (x > 0) { a[inv.id] = String(x); left -= x; } } setAlloc(a); };
  const save = useAction(() => post('/receivables/receipts', { customer_id: customerId, amount: Number(f.amount), payment_method_id: f.payment_method_id || undefined, reference: f.reference || null, notes: f.notes || null, allocations: Object.entries(alloc).filter(([, v]) => Number(v) > 0).map(([invoice_id, amount]) => ({ invoice_id, amount: Number(amount) })) }), { success: 'Receipt posted', invalidate: ['/receivables', '/customers', '/payments', '/invoices'], onSuccess: () => { onOpenChange(false); setF({ amount: '', payment_method_id: '', reference: '', notes: '' }); setAlloc({}); } });
  return <Modal open={open} onOpenChange={onOpenChange} title="Record AR receipt" size="lg"><div className="space-y-3">
    {!customer && <LookupSelect label="Customer" source="/customers" value={customerId} onChange={setCustomerId} sourceLabel={(c: any) => `${c.name} · bal ${fmtMoney(c.balance, currency)}`} allowEmpty={false} />}
    <div className="grid grid-cols-3 gap-3"><div className="flex flex-col gap-1"><Label>Amount received</Label><Input type="number" step="0.01" value={f.amount} onChange={(e) => setF({ ...f, amount: e.target.value })} /></div><LookupSelect label="Payment method" source="/payment-methods" sourceQuery={{ active: 'true' }} value={f.payment_method_id} onChange={(v) => setF({ ...f, payment_method_id: v })} allowEmpty={false} /><div className="flex flex-col gap-1"><Label>Reference (cheque / transfer no.)</Label><Input value={f.reference} onChange={(e) => setF({ ...f, reference: e.target.value })} /></div></div>
    <div className="flex items-center justify-between"><Label>Allocate to invoices</Label><Button size="sm" variant="ghost" onClick={autoAllocate} disabled={!Number(f.amount)}>Auto-allocate oldest first</Button></div>
    <div className="max-h-60 overflow-auto rounded border"><table className="w-full text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Invoice</th><th className="p-2 text-left">Due</th><th className="p-2 text-right">Balance</th><th className="p-2 text-right w-36">Allocate</th></tr></thead><tbody className="divide-y">{invoices.map((inv) => <tr key={inv.id}><td className="p-2">{inv.number}<div className="text-xs text-muted-foreground">{inv.description ?? inv.type}</div></td><td className="p-2">{fmtDate(inv.due_date)}{Number(inv.days_overdue) > 0 && <Badge tone="destructive" className="ml-1">{inv.days_overdue}d</Badge>}</td><td className="p-2 text-right tabular">{fmtMoney(inv.balance, currency)}</td><td className="p-2"><Input type="number" step="0.01" min={0} max={Number(inv.balance)} className="text-right" value={alloc[inv.id] ?? ''} onChange={(e) => setAlloc({ ...alloc, [inv.id]: e.target.value })} /></td></tr>)}{invoices.length === 0 && <tr><td colSpan={4} className="p-4 text-center text-muted-foreground">{customerId ? 'No open invoices — receipt will sit as unapplied credit.' : 'Select a customer'}</td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between text-sm"><span>Allocated {fmtMoney(allocated, currency)} of {fmtMoney(f.amount, currency)}{allocated > Number(f.amount || 0) && <span className="text-destructive"> — over-allocated</span>}</span><Button loading={save.isPending} disabled={!customerId || !Number(f.amount) || !f.payment_method_id || allocated > Number(f.amount) + 0.005} onClick={() => save.mutate(undefined as any)}><Banknote />Post receipt</Button></div>
  </div></Modal>;
}
function CustomerStatement({ customer, onClose, onReceipt }: { customer: any | null; onClose: () => void; onReceipt: () => void }) {
  const { can, currency } = useAuth(); const [from, setFrom] = useState(addDays(today(), -90)); const [to, setTo] = useState(today()); const [cn, setCn] = useState<any>(null);
  const { data, refetch } = useApi<any>(customer ? `/customers/${customer.id}/statement` : null, { from, to });
  const creditNote = useAction((v: any) => post('/receivables/credit-notes', { invoice_id: cn.id, amount: Number(v.amount), reason: v.reason }), { success: 'Credit note posted', invalidate: ['/receivables', '/customers'], onSuccess: () => { setCn(null); refetch(); } });
  if (!customer) return null; const ag = data?.aging;
  return <Modal open={!!customer} onOpenChange={(o) => !o && onClose()} title={`${customer.name} — statement`} size="xl"><div className="space-y-3">
    <div className="flex flex-wrap items-end gap-2"><div className="flex flex-col gap-1"><Label>From</Label><Input type="date" className="w-40" value={from} onChange={(e) => setFrom(e.target.value)} /></div><div className="flex flex-col gap-1"><Label>To</Label><Input type="date" className="w-40" value={to} onChange={(e) => setTo(e.target.value)} /></div><div className="ml-auto flex gap-2">{can('receivables.manage', 'payments.create') && <Button size="sm" onClick={onReceipt}><Banknote />Receive payment</Button>}</div></div>
    <KV cols={4} items={[['Opening balance', fmtMoney(data?.opening, currency)], ['Closing balance', <b key="c">{fmtMoney(data?.closing, currency)}</b>], ['Credit limit', `${fmtMoney(customer.credit_limit, currency)} · ${customer.payment_terms_days}d terms`], ['Aging', ag ? `cur ${fmtNum(ag.current, 0)} · 30 ${fmtNum(ag.d30, 0)} · 60 ${fmtNum(ag.d60, 0)} · 90+ ${fmtNum(Number(ag.d90) + Number(ag.d90plus), 0)}` : '—']]} />
    <Tabs defaultValue="ledger"><TabsList><TabsTrigger value="ledger">Ledger</TabsTrigger><TabsTrigger value="invoices">Invoices</TabsTrigger></TabsList>
      <TabsContent value="ledger"><div className="max-h-[45vh] overflow-auto rounded border"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Date</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">Description</th><th className="p-2 text-right">Debit</th><th className="p-2 text-right">Credit</th><th className="p-2 text-right">Balance</th></tr></thead><tbody className="divide-y">{(data?.lines ?? []).map((l: any, i: number) => <tr key={i}><td className="p-2">{fmtDate(l.entry_date)}</td><td className="p-2 text-xs">{titleCase(l.source_type ?? l.type)}</td><td className="p-2">{l.description}{l.reference && <span className="text-xs text-muted-foreground"> · {l.reference}</span>}</td><td className="p-2 text-right tabular">{Number(l.debit) ? fmtNum(l.debit, 2) : ''}</td><td className="p-2 text-right tabular">{Number(l.credit) ? fmtNum(l.credit, 2) : ''}</td><td className="p-2 text-right tabular">{fmtNum(l.balance, 2)}</td></tr>)}</tbody></table></div></TabsContent>
      <TabsContent value="invoices"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Invoice</th><th className="p-2 text-left">Date</th><th className="p-2 text-left">Due</th><th className="p-2 text-right">Total</th><th className="p-2 text-right">Balance</th><th className="p-2">Status</th><th /></tr></thead><tbody className="divide-y">{(data?.invoices ?? []).map((inv: any) => <tr key={inv.id}><td className="p-2">{inv.number}<div className="text-xs text-muted-foreground">{inv.description ?? titleCase(inv.type)}</div></td><td className="p-2">{fmtDate(inv.invoice_date ?? inv.created_at)}</td><td className="p-2">{fmtDate(inv.due_date)}</td><td className="p-2 text-right tabular">{fmtMoney(inv.total, currency)}</td><td className="p-2 text-right tabular">{fmtMoney(inv.balance, currency)}</td><td className="p-2"><StatusBadge status={inv.status} /></td><td className="p-2 text-right">{Number(inv.balance) > 0 && can('receivables.manage') && <Button size="sm" variant="ghost" onClick={() => setCn(inv)}><FileMinus />Credit note</Button>}</td></tr>)}</tbody></table></TabsContent>
    </Tabs>
    <FormDialog open={!!cn} onOpenChange={(o) => !o && setCn(null)} title={cn ? `Credit note against ${cn.number}` : ''} description="Reduces the receivable and reverses revenue via a Sales Returns posting." fields={[{ name: 'amount', label: 'Amount', type: 'money', required: true, default: cn ? Number(cn.balance) : 0 }, { name: 'reason', label: 'Reason', required: true, col: 2 }]} initial={{ amount: cn ? Number(cn.balance) : 0 }} onSubmit={(v) => creditNote.mutateAsync(v)} />
  </div></Modal>;
}
function ReceivablesInner() {
  const { can, currency } = useAuth(); const sp = useSearchParams(); const router = useRouter(); const [receipt, setReceipt] = useState<{ open: boolean; customer?: any; invoiceId?: string | null }>({ open: false }); const [stmt, setStmt] = useState<any>(null);
  const { data: aging } = useApi<any>('/receivables/aging'); const { data: customers } = useApi<any>('/customers', { pageSize: 500 });
  useEffect(() => { const inv = sp.get('invoice'); const cid = sp.get('customer'); if (inv) setReceipt({ open: true, invoiceId: inv, customer: cid ? customers?.data?.find((c: any) => c.id === cid) : undefined }); else if (cid && customers?.data) { const c = customers.data.find((x: any) => x.id === cid); if (c) setStmt(c); } }, [sp, customers]);
  const T = aging?.totals;
  return <div className="space-y-4">
    <PageHeader title="Receivables (city ledger)" subtitle="Corporate accounts, travel agents and direct-bill guests: aging, statements, receipts and credit notes." actions={can('receivables.manage', 'payments.create') && <Button onClick={() => setReceipt({ open: true })}><Banknote />Receive payment</Button>} />
    <div className="grid gap-3 grid-cols-3 md:grid-cols-6">{[['Total AR', T?.total], ['Current', T?.current], ['1–30', T?.d30], ['31–60', T?.d60], ['61–90', T?.d90], ['90+', T?.d90plus]].map(([k, v], i) => <div key={String(k)} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className={`text-lg font-semibold tabular ${i === 5 && Number(v) > 0 ? 'text-destructive' : ''}`}>{fmtMoney(v, currency)}</div></div>)}</div>
    <div className="text-xs text-muted-foreground">Guest ledger (in-house folios): {fmtMoney(aging?.guest_ledger_balance, currency)} — settled at checkout, not part of AR.</div>
    <Tabs defaultValue="aging"><TabsList><TabsTrigger value="aging">Aging by customer</TabsTrigger><TabsTrigger value="invoices">Open invoices</TabsTrigger><TabsTrigger value="customers">Customers</TabsTrigger></TabsList>
      <TabsContent value="aging"><Section><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Customer</th><th className="p-2 text-right">Current</th><th className="p-2 text-right">1–30</th><th className="p-2 text-right">31–60</th><th className="p-2 text-right">61–90</th><th className="p-2 text-right">90+</th><th className="p-2 text-right">Total</th><th className="p-2 text-right">Limit</th></tr></thead><tbody className="divide-y">{(aging?.data ?? []).map((r: any) => <tr key={r.id} className="cursor-pointer hover:bg-accent/50" onClick={() => setStmt(customers?.data?.find((c: any) => c.id === r.id) ?? r)}><td className="p-2">{r.name}<div className="text-xs text-muted-foreground">{r.payment_terms_days}d terms</div></td><td className="p-2 text-right tabular">{fmtNum(r.current, 0)}</td><td className="p-2 text-right tabular">{fmtNum(r.d30, 0)}</td><td className="p-2 text-right tabular">{fmtNum(r.d60, 0)}</td><td className="p-2 text-right tabular">{fmtNum(r.d90, 0)}</td><td className={`p-2 text-right tabular ${Number(r.d90plus) > 0 ? 'text-destructive font-medium' : ''}`}>{fmtNum(r.d90plus, 0)}</td><td className="p-2 text-right tabular font-semibold">{fmtMoney(r.total, currency)}</td><td className="p-2 text-right tabular">{Number(r.credit_limit) > 0 && Number(r.total) > Number(r.credit_limit) ? <Badge tone="destructive">over limit</Badge> : fmtNum(r.credit_limit, 0)}</td></tr>)}{(aging?.data ?? []).length === 0 && <tr><td colSpan={8} className="p-6 text-center text-muted-foreground">No outstanding receivables.</td></tr>}</tbody></table></Section></TabsContent>
      <TabsContent value="invoices"><DataTable path="/receivables/open-invoices" defaultSort="due_date" exportName="open-invoices" onRowClick={(r) => setReceipt({ open: true, invoiceId: r.id, customer: customers?.data?.find((c: any) => c.id === r.customer_id) })} filters={[{ key: 'customer_id', label: 'Customer', type: 'select', source: '/customers', sourceLabel: 'name' }, { key: 'type', label: 'Type', type: 'select', options: ['FOLIO', 'EVENT', 'POS', 'MANUAL', 'SERVICE'] }]}
        columns={[{ key: 'number', label: 'Invoice' }, { key: 'customer_name', label: 'Customer', render: (r) => r.customer_name ?? r.guest_name }, { key: 'invoice_date', label: 'Date', type: 'date' }, { key: 'due_date', label: 'Due', type: 'date' }, { key: 'days_overdue', label: 'Overdue', render: (r) => (Number(r.days_overdue) > 0 ? <Badge tone="destructive">{r.days_overdue}d</Badge> : <span className="text-muted-foreground">—</span>) }, { key: 'total', label: 'Total', type: 'money' }, { key: 'balance', label: 'Balance', type: 'money' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }]} /></TabsContent>
      <TabsContent value="customers"><ResourcePage embedded path="/customers" title="Customer" entity="customer" permissions={{ view: 'receivables.view', create: 'receivables.manage', edit: 'receivables.manage' }} fields={customerFields} defaultSort="name" extraActions={(r) => <Button size="sm" variant="ghost" onClick={(e) => { e.stopPropagation(); setStmt(r); }}>Statement</Button>} filters={[{ key: 'type', label: 'Type', type: 'select', options: CUSTOMER_TYPES }, { key: 'active', label: 'Active', type: 'select', options: [{ value: 'true', label: 'Active' }, { value: 'false', label: 'Inactive' }] }]}
        columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'type', label: 'Type', render: (r) => titleCase(r.type) }, { key: 'contact_name', label: 'Contact', hideOnMobile: true }, { key: 'phone', label: 'Phone', hideOnMobile: true }, { key: 'credit_limit', label: 'Credit limit', type: 'money' }, { key: 'payment_terms_days', label: 'Terms', render: (r) => `${r.payment_terms_days}d` }, { key: 'balance', label: 'Balance', type: 'money' }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
    </Tabs>
    <ReceiptDialog open={receipt.open} onOpenChange={(o) => { setReceipt((r) => ({ ...r, open: o })); if (!o && sp.get('invoice')) router.replace('/finance/receivables'); }} customer={receipt.customer} invoiceId={receipt.invoiceId} />
    <CustomerStatement customer={stmt} onClose={() => { setStmt(null); if (sp.get('customer')) router.replace('/finance/receivables'); }} onReceipt={() => setReceipt({ open: true, customer: stmt })} />
  </div>;
}
export default function ReceivablesPage() { return <Suspense fallback={null}><ReceivablesInner /></Suspense>; }
