'use client';
import React, { useRef, useState } from 'react';
import { Upload, Download, FileCheck2, AlertTriangle } from 'lucide-react';
import { api, download } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { PageHeader, Section } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Textarea, Label } from '@/components/ui/input';
import { fmtDateTime, titleCase } from '@/lib/utils';

export default function ImportPage() {
  const { data: templates } = useApi<any[]>('/imports/templates'); const { data: jobs, refetch } = useApi<any>('/imports'); const [entity, setEntity] = useState<string>(''); const [file, setFile] = useState<File | null>(null); const [csv, setCsv] = useState(''); const [result, setResult] = useState<any>(null); const fileRef = useRef<HTMLInputElement>(null);
  const tpl = (templates ?? []).find((t) => t.entity === entity);
  const run = useAction(async (commit: boolean) => { if (file) { const fd = new FormData(); fd.append('file', file); return api(`/imports/${entity}`, { method: 'POST', formData: fd, query: { commit } }); } return api(`/imports/${entity}`, { method: 'POST', body: { csv }, query: { commit } }); }, { silent: true, onSuccess: (r: any) => { setResult(r); refetch(); } });
  return <div className="space-y-4">
    <PageHeader title="Data import" subtitle="Bulk-load master data from CSV. Every import is validated row by row and previewed before anything is written; nothing is ever deleted." crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'Import' }]} />
    <div className="grid gap-4 lg:grid-cols-[300px_1fr]">
      <Section title="1. Choose what to import"><div className="space-y-1">{(templates ?? []).map((t) => <button key={t.entity} type="button" onClick={() => { setEntity(t.entity); setResult(null); }} className={`block w-full rounded px-2 py-1.5 text-left text-sm ${entity === t.entity ? 'bg-primary/10 font-medium text-primary' : 'hover:bg-accent'}`}>{titleCase(t.entity)}<span className="block text-xs text-muted-foreground">{t.columns.length} columns</span></button>)}</div></Section>
      <div className="space-y-4">{tpl ? <>
        <Section title={`2. Prepare the file — ${titleCase(tpl.entity)}`} actions={<Button size="sm" variant="outline" onClick={() => download(`/imports/templates/${tpl.entity}.csv`, {}, `${tpl.entity}-template.csv`)}><Download />Template CSV</Button>}><div className="flex flex-wrap gap-1">{tpl.columns.map((c: string) => <Badge key={c} tone="muted">{c}</Badge>)}</div><p className="mt-2 text-xs text-muted-foreground">Header row must use these column names. Lookups (room type, category, unit, supplier…) are matched by code or name. Existing records with the same code/number are updated, never duplicated.</p></Section>
        <Section title="3. Upload & validate"><div className="grid gap-3 md:grid-cols-2"><div className="space-y-2"><Label>CSV file</Label><input ref={fileRef} type="file" accept=".csv,text/csv" className="block w-full text-sm" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setCsv(''); }} /></div><div className="space-y-2"><Label>…or paste CSV</Label><Textarea rows={6} value={csv} onChange={(e) => { setCsv(e.target.value); setFile(null); if (fileRef.current) fileRef.current.value = ''; }} placeholder={tpl.columns.join(',')} className="font-mono text-xs" /></div></div><div className="mt-3 flex gap-2"><Button variant="outline" loading={run.isPending} disabled={!file && !csv.trim()} onClick={() => run.mutate(false)}><FileCheck2 />Validate (dry run)</Button><Button loading={run.isPending} disabled={(!file && !csv.trim()) || !result || result.errors?.length > 0 || result.job?.status === 'COMPLETED'} onClick={() => run.mutate(true)}><Upload />Import {result?.valid_rows ? `${result.valid_rows} rows` : ''}</Button></div></Section>
        {result && <Section title={result.job?.status === 'COMPLETED' ? `Imported ${result.imported_rows} row(s)` : `Validation: ${result.valid_rows}/${result.total_rows} rows valid`} actions={<StatusBadge status={result.job?.status ?? (result.errors?.length ? 'ERRORS' : 'VALID')} />}>{result.errors?.length > 0 && <div className="mb-3 rounded border border-destructive/40 bg-destructive/5 p-2 text-xs"><div className="mb-1 flex items-center gap-1 font-medium"><AlertTriangle className="h-3.5 w-3.5" />{result.errors.length} error(s) — fix and re-validate</div><ul className="max-h-40 list-disc overflow-auto pl-5">{result.errors.slice(0, 50).map((e: any, i: number) => <li key={i}>Row {e.row}: {e.message ?? e.error}{e.field && ` (${e.field})`}</li>)}</ul></div>}{result.preview?.length > 0 && <div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted uppercase text-muted-foreground"><tr>{Object.keys(result.preview[0]).map((k) => <th key={k} className="p-1 text-left">{k}</th>)}</tr></thead><tbody className="divide-y">{result.preview.map((r: any, i: number) => <tr key={i}>{Object.keys(result.preview[0]).map((k) => <td key={k} className="p-1 whitespace-nowrap">{String(r[k] ?? '')}</td>)}</tr>)}</tbody></table><div className="mt-1 text-xs text-muted-foreground">Showing first {result.preview.length} rows.</div></div>}</Section>}
      </> : <div className="rounded-lg border border-dashed p-12 text-center text-muted-foreground"><Upload className="mx-auto mb-2 h-8 w-8" />Select an import type.</div>}</div>
    </div>
    <Section title="Import history"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">When</th><th className="p-2 text-left">Entity</th><th className="p-2 text-left">File</th><th className="p-2 text-right">Rows</th><th className="p-2 text-right">Valid</th><th className="p-2 text-right">Imported</th><th className="p-2 text-left">By</th><th className="p-2">Status</th></tr></thead><tbody className="divide-y">{(jobs?.data ?? []).map((j: any) => <tr key={j.id}><td className="p-2 whitespace-nowrap">{fmtDateTime(j.created_at)}</td><td className="p-2">{titleCase(j.entity)}</td><td className="p-2 font-mono text-xs">{j.file_name}</td><td className="p-2 text-right">{j.total_rows}</td><td className="p-2 text-right">{j.valid_rows}</td><td className="p-2 text-right">{j.imported_rows}</td><td className="p-2">{j.user_name}</td><td className="p-2 text-center"><StatusBadge status={j.status} /></td></tr>)}{(jobs?.data ?? []).length === 0 && <tr><td colSpan={8} className="p-6 text-center text-muted-foreground">No imports yet.</td></tr>}</tbody></table></Section>
  </div>;
}
