'use client';
import React from 'react';
import { PageHeader } from '@/components/shared/page';
import { ResourcePage } from '@/components/shared/resource-page';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { useAuth } from '@/lib/auth';
import { fmtMoney } from '@/lib/utils';

const ROOM_STATUSES = ['VACANT', 'OCCUPIED', 'OUT_OF_ORDER', 'OUT_OF_SERVICE', 'RESERVED', 'DUE_OUT'];
export default function RoomsSetupPage() {
  const { currency } = useAuth();
  return <div className="space-y-4">
    <PageHeader title="Room types & rooms" subtitle="Room types drive availability, base pricing and occupancy limits; rooms are the physical inventory with floor, features and status." crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'Rooms' }]} />
    <Tabs defaultValue="types"><TabsList><TabsTrigger value="types">Room types</TabsTrigger><TabsTrigger value="rooms">Rooms</TabsTrigger></TabsList>
      <TabsContent value="types"><ResourcePage embedded path="/room-types" title="Room type" entity="room_type" permissions={{ view: 'room_types.view', create: 'room_types.manage', edit: 'room_types.manage', delete: 'room_types.manage' }} defaultSort="sort_order" dialogSize="lg" softDelete fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'base_rate', label: 'Base rate (per night)', type: 'money', required: true }, { name: 'extra_adult_rate', label: 'Extra adult rate', type: 'money', default: 0 }, { name: 'extra_child_rate', label: 'Extra child rate', type: 'money', default: 0 }, { name: 'max_adults', label: 'Max adults', type: 'number', default: 2 }, { name: 'max_children', label: 'Max children', type: 'number', default: 1 }, { name: 'max_occupancy', label: 'Max occupancy', type: 'number', default: 3 }, { name: 'bed_configuration', label: 'Bed configuration', placeholder: '1 King / 2 Twin' }, { name: 'size_sqm', label: 'Size (m²)', type: 'number' }, { name: 'sort_order', label: 'Sort order', type: 'number', default: 0 }, { name: 'amenities', label: 'Amenities', type: 'tags', col: 2 }, { name: 'description', label: 'Description', type: 'textarea', col: 2 }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]}
        columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'base_rate', label: 'Base rate', type: 'money' }, { key: 'max_occupancy', label: 'Occupancy', render: (r) => `${r.max_adults}A + ${r.max_children}C (max ${r.max_occupancy})` }, { key: 'bed_configuration', label: 'Beds', hideOnMobile: true }, { key: 'room_count', label: 'Rooms', type: 'number', decimals: 0 }, { key: 'amenities', label: 'Amenities', hideOnMobile: true, render: (r) => (r.amenities ?? []).slice(0, 4).map((a: string) => <Badge key={a} tone="muted" className="mr-1">{a}</Badge>) }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
      <TabsContent value="rooms"><ResourcePage embedded path="/rooms" title="Room" entity="room" permissions={{ view: 'rooms.view', create: 'rooms.create', edit: 'rooms.edit' }} defaultSort="number" softDelete fields={[{ name: 'number', label: 'Room number', required: true }, { name: 'room_type_id', label: 'Room type', type: 'lookup', source: '/room-types', sourceLabel: 'name', required: true }, { name: 'floor', label: 'Floor' }, { name: 'building', label: 'Building / wing' }, { name: 'rate_override', label: 'Rate override (blank = type rate)', type: 'money' }, { name: 'phone_extension', label: 'Phone extension' }, { name: 'features', label: 'Features (view, balcony…)', type: 'tags', col: 2 }, { name: 'amenities', label: 'Extra amenities', type: 'tags', col: 2 }, { name: 'notes', label: 'Notes', type: 'textarea', col: 2 }, { name: 'is_active', label: 'Active (sellable)', type: 'switch', default: true }]} filters={[{ key: 'room_type_id', label: 'Type', type: 'select', source: '/room-types', sourceLabel: 'name' }, { key: 'status', label: 'Status', type: 'select', options: ROOM_STATUSES }, { key: 'floor', label: 'Floor', type: 'text' }]}
        columns={[{ key: 'number', label: 'Room' }, { key: 'room_type_name', label: 'Type' }, { key: 'floor', label: 'Floor' }, { key: 'building', label: 'Building', hideOnMobile: true }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }, { key: 'housekeeping_status', label: 'HK', render: (r) => <StatusBadge status={r.housekeeping_status} /> }, { key: 'rate_override', label: 'Rate', render: (r) => (r.rate_override != null ? fmtMoney(r.rate_override, currency) : <span className="text-muted-foreground">type rate</span>) }, { key: 'features', label: 'Features', hideOnMobile: true, render: (r) => (r.features ?? []).join(', ') }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
    </Tabs>
  </div>;
}
