'use client';
import React, { Suspense, useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Plus, Check, AlertTriangle, X, Wallet } from 'lucide-react';
import { post, get } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, KV, Section } from '@/components/shared/page';
import { DataTable } from '@/components/shared/data-table';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Input, Label, Textarea } from '@/components/ui/input';
import { LookupSelect, ConfirmDialog } from '@/components/shared/form';
import { Switch } from '@/components/ui/misc';
import { LinesTable } from '@/components/inventory/product-lines';
import { AuditTrail } from '@/components/shared/audit-trail';
import { Attachments } from '@/components/shared/attachments';
import { fmtDate, fmtDateTime, fmtMoney, fmtNum, today, addDays } from '@/lib/utils';

interface Line { key: string; grn_item_id?: string | null; product_id?: string | null; description: string; sku?: string; grn_number?: string; max?: number | null; grn_unit_cost?: number | null; quantity: string | number; unit_price: string | number; tax_id?: string | null; account_id?: string | null }
/** Supplier invoice entry with 3-way match: lines default from completed GRNs (uninvoiced qty at GRN cost); price variances beyond tolerance need purchases.approve. */
function NewInvoice({ open, onOpenChange, preset, onCreated }: { open: boolean; onOpenChange: (o: boolean) => void; preset: { po?: string | null; grn?: string | null }; onCreated: (i: any) => void }) {
  const { currency, can } = useAuth();
  const [f, setF] = useState<any>({ supplier_id: '', supplier_invoice_no: '', purchase_order_id: preset.po ?? '', invoice_date: today(), due_date: '', notes: '', approve: true, tolerance_percent: 2 }); const [grns, setGrns] = useState<any[]>([]); const [picked, setPicked] = useState<Set<string>>(new Set()); const [lines, setLines] = useState<Line[]>([]); const [terms, setTerms] = useState(30);
  const set = (k: string, v: any) => setF((x: any) => ({ ...x, [k]: v }));
  useEffect(() => { (async () => {
    if (preset.grn) { const g = await get(`/grns/${preset.grn}`); setF((x: any) => ({ ...x, supplier_id: g.supplier_id, purchase_order_id: g.purchase_order_id ?? '' })); setGrns([g]); setPicked(new Set([g.id])); }
    else if (preset.po) { const po = await get(`/purchase-orders/${preset.po}`); setF((x: any) => ({ ...x, supplier_id: po.supplier_id })); const list = await Promise.all((po.grns ?? []).filter((g: any) => g.status === 'COMPLETED').map((g: any) => get(`/grns/${g.id}`))); setGrns(list); setPicked(new Set(list.map((g: any) => g.id))); }
  })(); }, [preset.grn, preset.po]);
  const { data: supGrns } = useApi<any>(!preset.grn && !preset.po && f.supplier_id ? '/grns' : null, { supplier_id: f.supplier_id, status: 'COMPLETED', pageSize: 50 });
  useEffect(() => { if (supGrns?.data && !preset.grn && !preset.po) Promise.all(supGrns.data.map((g: any) => get(`/grns/${g.id}`))).then(setGrns); }, [supGrns, preset.grn, preset.po]);
  const { data: sup } = useApi<any>(f.supplier_id ? `/suppliers/${f.supplier_id}` : null);
  useEffect(() => { if (sup) { setTerms(sup.payment_terms_days); set('due_date', addDays(f.invoice_date, Number(sup.payment_terms_days))); } }, [sup]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const ls: Line[] = []; for (const g of grns) if (picked.has(g.id)) for (const i of g.items ?? []) { const remaining = Number(i.accepted_qty) - Number(i.already_invoiced ?? 0); if (remaining <= 0 && i.already_invoiced != null) continue; ls.push({ key: i.id, grn_item_id: i.id, product_id: i.product_id, description: i.product_name ?? i.description, sku: i.sku, grn_number: g.number, max: remaining > 0 ? remaining : Number(i.accepted_qty), grn_unit_cost: Number(i.unit_cost), quantity: remaining > 0 ? remaining : Number(i.accepted_qty), unit_price: Number(i.unit_cost), tax_id: i.tax_id }); } setLines(ls); }, [grns, picked]);
  const setAt = (k: string, patch: Partial<Line>) => setLines((ls) => ls.map((l) => (l.key === k ? { ...l, ...patch } : l)));
  const subtotal = lines.reduce((s, l) => s + Number(l.quantity || 0) * Number(l.unit_price || 0), 0);
  const variances = lines.filter((l) => l.grn_unit_cost != null && Math.abs(Number(l.unit_price) - l.grn_unit_cost) / Math.max(0.01, l.grn_unit_cost) * 100 > Number(f.tolerance_percent));
  const create = useAction(() => post('/supplier-invoices', { ...f, purchase_order_id: f.purchase_order_id || null, due_date: f.due_date || undefined, notes: f.notes || null, grn_ids: [...picked], items: lines.map((l) => ({ grn_item_id: l.grn_item_id ?? null, product_id: l.product_id ?? null, description: l.description, quantity: Number(l.quantity), unit_price: Number(l.unit_price), tax_id: l.tax_id ?? null, account_id: l.account_id ?? null })) }, true), { success: 'Supplier invoice recorded', invalidate: ['/supplier-invoices', '/purchase-orders', '/grns', '/journals'], onSuccess: (i: any) => { onOpenChange(false); onCreated(i); } });
  const [freeDesc, setFreeDesc] = useState('');
  return <Modal open={open} onOpenChange={onOpenChange} title="Record supplier invoice" size="xl"><div className="space-y-3">
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
      <div className="flex flex-col gap-1 col-span-2"><Label>Supplier</Label><LookupSelect source="/suppliers" value={f.supplier_id} onChange={(v) => { set('supplier_id', v); if (!preset.grn && !preset.po) { setGrns([]); setPicked(new Set()); } }} allowEmpty={false} placeholder="Select supplier" disabled={!!(preset.grn || preset.po)} /></div>
      <div className="flex flex-col gap-1"><Label>Supplier invoice no.</Label><Input value={f.supplier_invoice_no} onChange={(e) => set('supplier_invoice_no', e.target.value)} placeholder="INV-2026-001" /></div>
      <div className="flex flex-col gap-1"><Label>Tolerance %</Label><Input type="number" step="0.5" value={f.tolerance_percent} onChange={(e) => set('tolerance_percent', e.target.value)} /></div>
      <div className="flex flex-col gap-1"><Label>Invoice date</Label><Input type="date" value={f.invoice_date} onChange={(e) => { set('invoice_date', e.target.value); set('due_date', addDays(e.target.value, terms)); }} /></div>
      <div className="flex flex-col gap-1"><Label>Due date</Label><Input type="date" value={f.due_date} onChange={(e) => set('due_date', e.target.value)} /></div>
      <div className="flex flex-col gap-1 col-span-2"><Label>Notes</Label><Input value={f.notes} onChange={(e) => set('notes', e.target.value)} /></div>
    </div>
    {grns.length > 0 && <div><Label>Match against goods received</Label><div className="mt-1 flex flex-wrap gap-2">{grns.map((g) => <label key={g.id} className={`flex items-center gap-2 rounded-md border px-2 py-1 text-sm ${picked.has(g.id) ? 'border-primary bg-primary/5' : ''}`}><input type="checkbox" checked={picked.has(g.id)} onChange={(e) => { const n = new Set(picked); e.target.checked ? n.add(g.id) : n.delete(g.id); setPicked(n); }} />{g.number} · {fmtDate(g.received_date)} · {fmtMoney(g.total_value, currency)}{g.po_number && <span className="text-xs text-muted-foreground">({g.po_number})</span>}</label>)}</div></div>}
    <div className="overflow-x-auto rounded-md border"><table className="w-full text-sm min-w-[800px]"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Item</th><th className="p-2 text-left">GRN</th><th className="p-2 text-right w-28">Qty</th><th className="p-2 text-right">GRN cost</th><th className="p-2 text-right w-32">Invoice price</th><th className="p-2 text-right">Line total</th><th className="w-8" /></tr></thead>
      <tbody className="divide-y">{lines.map((l) => { const varPct = l.grn_unit_cost ? (Number(l.unit_price) - l.grn_unit_cost) / l.grn_unit_cost * 100 : 0; const over = Math.abs(varPct) > Number(f.tolerance_percent); return <tr key={l.key} className={over ? 'bg-amber-500/5' : ''}><td className="p-2"><div className="font-medium">{l.description}</div><div className="text-xs text-muted-foreground">{l.sku}</div></td><td className="p-2 text-xs">{l.grn_number ?? '—'}</td><td className="p-1"><Input type="number" step="any" min={0} max={l.max ?? undefined} className="text-right" value={l.quantity} onChange={(e) => setAt(l.key, { quantity: e.target.value })} />{l.max != null && <div className="text-[10px] text-right text-muted-foreground">max {fmtNum(l.max, 2)}</div>}</td><td className="p-2 text-right tabular">{l.grn_unit_cost == null ? '—' : fmtMoney(l.grn_unit_cost, currency)}</td><td className="p-1"><Input type="number" step="0.01" className="text-right" value={l.unit_price} onChange={(e) => setAt(l.key, { unit_price: e.target.value })} />{l.grn_unit_cost != null && varPct !== 0 && <div className={`text-[10px] text-right ${over ? 'text-amber-600 font-medium' : 'text-muted-foreground'}`}>{varPct > 0 ? '+' : ''}{fmtNum(varPct, 1)}%</div>}</td><td className="p-2 text-right tabular">{fmtMoney(Number(l.quantity || 0) * Number(l.unit_price || 0), currency)}</td><td className="p-1"><Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => setLines(lines.filter((x) => x.key !== l.key))}>×</Button></td></tr>; })}{lines.length === 0 && <tr><td colSpan={7} className="p-6 text-center text-muted-foreground">Select GRNs to match, or add a service line below.</td></tr>}</tbody></table></div>
    <div className="flex gap-2"><Input placeholder="Service / non-stock line (e.g. delivery charge)" value={freeDesc} onChange={(e) => setFreeDesc(e.target.value)} /><Button variant="outline" disabled={!freeDesc.trim()} onClick={() => { setLines([...lines, { key: `free-${Date.now()}`, description: freeDesc.trim(), quantity: 1, unit_price: 0 }]); setFreeDesc(''); }}>Add line</Button></div>
    {variances.length > 0 && <div className="flex items-start gap-2 rounded-md border border-amber-500/50 bg-amber-500/10 p-2 text-sm"><AlertTriangle className="h-4 w-4 text-amber-600 mt-0.5" /><div>{variances.length} line{variances.length > 1 ? 's' : ''} exceed the {f.tolerance_percent}% price tolerance vs GRN cost.{!can('purchases.approve') && ' A purchasing manager must record/approve this invoice.'}</div></div>}
    <div className="flex flex-wrap items-center justify-between gap-2"><label className="flex items-center gap-2 text-sm"><Switch checked={f.approve} onCheckedChange={(v) => set('approve', v)} /> Approve & post to payables now</label><div className="flex items-center gap-3"><span className="text-sm">Subtotal <b>{fmtMoney(subtotal, currency)}</b> <span className="text-muted-foreground">(tax per line)</span></span><Button loading={create.isPending} disabled={!f.supplier_id || !f.supplier_invoice_no || lines.length === 0} onClick={() => create.mutate(undefined as any)}><Check />{f.approve ? 'Record & approve' : 'Save draft'}</Button></div></div>
  </div></Modal>;
}
function InvoiceDetail({ id, onClose }: { id: string | null; onClose: () => void }) {
  const { can, currency } = useAuth(); const router = useRouter(); const { data: si, refetch } = useApi<any>(id ? `/supplier-invoices/${id}` : null); const [dispute, setDispute] = useState(false); const [cancel, setCancel] = useState(false);
  const inv = ['/supplier-invoices', '/journals', '/purchase-orders'];
  const approveM = useAction(() => post(`/supplier-invoices/${id}/approve`), { success: 'Invoice approved — posted to payables', invalidate: inv, onSuccess: () => refetch() });
  const disputeM = useAction((v: any) => post(`/supplier-invoices/${id}/dispute`, v), { success: 'Marked disputed', invalidate: inv, onSuccess: () => { setDispute(false); refetch(); } });
  const cancelM = useAction((v: any) => post(`/supplier-invoices/${id}/cancel`, v), { success: 'Invoice cancelled (reversal posted)', invalidate: inv, onSuccess: () => { setCancel(false); refetch(); } });
  if (!id) return null;
  return <Modal open={!!id} onOpenChange={(o) => !o && onClose()} title={si ? <span className="flex items-center gap-2">{si.number} <Badge tone="muted">{si.type}</Badge> <StatusBadge status={si.status} /></span> : 'Supplier invoice'} size="xl">{si && <div className="space-y-4">
    <KV cols={4} items={[['Supplier', si.supplier_name], ['Supplier ref', si.supplier_invoice_no], ['PO', si.po_number ? <a key="po" className="underline" href={`/procurement/purchase-orders?id=${si.purchase_order_id}`}>{si.po_number}</a> : '—'], ['Invoice date', fmtDate(si.invoice_date)], ['Due', <span key="d" className={Number(si.days_overdue) > 0 && Number(si.balance) > 0 ? 'text-destructive' : ''}>{fmtDate(si.due_date)}{Number(si.days_overdue) > 0 && Number(si.balance) > 0 && ` · ${si.days_overdue}d overdue`}</span>], ['Subtotal / tax', `${fmtMoney(si.subtotal, currency)} / ${fmtMoney(si.tax_total, currency)}`], ['Total', <b key="t">{fmtMoney(si.total, currency)}</b>], ['Paid / balance', `${fmtMoney(si.paid_total, currency)} / ${fmtMoney(si.balance, currency)}`], ['Recorded', `${si.created_by_name} · ${fmtDateTime(si.created_at)}`], ['Journal', si.journal_entry_id ? <a key="j" className="underline" href={`/finance/journals?id=${si.journal_entry_id}`}>view</a> : 'not posted']]} />
    <LinesTable rows={si.items} columns={[{ key: 'description', label: 'Item', render: (i) => <div><div className="font-medium">{i.product_name ?? i.description}</div><div className="text-xs text-muted-foreground">{i.sku}{i.grn_number ? ` · ${i.grn_number}` : ''}</div></div> }, { key: 'quantity', label: 'Qty', align: 'right', render: (i) => fmtNum(i.quantity, 2) }, { key: 'grn_unit_cost', label: 'GRN cost', align: 'right', render: (i) => (i.grn_unit_cost == null ? '—' : fmtMoney(i.grn_unit_cost, currency)) }, { key: 'unit_price', label: 'Invoice price', align: 'right', render: (i) => <span className={i.grn_unit_cost != null && Number(i.unit_price) !== Number(i.grn_unit_cost) ? 'text-amber-600' : ''}>{fmtMoney(i.unit_price, currency)}</span> }, { key: 'tax_amount', label: 'Tax', align: 'right', render: (i) => fmtMoney(i.tax_amount, currency) }, { key: 'line_total', label: 'Total', align: 'right', render: (i) => fmtMoney(i.line_total, currency) }]} />
    <div className="flex flex-wrap gap-2">
      {['DRAFT', 'PENDING', 'DISPUTED'].includes(si.status) && can('purchases.approve', 'purchases.invoice') && <Button onClick={() => approveM.mutate(undefined as any)}><Check />Approve & post</Button>}
      {['APPROVED', 'PARTIALLY_PAID'].includes(si.status) && Number(si.balance) > 0 && can('payments.pay_supplier') && <Button onClick={() => router.push(`/procurement/supplier-payments?new=1&supplier_id=${si.supplier_id}&invoice_id=${si.id}`)}><Wallet />Pay</Button>}
      {['DRAFT', 'PENDING', 'APPROVED'].includes(si.status) && Number(si.paid_total) === 0 && can('purchases.invoice') && <Button variant="outline" onClick={() => setDispute(true)}><AlertTriangle />Dispute</Button>}
      {!['PAID', 'CANCELLED'].includes(si.status) && Number(si.paid_total) === 0 && can('purchases.approve') && <Button variant="ghost" onClick={() => setCancel(true)}><X />Cancel</Button>}
    </div>
    {si.payments?.length > 0 && <Section title="Payments"><ul className="divide-y text-sm">{si.payments.map((p: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{fmtDate(p.business_date)} · {p.number} · {p.method}{p.reference && ` · ${p.reference}`}</span><span className="tabular">{fmtMoney(p.amount, currency)}</span></li>)}</ul></Section>}
    {si.notes && <div className="text-sm"><span className="text-muted-foreground">Notes:</span> {si.notes}</div>}
    <Attachments entity="supplier_invoice" entityId={id} title="Scanned invoice" />
    <AuditTrail entity="supplier_invoice" entityId={id} />
    <ConfirmDialog open={dispute} onOpenChange={setDispute} title="Dispute invoice" confirmLabel="Mark disputed" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => disputeM.mutateAsync(v)} />
    <ConfirmDialog open={cancel} onOpenChange={setCancel} title="Cancel invoice" description="A reversing journal is posted; the GRN accrual is restored." destructive confirmLabel="Cancel invoice" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => cancelM.mutateAsync(v)} />
  </div>}</Modal>;
}
function SupplierInvoicesPageInner() {
  const { can, currency } = useAuth(); const sp = useSearchParams(); const router = useRouter(); const { data: aging } = useApi<any>('/supplier-invoices/aging');
  const [open, setOpen] = useState<{ po?: string | null; grn?: string | null } | null>(null); const [sel, setSel] = useState<string | null>(null); const [mode, setMode] = useState<'all' | 'unpaid' | 'overdue'>('all');
  useEffect(() => { if (sp.get('new')) setOpen({ po: sp.get('po'), grn: sp.get('grn') }); if (sp.get('id')) setSel(sp.get('id')); }, [sp]);
  const t = aging?.totals;
  return <div className="space-y-4">
    <PageHeader title="Supplier invoices" subtitle="Accounts payable: invoices matched to POs and GRNs, aged by due date." actions={can('purchases.invoice') && <Button onClick={() => setOpen({})}><Plus />Record invoice</Button>} />
    {t && <div className="grid gap-3 grid-cols-2 md:grid-cols-6">{[['Total payable', t.total], ['Current', t.current], ['1–30', t.d30], ['31–60', t.d60], ['61–90', t.d90], ['90+', t.d90plus]].map(([k, v], i) => <div key={String(k)} className={`rounded-lg border bg-card p-3 ${i >= 4 && Number(v) > 0 ? 'border-destructive/50' : ''}`}><div className="text-xs text-muted-foreground">{k}</div><div className="text-lg font-semibold tabular">{fmtMoney(v, currency)}</div></div>)}</div>}
    <DataTable path="/supplier-invoices" query={{ unpaid: mode === 'unpaid' ? 'true' : undefined, overdue: mode === 'overdue' ? 'true' : undefined }} defaultSort="created_at" onRowClick={(r) => setSel(r.id)} exportName="supplier_invoices" toolbar={<div className="flex gap-1">{(['all', 'unpaid', 'overdue'] as const).map((m) => <Button key={m} size="sm" variant={mode === m ? 'default' : 'outline'} onClick={() => setMode(m)}>{m === 'all' ? 'All' : m === 'unpaid' ? 'Unpaid' : 'Overdue'}</Button>)}</div>}
      filters={[{ key: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PENDING', 'APPROVED', 'PARTIALLY_PAID', 'PAID', 'DISPUTED', 'CANCELLED'] }, { key: 'supplier_id', label: 'Supplier', type: 'select', source: '/suppliers' }, { key: 'type', label: 'Type', type: 'select', options: ['INVOICE', 'CREDIT_NOTE'] }]}
      columns={[{ key: 'number', label: 'No.' }, { key: 'supplier_invoice_no', label: 'Supplier ref' }, { key: 'supplier_name', label: 'Supplier' }, { key: 'po_number', label: 'PO' }, { key: 'invoice_date', label: 'Date', type: 'date' }, { key: 'due_date', label: 'Due', render: (r) => <span className={Number(r.days_overdue) > 0 && Number(r.balance) > 0 ? 'text-destructive' : ''}>{fmtDate(r.due_date)}</span> }, { key: 'total', label: 'Total', type: 'money' }, { key: 'paid_total', label: 'Paid', type: 'money' }, { key: 'balance', label: 'Balance', type: 'money' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }]} />
    {open && <NewInvoice open={!!open} preset={open} onOpenChange={(o) => { if (!o) { setOpen(null); router.replace('/procurement/supplier-invoices'); } }} onCreated={(i) => setSel(i.id)} />}
    <InvoiceDetail id={sel} onClose={() => { setSel(null); if (sp.get('id')) router.replace('/procurement/supplier-invoices'); }} />
  </div>;
}
export default function SupplierInvoicesPage() { return <Suspense fallback={null}><SupplierInvoicesPageInner /></Suspense>; }
