'use client';
import React, { useState } from 'react';
import { Plus, Trash2, Save, GitBranch } from 'lucide-react';
import { post, put, del } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Badge, StatusBadge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Input, Label, NativeSelect } from '@/components/ui/input';
import { Switch } from '@/components/ui/misc';
import { LookupSelect, ConfirmDialog } from '@/components/shared/form';
import { fmtMoney, titleCase } from '@/lib/utils';

const TX_TYPES = ['PURCHASE_REQUISITION', 'PURCHASE_ORDER', 'SUPPLIER_PAYMENT', 'EXPENSE', 'STOCK_ADJUSTMENT', 'WASTE', 'STOCKTAKE', 'MAINTENANCE_REQUEST', 'CASH_VARIANCE', 'REFUND', 'CREDIT_NOTE', 'RATE_OVERRIDE'];
const DOCS = ['QUOTATION', 'INVOICE', 'RECEIPT', 'DELIVERY_NOTE', 'PHOTO', 'APPROVAL_MEMO'];
const emptyStep = () => ({ step_order: 1, name: '', approver_role_id: '', approver_user_id: '', required_permission: '', min_amount: 0 });
function Editor({ wf, onClose, onSaved }: { wf: any | null; onClose: () => void; onSaved: () => void }) {
  const { currency } = useAuth(); const { data: perms } = useApi<any>('/permissions'); const [f, setF] = useState<any>(() => wf && wf.id ? { ...wf, max_amount: wf.max_amount ?? '', escalation_hours: wf.escalation_hours ?? '', steps: (wf.steps ?? []).map((s: any) => ({ ...s, approver_role_id: s.approver_role_id ?? '', approver_user_id: s.approver_user_id ?? '', required_permission: s.required_permission ?? '' })), scope: wf.property_id ? 'PROPERTY' : 'GLOBAL' } : { transaction_type: 'PURCHASE_REQUISITION', name: '', min_amount: 0, max_amount: '', is_active: true, required_documents: [], escalation_hours: '', steps: [emptyStep()], scope: 'PROPERTY' });
  const body = () => ({ transaction_type: f.transaction_type, name: f.name, min_amount: Number(f.min_amount || 0), max_amount: f.max_amount === '' ? null : Number(f.max_amount), is_active: f.is_active, required_documents: f.required_documents, escalation_hours: f.escalation_hours === '' ? null : Number(f.escalation_hours), scope: f.scope, steps: f.steps.map((s: any, i: number) => ({ step_order: i + 1, name: s.name, approver_role_id: s.approver_role_id || null, approver_user_id: s.approver_user_id || null, required_permission: s.required_permission || null, min_amount: Number(s.min_amount || 0) })) });
  const save = useAction(() => (f.id ? put(`/workflows/${f.id}`, body()) : post('/workflows', body())), { success: 'Workflow saved', invalidate: ['/workflows'], onSuccess: () => { onSaved(); onClose(); } });
  const setStep = (i: number, patch: any) => setF({ ...f, steps: f.steps.map((s: any, j: number) => (j === i ? { ...s, ...patch } : s)) });
  const allPerms: string[] = (perms?.data ?? []).map((p: any) => p.code);
  return <Modal open onOpenChange={(o) => !o && onClose()} title={f.id ? `Edit: ${f.name}` : 'New approval workflow'} size="xl"><div className="space-y-4">
    <div className="grid gap-3 md:grid-cols-4"><div className="flex flex-col gap-1"><Label>Transaction type</Label><NativeSelect value={f.transaction_type} onChange={(e) => setF({ ...f, transaction_type: e.target.value })}>{TX_TYPES.map((t) => <option key={t} value={t}>{titleCase(t)}</option>)}</NativeSelect></div><div className="flex flex-col gap-1 md:col-span-2"><Label>Name</Label><Input value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} placeholder="e.g. Purchase orders above 100k" /></div><div className="flex flex-col gap-1"><Label>Scope</Label><NativeSelect value={f.scope} onChange={(e) => setF({ ...f, scope: e.target.value })}><option value="PROPERTY">This property</option><option value="GLOBAL">All properties</option></NativeSelect></div>
      <div className="flex flex-col gap-1"><Label>Applies from amount</Label><Input type="number" value={f.min_amount} onChange={(e) => setF({ ...f, min_amount: e.target.value })} /></div><div className="flex flex-col gap-1"><Label>Up to amount (blank = no cap)</Label><Input type="number" value={f.max_amount} onChange={(e) => setF({ ...f, max_amount: e.target.value })} /></div><div className="flex flex-col gap-1"><Label>Escalate after (hours)</Label><Input type="number" value={f.escalation_hours} onChange={(e) => setF({ ...f, escalation_hours: e.target.value })} /></div><label className="flex items-center justify-between rounded border p-2 text-sm"><span>Active</span><Switch checked={!!f.is_active} onCheckedChange={(v) => setF({ ...f, is_active: v })} /></label></div>
    <div><Label>Required documents before submission</Label><div className="mt-1 flex flex-wrap gap-1">{DOCS.map((d) => <button key={d} type="button" onClick={() => setF({ ...f, required_documents: f.required_documents.includes(d) ? f.required_documents.filter((x: string) => x !== d) : [...f.required_documents, d] })} className={`rounded-full border px-2 py-0.5 text-xs ${f.required_documents.includes(d) ? 'border-primary bg-primary/10 text-primary' : ''}`}>{titleCase(d)}</button>)}</div></div>
    <Section title="Approval steps (in order)" description="Each step is satisfied by any user holding the role / the named user / the permission. A step's own minimum amount lets you add a second signature only for large values."><div className="space-y-2">{f.steps.map((s: any, i: number) => <div key={i} className="grid items-end gap-2 rounded border p-2 md:grid-cols-[2rem_1fr_1fr_1fr_1fr_8rem_2rem]"><div className="pb-2 text-center text-sm font-semibold">{i + 1}</div><div className="flex flex-col gap-1"><Label>Step name</Label><Input value={s.name} onChange={(e) => setStep(i, { name: e.target.value })} placeholder="Department head" /></div><LookupSelect label="Approver role" source="/roles" sourceLabel="name" value={s.approver_role_id} onChange={(v) => setStep(i, { approver_role_id: v })} placeholder="Any role" /><LookupSelect label="or specific user" source="/users" sourceLabel="full_name" value={s.approver_user_id} onChange={(v) => setStep(i, { approver_user_id: v })} placeholder="Any user" /><div className="flex flex-col gap-1"><Label>or permission</Label><NativeSelect value={s.required_permission} onChange={(e) => setStep(i, { required_permission: e.target.value })}><option value="">—</option>{allPerms.filter((p) => /approve|manage|admin/.test(p)).map((p) => <option key={p} value={p}>{p}</option>)}</NativeSelect></div><div className="flex flex-col gap-1"><Label>Only if ≥</Label><Input type="number" value={s.min_amount} onChange={(e) => setStep(i, { min_amount: e.target.value })} /></div><Button size="icon" variant="ghost" className="mb-0.5" disabled={f.steps.length <= 1} onClick={() => setF({ ...f, steps: f.steps.filter((_: any, j: number) => j !== i) })}><Trash2 className="h-4 w-4" /></Button></div>)}<Button size="sm" variant="outline" onClick={() => setF({ ...f, steps: [...f.steps, { ...emptyStep(), step_order: f.steps.length + 1 }] })}><Plus />Add step</Button></div></Section>
    <div className="flex justify-end"><Button loading={save.isPending} disabled={!f.name || f.steps.some((s: any) => !s.name || (!s.approver_role_id && !s.approver_user_id && !s.required_permission))} onClick={() => save.mutate(undefined as any)}><Save />Save workflow</Button></div>
  </div></Modal>;
}
export default function WorkflowsPage() {
  const { can, currency } = useAuth(); const { data, refetch } = useApi<any>('/workflows'); const [edit, setEdit] = useState<any>(null); const [remove, setRemove] = useState<any>(null);
  const removeM = useAction(() => del(`/workflows/${remove.id}`), { success: 'Workflow removed', invalidate: ['/workflows'], onSuccess: () => { setRemove(null); refetch(); } });
  const rows: any[] = data?.data ?? []; const groups = rows.reduce<Record<string, any[]>>((g, r) => { (g[r.transaction_type] ??= []).push(r); return g; }, {});
  return <div className="space-y-4">
    <PageHeader title="Approval workflows" subtitle="Configurable multi-step approvals by transaction type and amount band. When a document is submitted, the matching workflow is selected automatically and the approval inbox routes each step." crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'Workflows' }]} actions={can('settings.workflows') && <Button onClick={() => setEdit({})}><Plus />New workflow</Button>} />
    {rows.length === 0 && <div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground"><GitBranch className="mx-auto mb-2 h-8 w-8" />No workflows — documents are auto-approved on submission until you add one.</div>}
    <div className="grid gap-4 md:grid-cols-2">{Object.entries(groups).map(([type, list]) => <Section key={type} title={titleCase(type)}><ul className="divide-y">{list.sort((a, b) => Number(a.min_amount) - Number(b.min_amount)).map((w) => <li key={w.id} className="py-2"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 font-medium">{w.name}<StatusBadge status={w.is_active ? 'ACTIVE' : 'INACTIVE'} /><Badge tone="muted">{w.property_id ? 'property' : 'global'}</Badge></div><div className="text-xs text-muted-foreground">Amount {fmtMoney(w.min_amount, currency)} → {w.max_amount != null ? fmtMoney(w.max_amount, currency) : '∞'}{w.escalation_hours && ` · escalates after ${w.escalation_hours}h`}{(w.required_documents ?? []).length > 0 && ` · requires ${w.required_documents.map(titleCase).join(', ')}`}</div><ol className="mt-1 flex flex-wrap gap-1">{(w.steps ?? []).map((s: any) => <li key={s.id ?? s.step_order} className="rounded border bg-muted/40 px-2 py-0.5 text-xs"><b>{s.step_order}.</b> {s.name} <span className="text-muted-foreground">— {s.role_name ?? s.user_name ?? s.required_permission}{Number(s.min_amount) > 0 && ` (≥ ${fmtMoney(s.min_amount, currency)})`}</span></li>)}</ol></div>{can('settings.workflows') && <div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => setEdit(w)}>Edit</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => setRemove(w)}><Trash2 className="h-4 w-4" /></Button></div>}</div></li>)}</ul></Section>)}</div>
    {edit && <Editor wf={edit.id ? edit : null} onClose={() => setEdit(null)} onSaved={() => refetch()} />}
    <ConfirmDialog open={!!remove} onOpenChange={(o) => !o && setRemove(null)} title={`Remove ${remove?.name}?`} description="Pending requests already routed keep their steps; new submissions will fall back to the next matching workflow or auto-approve." destructive confirmLabel="Remove" onConfirm={() => removeM.mutateAsync(undefined as any)} />
  </div>;
}
