'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { Download } from 'lucide-react';
import { download } from '@/lib/api';
import { useApi } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Input, Label } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtMoney, fmtNum, today, addDays, titleCase } from '@/lib/utils';

function StatementTable({ title, section, currency, sign = 1 }: { title: string; section: any; currency: string; sign?: number }) {
  return <Section title={title} actions={<span className="font-semibold tabular">{fmtMoney(section?.total, currency)}</span>}><table className="w-full text-sm"><tbody className="divide-y">{(section?.items ?? []).map((r: any) => <tr key={r.id}><td className="py-1"><span className="text-muted-foreground mr-2">{r.code}</span>{r.name}{r.parent_name && <span className="text-xs text-muted-foreground"> · {r.parent_name}</span>}</td><td className="py-1 text-right tabular"><Link href={`/finance/accounts?ledger=${r.id}`} className="hover:underline">{fmtMoney(r.amount * sign, currency)}</Link></td></tr>)}{(section?.items ?? []).length === 0 && <tr><td className="py-2 text-muted-foreground">No activity.</td></tr>}</tbody></table></Section>;
}
/** Finance overview: P&L, balance sheet, trial balance and tax report for a period — all straight from the posted journal. */
export default function FinancePage() {
  const { currency } = useAuth(); const [from, setFrom] = useState(today().slice(0, 8) + '01'); const [to, setTo] = useState(today());
  const { data: pl } = useApi<any>('/journals/profit-loss', { from, to }); const { data: bs } = useApi<any>('/journals/balance-sheet', { as_of: to }); const { data: tb } = useApi<any>('/journals/trial-balance', { from, to }); const { data: tax } = useApi<any>('/journals/tax-report', { from, to }); const { data: ar } = useApi<any>('/receivables/aging'); const { data: ap } = useApi<any>('/supplier-invoices/aging');
  return <div className="space-y-4">
    <PageHeader title="Finance overview" subtitle="Real-time financial statements generated from immutable, balanced journal entries." actions={<div className="flex items-end gap-2"><div className="flex flex-col gap-1"><Label>From</Label><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="w-40" /></div><div className="flex flex-col gap-1"><Label>To</Label><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="w-40" /></div><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => { setFrom(today().slice(0, 8) + '01'); setTo(today()); }}>MTD</Button><Button size="sm" variant="ghost" onClick={() => { setFrom(today().slice(0, 4) + '-01-01'); setTo(today()); }}>YTD</Button><Button size="sm" variant="ghost" onClick={() => { setFrom(addDays(today(), -30)); setTo(today()); }}>30d</Button></div></div>} />
    <div className="grid gap-3 grid-cols-2 md:grid-cols-6">{[['Revenue', pl?.revenue?.total], ['Cost of sales', pl?.cost_of_sales?.total], ['Gross profit', pl?.gross_profit, `${fmtNum(pl?.gross_margin_percent, 1)}% margin`], ['Expenses', pl?.expenses?.total], ['Net profit', pl?.net_profit], ['Cash & bank', bs?.assets?.items?.filter((a: any) => /cash|bank|m-?pesa|mobile/i.test(a.name)).reduce((s: number, a: any) => s + Number(a.amount), 0)]].map(([k, v, sub]) => <div key={String(k)} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className={`text-lg font-semibold tabular ${k === 'Net profit' ? (Number(v) >= 0 ? 'text-emerald-600' : 'text-destructive') : ''}`}>{fmtMoney(v, currency)}</div>{sub && <div className="text-xs text-muted-foreground">{sub}</div>}</div>)}</div>
    <div className="grid gap-3 md:grid-cols-2"><Link href="/finance/receivables" className="rounded-lg border bg-card p-3 hover:bg-accent"><div className="text-xs text-muted-foreground">Accounts receivable (city ledger)</div><div className="text-lg font-semibold tabular">{fmtMoney(ar?.totals?.total, currency)}</div><div className="text-xs text-muted-foreground">90+ days: {fmtMoney(ar?.totals?.d90plus, currency)} · guest ledger {fmtMoney(ar?.guest_ledger_balance, currency)}</div></Link><Link href="/procurement/supplier-invoices" className="rounded-lg border bg-card p-3 hover:bg-accent"><div className="text-xs text-muted-foreground">Accounts payable</div><div className="text-lg font-semibold tabular">{fmtMoney(ap?.totals?.total, currency)}</div><div className="text-xs text-muted-foreground">90+ days: {fmtMoney(ap?.totals?.d90plus, currency)}</div></Link></div>
    <Tabs defaultValue="pl"><TabsList><TabsTrigger value="pl">Profit & loss</TabsTrigger><TabsTrigger value="bs">Balance sheet</TabsTrigger><TabsTrigger value="tb">Trial balance</TabsTrigger><TabsTrigger value="tax">Tax report</TabsTrigger></TabsList>
      <TabsContent value="pl" className="grid gap-4 lg:grid-cols-2"><div className="space-y-4"><StatementTable title="Revenue" section={pl?.revenue} currency={currency} /><StatementTable title="Cost of sales" section={pl?.cost_of_sales} currency={currency} /></div><div className="space-y-4"><StatementTable title="Operating expenses" section={pl?.expenses} currency={currency} /><Section title="Revenue by outlet"><ul className="divide-y text-sm">{(pl?.revenue_by_outlet ?? []).map((o: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{o.outlet ?? 'Rooms / other'}</span><span className="tabular">{fmtMoney(o.revenue, currency)}</span></li>)}</ul></Section><div className="rounded-lg border p-3 text-sm flex justify-between"><span>Net profit {pl?.from} → {pl?.to}</span><b className={Number(pl?.net_profit) >= 0 ? 'text-emerald-600' : 'text-destructive'}>{fmtMoney(pl?.net_profit, currency)}</b></div></div></TabsContent>
      <TabsContent value="bs" className="grid gap-4 lg:grid-cols-2"><StatementTable title="Assets" section={bs?.assets} currency={currency} /><div className="space-y-4"><StatementTable title="Liabilities" section={bs?.liabilities} currency={currency} /><StatementTable title="Equity" section={bs?.equity} currency={currency} /><KV items={[['Retained earnings (current)', fmtMoney(bs?.equity?.retained_earnings, currency)], ['Total equity', fmtMoney(bs?.equity?.total_with_earnings, currency)], ['Liabilities + equity', fmtMoney(Number(bs?.liabilities?.total ?? 0) + Number(bs?.equity?.total_with_earnings ?? 0), currency)], ['Assets', fmtMoney(bs?.assets?.total, currency)]]} /></div></TabsContent>
      <TabsContent value="tb"><Section title={`Trial balance ${tb?.from ?? ''} → ${tb?.to ?? ''}`} actions={<span className={`text-xs ${tb?.balanced ? 'text-emerald-600' : 'text-destructive'}`}>{tb?.balanced ? 'Balanced' : 'OUT OF BALANCE'}</span>}><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left py-1">Account</th><th className="text-left">Type</th><th className="text-right">Opening</th><th className="text-right">Debit</th><th className="text-right">Credit</th><th className="text-right">Closing Dr</th><th className="text-right">Closing Cr</th></tr></thead><tbody className="divide-y">{(tb?.rows ?? []).map((r: any) => <tr key={r.id}><td className="py-1"><Link href={`/finance/accounts?ledger=${r.id}`} className="hover:underline"><span className="text-muted-foreground mr-2">{r.code}</span>{r.name}</Link></td><td className="text-xs">{titleCase(r.type)}</td><td className="text-right tabular">{fmtNum(r.opening, 2)}</td><td className="text-right tabular">{fmtNum(r.debit, 2)}</td><td className="text-right tabular">{fmtNum(r.credit, 2)}</td><td className="text-right tabular">{fmtNum(r.closing_debit, 2)}</td><td className="text-right tabular">{fmtNum(r.closing_credit, 2)}</td></tr>)}</tbody><tfoot><tr className="font-semibold border-t"><td className="py-2" colSpan={2}>Totals</td><td className="text-right tabular">{fmtNum(tb?.totals?.opening, 2)}</td><td className="text-right tabular">{fmtNum(tb?.totals?.debit, 2)}</td><td className="text-right tabular">{fmtNum(tb?.totals?.credit, 2)}</td><td className="text-right tabular">{fmtNum(tb?.totals?.closing_debit, 2)}</td><td className="text-right tabular">{fmtNum(tb?.totals?.closing_credit, 2)}</td></tr></tfoot></table></div></Section></TabsContent>
      <TabsContent value="tax"><div className="grid gap-4 lg:grid-cols-2"><Section title="Tax accounts"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left py-1">Tax</th><th className="text-right">Rate</th><th className="text-right">Output tax</th><th className="text-right">Input tax</th><th className="text-right">Net payable</th></tr></thead><tbody className="divide-y">{(tax?.taxes ?? []).map((t: any, i: number) => <tr key={i}><td className="py-1">{t.name ?? t.code}</td><td className="text-right">{fmtNum(t.rate, 1)}%</td><td className="text-right tabular">{fmtMoney(t.output_tax, currency)}</td><td className="text-right tabular">{fmtMoney(t.input_tax, currency)}</td><td className="text-right tabular font-medium">{fmtMoney(t.net_payable, currency)}</td></tr>)}</tbody></table></Section><Section title="Folio tax by category"><ul className="divide-y text-sm">{(tax?.folio_tax_by_category ?? []).map((r: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{titleCase(r.category)}</span><span className="tabular">taxable {fmtMoney(r.taxable, currency)} · tax {fmtMoney(r.tax, currency)}</span></li>)}</ul></Section></div></TabsContent>
    </Tabs>
  </div>;
}
