'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { Moon, Play, AlertTriangle, CheckCircle2, RotateCcw, FileText } from 'lucide-react';
import { post } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/misc';
import { Label, Textarea } from '@/components/ui/input';
import { ConfirmDialog } from '@/components/shared/form';
import { fmtDate, fmtDateTime, fmtMoney, fmtNum, titleCase } from '@/lib/utils';

function Stats({ s, currency }: { s: any; currency: string }) {
  if (!s) return null;
  return <div className="space-y-3"><div className="grid gap-3 grid-cols-2 md:grid-cols-4 lg:grid-cols-8">{[['Occupancy', `${fmtNum(s.occupancy_percent, 1)}%`, `${s.rooms_occupied}/${s.rooms_available ?? s.rooms_total} rooms`], ['ADR', fmtMoney(s.adr, currency)], ['RevPAR', fmtMoney(s.revpar, currency)], ['Room revenue', fmtMoney(s.room_revenue, currency)], ['Total revenue', fmtMoney(s.total_revenue, currency)], ['Guests in house', s.guests_in_house], ['Guest ledger', fmtMoney(s.guest_ledger_balance, currency)], ['City ledger', fmtMoney(s.city_ledger_balance, currency)]].map(([k, v, sub]) => <div key={String(k)} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className="text-lg font-semibold tabular">{v as any}</div>{sub && <div className="text-xs text-muted-foreground">{sub}</div>}</div>)}</div>
    <div className="grid gap-3 md:grid-cols-3"><Section title="Revenue by category"><ul className="divide-y text-sm">{(s.revenue_by_category ?? []).map((r: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{titleCase(r.category)}</span><span className="tabular">{fmtMoney(r.net ?? r.amount ?? r.total, currency)}{r.tax !== undefined && <span className="text-xs text-muted-foreground"> + tax {fmtNum(r.tax, 0)}</span>}</span></li>)}</ul></Section><Section title="POS by outlet"><ul className="divide-y text-sm">{(s.pos_by_outlet ?? []).map((r: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{r.outlet}</span><span className="tabular">{fmtMoney(r.amount ?? r.total, currency)} <span className="text-xs text-muted-foreground">({r.count ?? r.orders})</span></span></li>)}</ul></Section><Section title="Payments by method"><ul className="divide-y text-sm">{(s.payments_by_method ?? []).map((r: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{r.method ?? r.method_name}</span><span className="tabular">{fmtMoney(r.amount ?? r.total, currency)}</span></li>)}</ul></Section></div>
    {(s.arrivals !== undefined) && <KV cols={4} items={[['Arrivals', s.arrivals], ['Departures', s.departures], ['No-shows', s.no_shows], ['Cancellations', s.cancellations], ['Out of order', s.rooms_out_of_order], ['Tax collected', fmtMoney(s.tax_total, currency)]]} />}
  </div>;
}
export default function NightAuditPage() {
  const { can, currency } = useAuth(); const { data: cur, refetch: refetchCur } = useApi<any>('/business-days/current'); const { data: prev, refetch: refetchPrev } = useApi<any>(can('accounting.night_audit') ? '/business-days/night-audit/preview' : null); const { data: days, refetch: refetchDays } = useApi<any>('/business-days', { pageSize: 30 });
  const [opts, setOpts] = useState({ mark_no_shows: true, post_room_charges: true, force: false, notes: '' }); const [confirm, setConfirm] = useState(false); const [report, setReport] = useState<any>(null); const [reopen, setReopen] = useState<any>(null);
  const run = useAction(() => post('/business-days/night-audit/run', { ...opts, notes: opts.notes || undefined }), { success: 'Night audit complete — business date rolled', invalidate: ['/business-days', '/dashboard', '/journals'], onSuccess: (r: any) => { setConfirm(false); setReport(r); refetchCur(); refetchPrev(); refetchDays(); } });
  const reopenM = useAction((v: any) => post(`/business-days/${reopen.business_date}/reopen`, v), { success: 'Business day reopened', invalidate: ['/business-days'], onSuccess: () => { setReopen(null); refetchCur(); refetchDays(); } });
  const list: any[] = days?.data ?? (Array.isArray(days) ? days : []); const blocked = (prev?.blocking ?? []).length > 0;
  const Check = ({ ok, warn, label, count, children }: { ok?: boolean; warn?: boolean; label: string; count?: number; children?: React.ReactNode }) => <details className={`rounded-lg border p-3 ${ok ? '' : warn ? 'border-amber-400/60 bg-amber-50/40 dark:bg-amber-950/20' : 'border-destructive/60 bg-destructive/5'}`}><summary className="flex cursor-pointer items-center gap-2 text-sm font-medium">{ok ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : <AlertTriangle className={`h-4 w-4 ${warn ? 'text-amber-500' : 'text-destructive'}`} />}{label}{count !== undefined && count > 0 && <Badge tone={warn ? 'warning' : 'destructive'}>{count}</Badge>}</summary>{children && <div className="mt-2 text-xs">{children}</div>}</details>;
  return <div className="space-y-4">
    <PageHeader title="Night audit & business date" subtitle="Close the hotel day: post room & tax charges to in-house folios, mark no-shows, snapshot statistics and roll the business date. Nothing rolls while cash drawers or POS checks are open." actions={<div className="rounded-lg border bg-card px-3 py-2 text-sm"><span className="text-muted-foreground">Business date</span> <b>{fmtDate(cur?.business_date)}</b> <StatusBadge status={cur?.status ?? 'OPEN'} /><span className="ml-2 text-xs text-muted-foreground">calendar {fmtDate(cur?.calendar_date)}</span></div>} />
    {can('accounting.night_audit') ? <div className="grid gap-4 lg:grid-cols-3">
      <div className="space-y-2 lg:col-span-2">
        <h3 className="text-sm font-semibold">Pre-audit checklist for {fmtDate(prev?.business_date)}</h3>
        <Check ok={!prev?.open_shifts?.length} label="Cashier shifts closed" count={prev?.open_shifts?.length}>{prev?.open_shifts?.map((s: any) => <div key={s.id}>{s.number} · {s.cashier} · {s.outlet ?? 'Front desk'} · opened {fmtDateTime(s.opened_at)}</div>)}<Link href="/pos/shifts" className="underline">Go to shifts</Link></Check>
        <Check ok={!prev?.open_orders?.length} label="POS orders settled" count={prev?.open_orders?.length}>{prev?.open_orders?.map((o: any) => <div key={o.id}><Link href={`/pos/orders/${o.id}`} className="underline">{o.number}</Link> · {o.outlet} · {o.status} · {fmtMoney(o.total, currency)}</div>)}</Check>
        <Check ok={!prev?.due_outs?.length} warn label="Due-outs still in house (will be charged another night)" count={prev?.due_outs?.length}>{prev?.due_outs?.map((s: any) => <div key={s.id}>Room {s.room} · {s.guest} · expected out {fmtDate(s.expected_check_out)}</div>)}<Link href="/front-office/in-house" className="underline">In-house list</Link></Check>
        <Check ok={!prev?.unarrived?.length} warn label="Unarrived reservations (will be marked no-show)" count={prev?.unarrived?.length}>{prev?.unarrived?.map((r: any) => <div key={r.id}>{r.number} · {r.guest} · arrival {fmtDate(r.arrival_date)} · {r.status}</div>)}</Check>
        <Check ok={!prev?.pending_variance?.length} warn label="Cash variances awaiting approval" count={prev?.pending_variance?.length}>{prev?.pending_variance?.map((s: any) => <div key={s.id}>{s.number} · variance {fmtMoney(s.variance, currency)}</div>)}</Check>
        <Check ok={!prev?.high_balances?.length} warn label="High-balance folios" count={prev?.high_balances?.length}>{prev?.high_balances?.map((f: any) => <div key={f.id}>Room {f.room} · {f.guest} · {f.number} · {fmtMoney(f.balance, currency)}</div>)}</Check>
        <Check ok label={`Room & tax charges to post: ${prev?.room_charges_to_post?.length ?? 0} stay(s)`}>{prev?.room_charges_to_post?.map((s: any) => <div key={s.id}>Room {s.room} · {s.guest} · {fmtMoney(s.rate, currency)}</div>)}</Check>
      </div>
      <Section title="Run night audit" className="h-fit"><div className="space-y-3 text-sm">
        <label className="flex items-center justify-between gap-2"><span>Post room charges & taxes</span><Switch checked={opts.post_room_charges} onCheckedChange={(v) => setOpts({ ...opts, post_room_charges: v })} /></label>
        <label className="flex items-center justify-between gap-2"><span>Mark unarrived reservations as no-show</span><Switch checked={opts.mark_no_shows} onCheckedChange={(v) => setOpts({ ...opts, mark_no_shows: v })} /></label>
        {blocked && can('accounting.periods') && <label className="flex items-center justify-between gap-2 text-destructive"><span>Force run despite blocking issues</span><Switch checked={opts.force} onCheckedChange={(v) => setOpts({ ...opts, force: v })} /></label>}
        <div className="flex flex-col gap-1"><Label>Auditor notes</Label><Textarea rows={3} value={opts.notes} onChange={(e) => setOpts({ ...opts, notes: e.target.value })} /></div>
        {blocked && <div className="rounded border border-destructive/50 bg-destructive/5 p-2 text-xs">{prev.blocking.map((b: any) => <div key={b.code}>{b.message}</div>)}</div>}
        <Button className="w-full" disabled={blocked && !opts.force} onClick={() => setConfirm(true)}><Moon />Close {fmtDate(prev?.business_date)} & roll date</Button>
      </div></Section>
      <div className="lg:col-span-3"><h3 className="mb-2 text-sm font-semibold">Today so far</h3><Stats s={prev?.statistics} currency={currency} /></div>
    </div> : <div className="rounded-lg border p-6 text-sm text-muted-foreground">You can view closed days below; running the audit requires the night-audit permission.</div>}
    <Section title="Business day history"><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Business date</th><th className="p-2 text-left">Status</th><th className="p-2 text-left">Opened</th><th className="p-2 text-left">Closed</th><th className="p-2 text-right">Occupancy</th><th className="p-2 text-right">Revenue</th><th /></tr></thead><tbody className="divide-y">{list.map((d: any) => <tr key={d.id}><td className="p-2">{fmtDate(d.business_date)}</td><td className="p-2"><StatusBadge status={d.status} /></td><td className="p-2 text-xs">{fmtDateTime(d.opened_at)}</td><td className="p-2 text-xs">{d.closed_at ? `${fmtDateTime(d.closed_at)} · ${d.closed_by_name ?? ''}` : '—'}</td><td className="p-2 text-right tabular">{d.night_audit_report ? `${fmtNum(d.night_audit_report.occupancy_percent, 1)}%` : ''}</td><td className="p-2 text-right tabular">{d.night_audit_report ? fmtMoney(d.night_audit_report.total_revenue, currency) : ''}</td><td className="p-2 text-right whitespace-nowrap">{d.night_audit_report && <Button size="sm" variant="ghost" onClick={() => setReport(d.night_audit_report)}><FileText />Report</Button>}{d.status === 'CLOSED' && can('accounting.periods') && <Button size="sm" variant="ghost" onClick={() => setReopen(d)}><RotateCcw />Reopen</Button>}</td></tr>)}</tbody></table></Section>
    <ConfirmDialog open={confirm} onOpenChange={setConfirm} title={`Run night audit for ${fmtDate(prev?.business_date)}?`} description="This posts room charges to every in-house folio, marks no-shows, freezes the day's statistics and advances the business date. It is recorded in the audit log and cannot be undone except by a supervised reopen." confirmLabel="Run night audit" onConfirm={() => run.mutateAsync(undefined as any)} />
    <ConfirmDialog open={!!reopen} onOpenChange={(o) => !o && setReopen(null)} title={`Reopen ${reopen ? fmtDate(reopen.business_date) : ''}`} description="Only for corrections; requires a reason that is written to the audit trail." destructive confirmLabel="Reopen day" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => reopenM.mutateAsync(v)} />
    <Modal open={!!report} onOpenChange={(o) => !o && setReport(null)} title={report ? `Night audit report — ${fmtDate(report.business_date)}` : ''} size="xl">{report && <div className="space-y-4"><KV cols={4} items={[['Run by', report.run_by], ['Run at', fmtDateTime(report.run_at)], ['Forced', report.checks?.forced ? 'Yes' : 'No'], ['Notes', report.notes ?? '—']]} /><Stats s={report} currency={currency} />{(report.audit_log ?? []).length > 0 && <Section title="Audit log"><ul className="list-disc space-y-0.5 pl-5 text-xs">{report.audit_log.map((l: any, i: number) => <li key={i}>{typeof l === 'string' ? l : JSON.stringify(l)}</li>)}</ul></Section>}{(report.checks?.warnings ?? []).length > 0 && <div className="text-xs text-amber-600">Warnings: {report.checks.warnings.map((w: any) => w.message).join('; ')}</div>}</div>}</Modal>
  </div>;
}
