'use client';
import React, { useMemo, useState } from 'react';
import { Play, Download, FileSpreadsheet, FileText, BarChart3 } from 'lucide-react';
import { api, download } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Input, Label, NativeSelect } from '@/components/ui/input';
import { LookupSelect } from '@/components/shared/form';
import { fmtDate, fmtNum, titleCase, today, addDays } from '@/lib/utils';
import { PrintButton, TableDoc } from '@/lib/print';

const LOOKUPS: Record<string, { source: string; label: string; query?: Record<string, any> }> = { store_id: { source: '/stores', label: 'name' }, outlet_id: { source: '/outlets', label: 'name' }, product_id: { source: '/products', label: 'name', query: { pageSize: 500 } }, supplier_id: { source: '/suppliers', label: 'name' }, department_id: { source: '/departments', label: 'name' }, room_type_id: { source: '/room-types', label: 'name' }, customer_id: { source: '/customers', label: 'name' } };
const isMoneyCol = (c: string) => /amount|total|revenue|cost|value|price|balance|tax|net|gross|adr|revpar|variance|paid|debit|credit/i.test(c);
const cell = (c: string, v: any) => { if (v === null || v === undefined) return ''; if (typeof v === 'number') return isMoneyCol(c) ? fmtNum(v, 2) : /percent|pct|occupancy/i.test(c) ? `${fmtNum(v, 1)}%` : fmtNum(v, Number.isInteger(v) ? 0 : 2); if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v)) return fmtDate(v); if (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}T/.test(v)) return v.replace('T', ' ').slice(0, 16); if (typeof v === 'boolean') return v ? 'Yes' : 'No'; if (typeof v === 'object') return JSON.stringify(v); return String(v); };
export default function ReportsPage() {
  const { can } = useAuth(); const { data: defs } = useApi<any[]>('/reports'); const [key, setKey] = useState<string>(''); const [params, setParams] = useState<Record<string, any>>({ from: addDays(today(), -29), to: today(), date: today() }); const [result, setResult] = useState<any>(null);
  const groups = useMemo(() => (defs ?? []).reduce<Record<string, any[]>>((g, r) => { (g[r.group] ??= []).push(r); return g; }, {}), [defs]); const def = (defs ?? []).find((d) => d.key === key);
  const run = useAction(async () => api(`/reports/${key}`, { query: clean(params) }), { silent: true, onSuccess: (r: any) => setResult(r) });
  const clean = (p: Record<string, any>) => Object.fromEntries(Object.entries(p).filter(([k, v]) => v !== '' && v !== undefined && (def?.params ?? []).some((x: any) => x.name === k)));
  const exp = (format: 'csv' | 'xlsx' | 'pdf') => download(`/reports/${key}`, { ...clean(params), format }, `${key}.${format}`);
  const cols: string[] = result?.columns ?? []; const sums = useMemo(() => { const s: Record<string, number> = {}; for (const c of cols) if (isMoneyCol(c) && (result?.rows ?? []).every((r: any) => r[c] === null || typeof r[c] === 'number')) s[c] = (result?.rows ?? []).reduce((a: number, r: any) => a + Number(r[c] ?? 0), 0); return s; }, [result, cols]);
  return <div className="space-y-4">
    <PageHeader title="Reports" subtitle="Operational and financial reports built on the same tables the modules write to — no separate reporting copy. Filter, run, export." />
    <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
      <aside className="space-y-3 rounded-lg border bg-card p-2 lg:max-h-[75vh] lg:overflow-auto">{Object.entries(groups).map(([g, list]) => <div key={g}><div className="px-2 py-1 text-[11px] font-semibold uppercase text-muted-foreground">{g}</div>{list.map((r) => <button key={r.key} type="button" onClick={() => { setKey(r.key); setResult(null); }} className={`block w-full rounded px-2 py-1.5 text-left text-sm ${key === r.key ? 'bg-primary/10 font-medium text-primary' : 'hover:bg-accent'}`}>{r.name}</button>)}</div>)}{(defs ?? []).length === 0 && <div className="p-3 text-sm text-muted-foreground">No reports available for your role.</div>}</aside>
      <div className="space-y-3">{!def ? <div className="rounded-lg border border-dashed p-12 text-center text-muted-foreground"><BarChart3 className="mx-auto mb-2 h-8 w-8" />Pick a report on the left.</div> : <>
        <div className="rounded-lg border bg-card p-3"><h2 className="mb-2 font-semibold">{def.name}</h2><div className="flex flex-wrap items-end gap-3">{def.params.map((p: any) => <div key={p.name} className="flex min-w-[10rem] flex-col gap-1"><Label>{titleCase(p.name)}{p.required && ' *'}</Label>{p.type === 'date' ? <Input type="date" value={params[p.name] ?? ''} onChange={(e) => setParams({ ...params, [p.name]: e.target.value })} /> : p.type === 'uuid' && LOOKUPS[p.name] ? <LookupSelect source={LOOKUPS[p.name].source} sourceLabel={LOOKUPS[p.name].label} sourceQuery={LOOKUPS[p.name].query} value={params[p.name] ?? ''} onChange={(v) => setParams({ ...params, [p.name]: v })} placeholder="All" /> : p.type === 'select' && p.options ? <NativeSelect value={params[p.name] ?? ''} onChange={(e) => setParams({ ...params, [p.name]: e.target.value })}><option value="">All</option>{String(p.options).split(',').map((o: string) => <option key={o} value={o.trim()}>{titleCase(o.trim())}</option>)}</NativeSelect> : <Input value={params[p.name] ?? ''} onChange={(e) => setParams({ ...params, [p.name]: e.target.value })} placeholder={p.default ?? ''} />}</div>)}<Button loading={run.isPending} onClick={() => run.mutate(undefined as any)}><Play />Run</Button>{result && can('reports.export') && <div className="flex gap-1"><PrintButton doc="report" size="sm" title={def.name} render={(ctx) => <TableDoc title={def.name} subtitle={Object.entries(result.params ?? {}).map(([k, v]) => `${titleCase(k)}: ${cell(k, v)}`).join(' · ')} meta={Object.entries(result.meta ?? {}).map(([k, v]) => [titleCase(k), cell(k, v)] as [string, React.ReactNode])} columns={cols.map((c) => ({ label: titleCase(c), align: typeof result.rows[0]?.[c] === 'number' ? 'right' as const : 'left' as const }))} rows={result.rows.map((r: any) => cols.map((c) => cell(c, r[c])))} footer={Object.keys(sums).length > 0 && result.rows.length > 1 ? cols.map((c, i) => sums[c] !== undefined ? fmtNum(sums[c], 2) : i === 0 ? 'Total' : '') : undefined} ctx={ctx} />} /><Button variant="outline" size="sm" onClick={() => exp('csv')}><Download />CSV</Button><Button variant="outline" size="sm" onClick={() => exp('xlsx')}><FileSpreadsheet />Excel</Button><Button variant="outline" size="sm" onClick={() => exp('pdf')}><FileText />PDF</Button></div>}</div></div>
        {result && <div className="rounded-lg border bg-card"><div className="flex flex-wrap items-center justify-between gap-2 border-b px-3 py-2 text-xs text-muted-foreground"><span>{result.count} row(s) · {Object.entries(result.params ?? {}).map(([k, v]) => `${k}=${v}`).join(' · ')}</span>{result.meta && Object.keys(result.meta).length > 0 && <span className="flex flex-wrap gap-3">{Object.entries(result.meta).map(([k, v]) => <span key={k}><b>{titleCase(k)}:</b> {cell(k, v)}</span>)}</span>}</div><div className="max-h-[60vh] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-xs uppercase text-muted-foreground"><tr>{cols.map((c) => <th key={c} className={`whitespace-nowrap p-2 ${typeof result.rows[0]?.[c] === 'number' ? 'text-right' : 'text-left'}`}>{titleCase(c)}</th>)}</tr></thead><tbody className="divide-y">{result.rows.map((r: any, i: number) => <tr key={i} className="hover:bg-accent/40">{cols.map((c) => <td key={c} className={`whitespace-nowrap p-2 ${typeof r[c] === 'number' ? 'text-right tabular' : ''}`}>{cell(c, r[c])}</td>)}</tr>)}{result.rows.length === 0 && <tr><td colSpan={cols.length || 1} className="p-8 text-center text-muted-foreground">No data for these filters.</td></tr>}</tbody>{Object.keys(sums).length > 0 && result.rows.length > 1 && <tfoot className="border-t font-semibold"><tr>{cols.map((c, i) => <td key={c} className={`p-2 ${sums[c] !== undefined ? 'text-right tabular' : ''}`}>{i === 0 && sums[c] === undefined ? 'Total' : sums[c] !== undefined ? fmtNum(sums[c], 2) : ''}</td>)}</tr></tfoot>}</table></div></div>}
      </>}</div>
    </div>
  </div>;
}
