'use client';
import React, { Suspense, useEffect, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { Plus, Send, Check, X, Banknote, Ban, Pencil } from 'lucide-react';
import { post, put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, KV } from '@/components/shared/page';
import { DataTable } from '@/components/shared/data-table';
import { ResourcePage } from '@/components/shared/resource-page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { FormDialog, ConfirmDialog, Field } from '@/components/shared/form';
import { Attachments } from '@/components/shared/attachments';
import { AuditTrail } from '@/components/shared/audit-trail';
import { ApprovalTrail } from '@/components/shared/approval-trail';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtDate, fmtDateTime, fmtMoney, titleCase, today } from '@/lib/utils';

const SOURCES = ['PETTY_CASH', 'CASH', 'BANK', 'MOBILE_MONEY', 'CORPORATE_CARD', 'CREDIT'];
const STATUSES = ['DRAFT', 'PENDING', 'APPROVED', 'PAID', 'REJECTED', 'CANCELLED'];
const expenseFields: Field[] = [{ name: 'category_id', label: 'Category', type: 'lookup', source: '/expense-categories', sourceQuery: { active: 'true' }, sourceLabel: 'name', required: true }, { name: 'expense_date', label: 'Date', type: 'date', default: today() }, { name: 'description', label: 'Description', required: true, col: 2 }, { name: 'amount', label: 'Amount', type: 'money', required: true }, { name: 'tax_id', label: 'Tax', type: 'lookup', source: '/taxes', sourceLabel: 'name' }, { name: 'tax_inclusive', label: 'Amount includes tax', type: 'switch', default: true }, { name: 'payment_source', label: 'Paid from', type: 'select', options: SOURCES, default: 'PETTY_CASH' }, { name: 'petty_cash_fund_id', label: 'Petty cash fund (if petty cash)', type: 'lookup', source: '/petty-cash/funds', sourceLabel: 'name' }, { name: 'department_id', label: 'Department', type: 'lookup', source: '/departments', sourceLabel: 'name' }, { name: 'outlet_id', label: 'Outlet', type: 'lookup', source: '/outlets', sourceLabel: 'name' }, { name: 'supplier_id', label: 'Supplier (optional)', type: 'lookup', source: '/suppliers', sourceLabel: 'name' }, { name: 'payee', label: 'Payee (if no supplier)' }, { name: 'reference', label: 'Receipt / reference no.' }, { name: 'submit', label: 'Submit for approval immediately', type: 'switch', default: true }];
export function ExpenseDetail({ id, onClose, onEdit }: { id: string | null; onClose: () => void; onEdit: (e: any) => void }) {
  const { can, currency, user } = useAuth(); const { data: e, refetch } = useApi<any>(id ? `/expenses/${id}` : null); const [dlg, setDlg] = useState<'reject' | 'pay' | 'cancel' | null>(null);
  const useAct = (path: string, msg: string) => useAction((v?: any) => post(`/expenses/${id}/${path}`, v ?? {}), { success: msg, invalidate: ['/expenses', '/petty-cash', '/payments'], onSuccess: () => { setDlg(null); refetch(); } });
  const submit = useAct('submit', 'Submitted for approval'), approve = useAct('approve', 'Expense approved'), reject = useAct('reject', 'Expense rejected'), pay = useAct('pay', 'Expense paid'), cancel = useAct('cancel', 'Expense cancelled');
  if (!id) return null;
  const mine = e && user && e.requested_by === user.id;
  return <Modal open={!!id} onOpenChange={(o) => !o && onClose()} title={e ? <span className="flex items-center gap-2">{e.number} <StatusBadge status={e.status} /><Badge tone="muted">{titleCase(e.payment_source)}</Badge></span> : 'Expense'} size="lg">{e && <div className="space-y-4">
    <KV cols={3} items={[['Description', e.description], ['Category', `${e.category_name ?? ''} (${e.account_code ?? ''} ${e.account_name ?? ''})`], ['Date', fmtDate(e.expense_date)], ['Amount', fmtMoney(e.amount, currency)], ['Tax', fmtMoney(e.tax_amount, currency)], ['Total', <b key="t">{fmtMoney(e.total, currency)}</b>], ['Payee', e.supplier_name ?? e.payee ?? '—'], ['Department / outlet', [e.department_name, e.outlet_name].filter(Boolean).join(' · ') || '—'], ['Fund', e.fund_name ?? '—'], ['Requested by', `${e.requested_by_name ?? ''} · ${fmtDateTime(e.created_at)}`], ['Approved by', e.approved_by_name ? `${e.approved_by_name} · ${fmtDateTime(e.approved_at)}` : '—'], ['Paid', e.paid_at ? `${fmtDateTime(e.paid_at)}${e.payment_number ? ` · ${e.payment_number}` : ''}${e.method_name ? ` · ${e.method_name}` : ''}` : '—'], ['Reference', e.reference ?? '—'], ['Journal', e.journal_entry_id ? <Link key="j" href={`/finance/journals?id=${e.journal_entry_id}`} className="underline">View</Link> : '—'], ['Rejection reason', e.rejection_reason ?? '—']]} />
    {e.status === 'REJECTED' && e.rejection_reason && <div className="rounded border border-destructive/40 bg-destructive/5 p-2 text-sm">Rejected: {e.rejection_reason}</div>}
    <div className="flex flex-wrap gap-2">
      {['DRAFT', 'REJECTED'].includes(e.status) && can('expenses.create') && <><Button variant="outline" onClick={() => onEdit(e)}><Pencil />Edit</Button><Button loading={submit.isPending} onClick={() => submit.mutate(undefined)}><Send />Submit for approval</Button></>}
      {e.status === 'PENDING' && can('expenses.approve') && <><Button loading={approve.isPending} disabled={mine} title={mine ? 'You cannot approve your own expense' : ''} onClick={() => approve.mutate(undefined)}><Check />Approve</Button><Button variant="outline" onClick={() => setDlg('reject')}><X />Reject</Button></>}
      {e.status === 'APPROVED' && e.payment_source !== 'CREDIT' && can('expenses.pay', 'petty_cash.manage') && <Button onClick={() => setDlg('pay')}><Banknote />Pay {e.payment_source === 'PETTY_CASH' ? 'from petty cash' : 'now'}</Button>}
      {e.status === 'APPROVED' && e.payment_source === 'CREDIT' && <span className="text-sm text-muted-foreground">On credit — settled via supplier payments.</span>}
      {!['PAID', 'CANCELLED'].includes(e.status) && can('expenses.create', 'expenses.approve') && <Button variant="ghost" className="text-destructive" onClick={() => setDlg('cancel')}><Ban />Cancel</Button>}
    </div>
    <Tabs defaultValue="approval"><TabsList><TabsTrigger value="approval">Approval</TabsTrigger><TabsTrigger value="files">Receipts ({e.attachments?.length ?? e.attachment_count ?? 0})</TabsTrigger><TabsTrigger value="audit">Audit</TabsTrigger></TabsList><TabsContent value="approval"><ApprovalTrail approval={e.approval} title="Approval workflow" /></TabsContent><TabsContent value="files"><Attachments entity="expense" entityId={id} /></TabsContent><TabsContent value="audit"><AuditTrail entity="expense" entityId={id} /></TabsContent></Tabs>
    <ConfirmDialog open={dlg === 'reject'} onOpenChange={(o) => !o && setDlg(null)} title="Reject expense" destructive confirmLabel="Reject" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => reject.mutateAsync(v)} />
    <ConfirmDialog open={dlg === 'cancel'} onOpenChange={(o) => !o && setDlg(null)} title="Cancel expense" destructive confirmLabel="Cancel expense" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => cancel.mutateAsync(v)} />
    <ConfirmDialog open={dlg === 'pay'} onOpenChange={(o) => !o && setDlg(null)} title={`Pay ${fmtMoney(e.total, currency)}`} description={e.payment_source === 'PETTY_CASH' ? `Disbursed from ${e.fund_name ?? 'your petty cash fund'}; the fund balance and expense ledger post automatically.` : 'Records the disbursement and posts the expense journal.'} confirmLabel="Record payment" fields={e.payment_source === 'PETTY_CASH' ? [{ name: 'reference', label: 'Voucher / receipt no.' }] : [{ name: 'payment_method_id', label: 'Payment method', type: 'lookup', source: '/payment-methods', sourceLabel: 'name', required: true }, { name: 'reference', label: 'Reference' }]} onConfirm={(v) => pay.mutateAsync({ ...v, payment_method_id: v.payment_method_id || undefined })} />
  </div>}</Modal>;
}
function ExpensesInner() {
  const { can, currency } = useAuth(); const sp = useSearchParams(); const router = useRouter(); const [sel, setSel] = useState<string | null>(null); const [dialog, setDialog] = useState<{ open: boolean; row?: any }>({ open: false });
  useEffect(() => { if (sp.get('id')) setSel(sp.get('id')); if (sp.get('new')) setDialog({ open: true }); }, [sp]);
  const { data: sum } = useApi<any>('/expenses/summary', { from: today().slice(0, 8) + '01', to: today() });
  const save = useAction((v: any) => (dialog.row ? put(`/expenses/${dialog.row.id}`, v) : post('/expenses', v)), { success: dialog.row ? 'Expense updated' : 'Expense recorded', invalidate: ['/expenses'], onSuccess: (r: any) => { setDialog({ open: false }); setSel(r?.id ?? dialog.row?.id ?? null); } });
  return <div className="space-y-4">
    <PageHeader title="Expenses" subtitle="Request → approve → pay. Petty cash, bank and card disbursements post straight to the ledger with the receipt attached." actions={can('expenses.create') && <Button onClick={() => setDialog({ open: true })}><Plus />New expense</Button>} />
    <div className="grid gap-3 grid-cols-2 md:grid-cols-4">{(sum?.by_status ?? []).slice(0, 4).map((s: any) => <div key={s.status} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{titleCase(s.status)} (MTD)</div><div className="text-lg font-semibold tabular">{fmtMoney(s.total, currency)}</div><div className="text-xs text-muted-foreground">{s.count} expense(s)</div></div>)}</div>
    <Tabs defaultValue="list"><TabsList><TabsTrigger value="list">Expenses</TabsTrigger><TabsTrigger value="summary">This month by category</TabsTrigger>{can('settings.edit', 'accounting.accounts') && <TabsTrigger value="categories">Categories</TabsTrigger>}</TabsList>
      <TabsContent value="list"><DataTable path="/expenses" defaultSort="created_at" onRowClick={(r) => setSel(r.id)} exportName="expenses" filters={[{ key: 'status', label: 'Status', type: 'select', options: STATUSES }, { key: 'category_id', label: 'Category', type: 'select', source: '/expense-categories', sourceLabel: 'name' }, { key: 'payment_source', label: 'Source', type: 'select', options: SOURCES }, { key: 'department_id', label: 'Department', type: 'select', source: '/departments', sourceLabel: 'name' }, { key: 'date', label: 'Date', type: 'daterange' }]}
        columns={[{ key: 'number', label: 'No.' }, { key: 'expense_date', label: 'Date', type: 'date' }, { key: 'description', label: 'Description' }, { key: 'category_name', label: 'Category' }, { key: 'department_name', label: 'Department', hideOnMobile: true }, { key: 'payment_source', label: 'Source', render: (r) => titleCase(r.payment_source) }, { key: 'requested_by_name', label: 'Requested by', hideOnMobile: true }, { key: 'total', label: 'Total', type: 'money' }, { key: 'attachment_count', label: 'Receipt', render: (r) => (Number(r.attachment_count) > 0 ? <Badge tone="success">{r.attachment_count}</Badge> : <span className="text-muted-foreground">—</span>) }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }]} /></TabsContent>
      <TabsContent value="summary"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border bg-card p-3"><h3 className="mb-2 text-sm font-semibold">By category</h3><ul className="divide-y text-sm">{(sum?.by_category ?? []).map((c: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{c.category}</span><span className="tabular">{fmtMoney(c.total, currency)} <span className="text-xs text-muted-foreground">({c.count})</span></span></li>)}</ul></div><div className="rounded-lg border bg-card p-3"><h3 className="mb-2 text-sm font-semibold">By department</h3><ul className="divide-y text-sm">{(sum?.by_department ?? []).map((c: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{c.department ?? 'Unassigned'}</span><span className="tabular">{fmtMoney(c.total, currency)}</span></li>)}</ul></div></div></TabsContent>
      <TabsContent value="categories"><ResourcePage embedded path="/expense-categories" title="Expense category" entity="expense_category" permissions={{ view: 'expenses.view', create: 'settings.edit', edit: 'settings.edit' }} defaultSort="code" fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'account_id', label: 'Expense GL account', type: 'lookup', source: '/accounts', sourceQuery: { type: 'EXPENSE', header: 'false', pageSize: 500 }, sourceLabel: (a: any) => `${a.code} · ${a.name}`, required: true }, { name: 'requires_receipt', label: 'Requires receipt', type: 'switch', default: true }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'account_code', label: 'GL', render: (r) => `${r.account_code ?? ''} ${r.account_name ?? ''}` }, { key: 'requires_receipt', label: 'Receipt', type: 'bool' }, { key: 'is_active', label: 'Active', type: 'bool' }]} /></TabsContent>
    </Tabs>
    <FormDialog open={dialog.open} onOpenChange={(o) => { setDialog((d) => ({ ...d, open: o })); if (!o && sp.get('new')) router.replace('/finance/expenses'); }} title={dialog.row ? `Edit ${dialog.row.number}` : 'New expense'} size="lg" fields={dialog.row ? expenseFields.filter((f) => f.name !== 'submit') : expenseFields} initial={dialog.row ?? undefined} onSubmit={(v) => save.mutateAsync({ ...v, petty_cash_fund_id: v.petty_cash_fund_id || null, tax_id: v.tax_id || null, supplier_id: v.supplier_id || null, department_id: v.department_id || null, outlet_id: v.outlet_id || null })} />
    <ExpenseDetail id={sel} onClose={() => { setSel(null); if (sp.get('id')) router.replace('/finance/expenses'); }} onEdit={(e) => { setSel(null); setDialog({ open: true, row: e }); }} />
  </div>;
}
export function ExpensesPage() { return <Suspense fallback={null}><ExpensesInner /></Suspense>; }
