'use client';
import React, { useState } from 'react';
import { ListPlus, FlaskConical, ChefHat } from 'lucide-react';
import { put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { ResourcePage } from '@/components/shared/resource-page';
import { DropdownMenuItem } from '@/components/ui/dropdown';
import { Modal } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input, Label } from '@/components/ui/input';
import { Switch } from '@/components/ui/misc';
import { LookupSelect } from '@/components/shared/form';
import { fmtMoney } from '@/lib/utils';

/** Menus → categories → items. Items link to products (direct stock) or recipes (multi-ingredient) so every sale consumes inventory and books COGS. */
export default function MenusPage() {
  const { can, currency } = useAuth(); const [recipeFor, setRecipeFor] = useState<any>(null); const [modsFor, setModsFor] = useState<any>(null);
  return <div className="space-y-4"><Tabs defaultValue="items"><TabsList><TabsTrigger value="menus">Menus</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="items">Menu items</TabsTrigger></TabsList>
    <TabsContent value="menus"><ResourcePage title="Menus" subtitle="A menu is assigned to one or more outlets and can be time-restricted (e.g. breakfast)." path="/menus" permissions={{ create: 'menus.manage', edit: 'menus.manage', delete: 'menus.manage' }} columns={[{ key: 'name', label: 'Menu' }, { key: 'category_count', label: 'Categories', type: 'number', decimals: 0 }, { key: 'item_count', label: 'Items', type: 'number', decimals: 0 }, { key: 'available_from', label: 'From' }, { key: 'available_to', label: 'To' }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'name', label: 'Name', required: true }, { name: 'outlet_ids', label: 'Outlets', type: 'multiselect', source: '/outlets', required: true }, { name: 'available_from', label: 'Available from', type: 'time' }, { name: 'available_to', label: 'Available to', type: 'time' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
    <TabsContent value="categories"><ResourcePage title="Menu categories" path="/menu-categories" permissions={{ create: 'menus.manage', edit: 'menus.manage', delete: 'menus.manage' }} filters={[{ key: 'menu_id', label: 'Menu', type: 'select', source: '/menus' }]} columns={[{ key: 'menu_name', label: 'Menu' }, { key: 'name', label: 'Category' }, { key: 'type', label: 'Type' }, { key: 'kitchen_name', label: 'Routes to' }, { key: 'sort_order', label: 'Order', type: 'number', decimals: 0 }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'menu_id', label: 'Menu', type: 'lookup', source: '/menus', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select', options: ['FOOD', 'BEVERAGE', 'ALCOHOL', 'TOBACCO', 'SERVICE', 'TICKET', 'OTHER'], default: 'FOOD' }, { name: 'kitchen_id', label: 'Kitchen / bar station', type: 'lookup', source: '/kitchens' }, { name: 'sort_order', label: 'Sort order', type: 'number', default: 0 }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
    <TabsContent value="items"><ResourcePage title="Menu items" subtitle="Price, tax, kitchen routing and stock linkage. Use “Recipe” for cocktails/dishes and “Modifiers” for options." path="/menu-items" permissions={{ create: 'menus.manage', edit: 'menus.manage', delete: 'menus.manage' }} filters={[{ key: 'category_id', label: 'Category', type: 'select', source: '/menu-categories' }, { key: 'available', label: 'Available', type: 'select', options: ['true', 'false'] }]}
      columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Item' }, { key: 'category_name', label: 'Category' }, { key: 'price', label: 'Price', type: 'money' }, { key: 'tax_name', label: 'Tax' }, { key: 'kitchen_name', label: 'Kitchen' }, { key: 'product_name', label: 'Stock link', render: (r) => r.product_name ? `${r.product_name} × ${r.product_qty}` : r.recipe ? `Recipe v${r.recipe.version}` : <span className="text-muted-foreground">none</span> }, { key: 'is_available', label: 'Available', type: 'bool' }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'category_id', label: 'Category', type: 'lookup', source: '/menu-categories', sourceLabel: (c: any) => `${c.menu_name ?? ''} › ${c.name}`, required: true }, { name: 'code', label: 'Code / PLU' }, { name: 'name', label: 'Name', required: true }, { name: 'price', label: 'Price (tax-inclusive)', type: 'money', required: true }, { name: 'tax_id', label: 'Tax', type: 'lookup', source: '/taxes' }, { name: 'kitchen_id', label: 'Kitchen override', type: 'lookup', source: '/kitchens' }, { name: 'product_id', label: 'Direct stock product (e.g. bottled drink)', type: 'lookup', source: '/products', sourceLabel: (p: any) => `${p.sku ?? ''} ${p.name}` }, { name: 'product_qty', label: 'Qty consumed per sale', type: 'number', default: 1 }, { name: 'cost_estimate', label: 'Cost estimate', type: 'money' }, { name: 'preparation_minutes', label: 'Prep minutes', type: 'number' }, { name: 'barcode', label: 'Barcode' }, { name: 'sort_order', label: 'Sort order', type: 'number', default: 0 }, { name: 'is_service_charge_applicable', label: 'Service charge applies', type: 'switch', default: true }, { name: 'is_available', label: 'Available (86 toggle)', type: 'switch', default: true }, { name: 'is_active', label: 'Active', type: 'switch', default: true }, { name: 'description', label: 'Description', type: 'textarea', col: 2 }]}
      extraActions={(row) => can('menus.manage') && <><DropdownMenuItem onClick={() => setRecipeFor(row)}><FlaskConical />Recipe…</DropdownMenuItem><DropdownMenuItem onClick={() => setModsFor(row)}><ListPlus />Modifiers…</DropdownMenuItem></>} /></TabsContent>
  </Tabs>
    {recipeFor && <RecipeDialog item={recipeFor} onClose={() => setRecipeFor(null)} />}
    {modsFor && <ModifiersDialog item={modsFor} onClose={() => setModsFor(null)} />}
  </div>;
}
function RecipeDialog({ item, onClose }: { item: any; onClose: () => void }) {
  const { currency } = useAuth(); const { data } = useApi<any>(`/menu-items/${item.id}`);
  const existing = data?.recipe; const [lines, setLines] = useState<any[] | null>(null); const [yieldQty, setYieldQty] = useState<any>(1);
  const rows = lines ?? (existing?.items ?? []).map((i: any) => ({ product_id: i.product_id, quantity: i.quantity, wastage_percent: i.wastage_percent ?? 0 })) ?? [];
  const save = useAction(() => put(`/menu-items/${item.id}/recipe`, { items: rows.filter((r: any) => r.product_id).map((r: any) => ({ product_id: r.product_id, quantity: Number(r.quantity), wastage_percent: Number(r.wastage_percent || 0) })), yield_qty: Number(yieldQty) || 1 }), { success: 'Recipe saved (new version)', invalidate: ['/recipes', '/menu-items'], onSuccess: onClose });
  const upd = (i: number, p: any) => setLines(rows.map((r: any, j: number) => (j === i ? { ...r, ...p } : r)));
  return <Modal open onOpenChange={(o) => !o && onClose()} title={`Recipe · ${item.name}`} description="Ingredients deducted from the kitchen/bar store on every sale (per portion). Saving creates a new recipe version; history is kept." size="lg"><div className="space-y-3">
    {existing && <div className="text-xs text-muted-foreground">Current version {existing.version} · ingredient cost {fmtMoney((existing.items ?? []).reduce((a: number, i: any) => a + Number(i.cost ?? 0), 0), currency)} per batch</div>}
    <table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left">Ingredient</th><th className="w-28">Qty (stock unit)</th><th className="w-24">Wastage %</th><th className="w-8" /></tr></thead><tbody>{rows.map((r: any, i: number) => <tr key={i}><td className="p-1"><LookupSelect source="/products" sourceQuery={{ pageSize: 500 }} sourceLabel={(p: any) => `${p.sku ?? ''} ${p.name} (${p.unit_code ?? p.unit ?? ''})`} value={r.product_id} onChange={(v) => upd(i, { product_id: v })} /></td><td className="p-1"><Input type="number" step="0.001" value={r.quantity} onChange={(e) => upd(i, { quantity: e.target.value })} /></td><td className="p-1"><Input type="number" step="0.1" value={r.wastage_percent} onChange={(e) => upd(i, { wastage_percent: e.target.value })} /></td><td><Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => setLines(rows.filter((_: any, j: number) => j !== i))}>×</Button></td></tr>)}</tbody></table>
    <div className="flex items-center justify-between"><Button size="sm" variant="outline" onClick={() => setLines([...rows, { product_id: '', quantity: 1, wastage_percent: 0 }])}>Add ingredient</Button><div className="flex items-center gap-2 text-sm"><Label>Yield (portions)</Label><Input className="w-20" type="number" min={1} value={yieldQty} onChange={(e) => setYieldQty(e.target.value)} /><Button loading={save.isPending} onClick={() => save.mutate(undefined as any)}><ChefHat />Save recipe</Button></div></div>
  </div></Modal>;
}
function ModifiersDialog({ item, onClose }: { item: any; onClose: () => void }) {
  const { data } = useApi<any>(`/menu-items/${item.id}`); const [rows, setRows] = useState<any[] | null>(null);
  const list = rows ?? (data?.modifiers ?? []);
  const save = useAction(() => put(`/menu-items/${item.id}/modifiers`, { modifiers: list.filter((m: any) => m.name).map((m: any) => ({ group_name: m.group_name || 'Options', name: m.name, price_delta: Number(m.price_delta || 0), product_id: m.product_id || null, product_qty: Number(m.product_qty || 0), is_required: !!m.is_required, max_select: Number(m.max_select || 1) })) }), { success: 'Modifiers saved', invalidate: ['/menu-items', '/menus'], onSuccess: onClose });
  const upd = (i: number, p: any) => setRows(list.map((r: any, j: number) => (j === i ? { ...r, ...p } : r)));
  return <Modal open onOpenChange={(o) => !o && onClose()} title={`Modifiers · ${item.name}`} description="Options shown to the waiter (e.g. Doneness, Extras). Price deltas and optional extra stock consumption." size="lg"><div className="space-y-3">
    <table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left">Group</th><th className="text-left">Option</th><th className="w-24">+Price</th><th className="text-left">Extra stock</th><th className="w-16">Qty</th><th className="w-14">Max</th><th className="w-16">Req.</th><th className="w-8" /></tr></thead><tbody>{list.map((m: any, i: number) => <tr key={i}><td className="p-1"><Input value={m.group_name ?? ''} onChange={(e) => upd(i, { group_name: e.target.value })} placeholder="Options" /></td><td className="p-1"><Input value={m.name ?? ''} onChange={(e) => upd(i, { name: e.target.value })} /></td><td className="p-1"><Input type="number" step="0.01" value={m.price_delta ?? 0} onChange={(e) => upd(i, { price_delta: e.target.value })} /></td><td className="p-1"><LookupSelect source="/products" sourceQuery={{ pageSize: 500 }} value={m.product_id ?? ''} onChange={(v) => upd(i, { product_id: v })} /></td><td className="p-1"><Input type="number" step="0.001" value={m.product_qty ?? 0} onChange={(e) => upd(i, { product_qty: e.target.value })} /></td><td className="p-1"><Input type="number" min={1} value={m.max_select ?? 1} onChange={(e) => upd(i, { max_select: e.target.value })} /></td><td className="p-1 text-center"><Switch checked={!!m.is_required} onCheckedChange={(v) => upd(i, { is_required: v })} /></td><td><Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => setRows(list.filter((_: any, j: number) => j !== i))}>×</Button></td></tr>)}</tbody></table>
    <div className="flex justify-between"><Button size="sm" variant="outline" onClick={() => setRows([...list, { group_name: 'Options', name: '', price_delta: 0, max_select: 1 }])}>Add option</Button><Button loading={save.isPending} onClick={() => save.mutate(undefined as any)}>Save modifiers</Button></div>
  </div></Modal>;
}
