'use client';
import React, { useState } from 'react';
import { ResourcePage } from '@/components/shared/resource-page';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { PageHeader, KV, Section } from '@/components/shared/page';
import { Modal } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { DropdownMenuItem } from '@/components/ui/dropdown';
import { Boxes } from 'lucide-react';
import { get } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { fmtMoney, fmtNum, titleCase } from '@/lib/utils';

const CATEGORY_TYPES = ['FOOD', 'BEVERAGE', 'HOUSEKEEPING', 'GUEST_SUPPLIES', 'MAINTENANCE', 'OFFICE', 'LINEN', 'SPA', 'OTHER'];
export default function ProductsPage() {
  const { currency } = useAuth(); const [stock, setStock] = useState<any>(null);
  return <div className="space-y-4">
    <PageHeader title="Products" subtitle="Inventory master data: products, categories (mapped to GL inventory/COGS accounts) and units of measure." />
    <Tabs defaultValue="products"><TabsList><TabsTrigger value="products">Products</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="units">Units</TabsTrigger></TabsList>
      <TabsContent value="products"><ResourcePage embedded title="Products" path="/products" entity="product" searchPlaceholder="Search SKU, name, barcode…" permissions={{ create: 'products.manage', edit: 'products.manage' }} defaultSort="name" dialogSize="lg"
        filters={[{ key: 'category_id', label: 'Category', type: 'select', source: '/product-categories' }, { key: 'category_type', label: 'Type', type: 'select', options: CATEGORY_TYPES }, { key: 'sellable', label: 'Sellable', type: 'select', options: [{ value: 'true', label: 'Sellable' }, { value: 'false', label: 'Not sellable' }] }, { key: 'active', label: 'Active', type: 'select', options: [{ value: 'true', label: 'Active' }, { value: 'false', label: 'Inactive' }] }]}
        columns={[{ key: 'sku', label: 'SKU' }, { key: 'name', label: 'Product', render: (r) => <div><div className="font-medium">{r.name}</div>{r.barcode && <div className="text-xs text-muted-foreground font-mono">{r.barcode}</div>}</div> }, { key: 'category_name', label: 'Category', render: (r) => <span>{r.category_name} <Badge tone="muted">{titleCase(r.category_type)}</Badge></span> }, { key: 'unit', label: 'Unit' }, { key: 'cost_price', label: 'Cost', type: 'money' }, { key: 'selling_price', label: 'Sell', type: 'money' }, { key: 'reorder_level', label: 'Reorder', type: 'number', decimals: 2 }, { key: 'total_on_hand', label: 'On hand', render: (r) => <span className="tabular">{fmtNum(r.total_on_hand, 2)}</span> }, { key: 'total_value', label: 'Value', type: 'money' }, { key: 'supplier_name', label: 'Supplier' }, { key: 'is_active', label: 'Active', type: 'bool' }]}
        fields={[{ name: 'sku', label: 'SKU', required: true }, { name: 'barcode', label: 'Barcode' }, { name: 'name', label: 'Name', required: true, col: 2 }, { name: 'category_id', label: 'Category', type: 'lookup', source: '/product-categories', required: true }, { name: 'unit_id', label: 'Stock unit', type: 'lookup', source: '/units', required: true }, { name: 'purchase_unit_id', label: 'Purchase unit', type: 'lookup', source: '/units' }, { name: 'pack_size', label: 'Pack size (stock units per purchase unit)', type: 'number', default: 1 }, { name: 'cost_price', label: 'Standard cost', type: 'money' }, { name: 'selling_price', label: 'Selling price', type: 'money' }, { name: 'tax_id', label: 'Tax', type: 'lookup', source: '/taxes' }, { name: 'preferred_supplier_id', label: 'Preferred supplier', type: 'lookup', source: '/suppliers' }, { name: 'reorder_level', label: 'Reorder level', type: 'number' }, { name: 'reorder_qty', label: 'Reorder quantity', type: 'number' }, { name: 'min_stock', label: 'Min stock', type: 'number' }, { name: 'max_stock', label: 'Max stock', type: 'number' }, { name: 'is_stock_item', label: 'Stock item (tracked)', type: 'switch', default: true }, { name: 'is_sellable', label: 'Sellable', type: 'switch' }, { name: 'track_batches', label: 'Track batches', type: 'switch' }, { name: 'track_expiry', label: 'Track expiry', type: 'switch' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }, { name: 'description', label: 'Description', type: 'textarea', col: 2 }]}
        extraActions={(row) => <DropdownMenuItem onClick={async () => setStock({ product: row, rows: await get(`/products/${row.id}/stock`) })}><Boxes />Stock by store</DropdownMenuItem>} /></TabsContent>
      <TabsContent value="categories"><ResourcePage embedded title="Product categories" subtitle="Each category maps to an inventory (asset) account and a COGS/expense account so stock movements post correctly." path="/product-categories" permissions={{ create: 'products.manage', edit: 'products.manage', delete: 'products.manage' }} defaultSort="name"
        columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Category' }, { key: 'type', label: 'Type', render: (r) => titleCase(r.type) }, { key: 'parent_name', label: 'Parent' }, { key: 'inventory_account_code', label: 'Inventory a/c' }, { key: 'cogs_account_code', label: 'COGS a/c' }, { key: 'product_count', label: 'Products', type: 'number', decimals: 0 }, { key: 'is_active', label: 'Active', type: 'bool' }]}
        fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select', options: CATEGORY_TYPES, default: 'OTHER' }, { name: 'parent_id', label: 'Parent category', type: 'lookup', source: '/product-categories' }, { name: 'inventory_account_id', label: 'Inventory account', type: 'lookup', source: '/accounts', sourceQuery: { type: 'ASSET' }, sourceLabel: (a: any) => `${a.code} ${a.name}` }, { name: 'cogs_account_id', label: 'COGS / expense account', type: 'lookup', source: '/accounts', sourceQuery: { type: 'EXPENSE' }, sourceLabel: (a: any) => `${a.code} ${a.name}` }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
      <TabsContent value="units"><ResourcePage embedded title="Units of measure" path="/units" permissions={{ create: 'products.manage', edit: 'products.manage', delete: 'products.manage' }} defaultSort="name"
        columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Unit' }, { key: 'factor', label: 'Factor to base', type: 'number', decimals: 4 }]}
        fields={[{ name: 'code', label: 'Code', required: true, placeholder: 'kg, ltr, pc, crate' }, { name: 'name', label: 'Name', required: true }, { name: 'base_unit_id', label: 'Base unit (for conversions)', type: 'lookup', source: '/units' }, { name: 'factor', label: 'Factor (1 unit = N base units)', type: 'number', default: 1 }]} /></TabsContent>
    </Tabs>
    <Modal open={!!stock} onOpenChange={(o) => !o && setStock(null)} title={stock ? `${stock.product.name} · stock by store` : ''} size="md">{stock && <Section><ul className="divide-y text-sm">{(Array.isArray(stock.rows) ? stock.rows : stock.rows?.data ?? []).map((s: any) => <li key={s.store_id} className="flex justify-between py-1.5"><span>{s.store_name} <span className="text-xs text-muted-foreground">{s.store_code}</span></span><span className="tabular">{fmtNum(s.quantity, 3)} {stock.product.unit} · {fmtMoney(s.quantity * s.avg_cost, currency)}</span></li>)}{(Array.isArray(stock.rows) ? stock.rows : stock.rows?.data ?? []).length === 0 && <li className="py-3 text-muted-foreground">No stock in any store.</li>}</ul></Section>}</Modal>
  </div>;
}
