'use client';
import React, { useEffect, useState } from 'react';
import { Plus, KeyRound, Power, LogOut, Save } from 'lucide-react';
import { post, put, del } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { DataTable } from '@/components/shared/data-table';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Input, Label, NativeSelect } from '@/components/ui/input';
import { Switch, Checkbox } from '@/components/ui/misc';
import { LookupSelect, ConfirmDialog } from '@/components/shared/form';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtDateTime, titleCase } from '@/lib/utils';

const LIMIT_CODES = ['discount_percent', 'refund_amount', 'cash_variance_amount', 'purchase_approval_amount', 'expense_approval_amount', 'credit_limit_override', 'void_amount'];
const blank = { username: '', full_name: '', email: '', phone: '', password: '', department_id: '', default_property_id: '', employee_id: '', is_active: true, is_superuser: false, must_change_password: true, role_ids: [] as string[], property_ids: [] as string[], permission_overrides: [] as { code: string; effect: 'ALLOW' | 'DENY' }[], limits: [] as { limit_code: string; limit_value: number }[] };
function UserEditor({ id, onClose, onSaved }: { id: string | 'new' | null; onClose: () => void; onSaved: (id: string) => void }) {
  const { can, user: me } = useAuth(); const { data: u, refetch } = useApi<any>(id && id !== 'new' ? `/users/${id}` : null); const { data: roles } = useApi<any>('/roles'); const { data: props } = useApi<any>('/properties', { pageSize: 100 }); const { data: perms } = useApi<any>('/permissions'); const { data: sessions, refetch: refetchSessions } = useApi<any>(id && id !== 'new' && can('users.sessions') ? `/users/${id}/sessions` : null);
  const [f, setF] = useState<any>(blank); const [pw, setPw] = useState(false); const [permFilter, setPermFilter] = useState('');
  useEffect(() => { if (id === 'new') setF({ ...blank }); else if (u) setF({ ...blank, ...u, password: '', role_ids: (u.roles ?? []).map((r: any) => r.id), property_ids: u.property_ids ?? [], permission_overrides: u.permission_overrides ?? [], limits: u.limits ?? [], department_id: u.department_id ?? '', default_property_id: u.default_property_id ?? '', employee_id: u.employee_id ?? '' }); }, [u, id]);
  const body = () => ({ username: f.username, full_name: f.full_name, email: f.email || null, phone: f.phone || null, password: f.password || undefined, department_id: f.department_id || null, default_property_id: f.default_property_id || null, employee_id: f.employee_id || null, is_active: f.is_active, is_superuser: f.is_superuser, must_change_password: f.must_change_password, role_ids: f.role_ids, property_ids: f.property_ids, permission_overrides: f.permission_overrides, limits: f.limits.filter((l: any) => l.limit_code) });
  const save = useAction(() => (id === 'new' ? post('/users', body()) : put(`/users/${id}`, body())), { success: 'User saved', invalidate: ['/users'], onSuccess: (r: any) => { onSaved(r?.id ?? (id as string)); refetch(); } });
  const toggle = useAction(() => post(`/users/${id}/toggle-active`, {}), { success: 'Status updated', invalidate: ['/users'], onSuccess: () => refetch() });
  const reset = useAction((v: any) => post(`/users/${id}/reset-password`, { newPassword: v.newPassword }), { success: 'Password reset', onSuccess: () => setPw(false) });
  const revoke = useAction(() => del(`/users/${id}/sessions`), { success: 'All sessions revoked', onSuccess: () => refetchSessions() });
  if (!id) return null; const roleList: any[] = roles?.data ?? []; const propList: any[] = props?.data ?? []; const modules: Record<string, { code: string; description: string }[]> = perms?.modules ?? {};
  const ovr = (code: string) => f.permission_overrides.find((o: any) => o.code === code)?.effect as 'ALLOW' | 'DENY' | undefined;
  const setOvr = (code: string, effect?: 'ALLOW' | 'DENY') => setF({ ...f, permission_overrides: [...f.permission_overrides.filter((o: any) => o.code !== code), ...(effect ? [{ code, effect }] : [])] });
  const isNew = id === 'new'; const editable = isNew ? can('users.create') : can('users.edit');
  return <Modal open={!!id} onOpenChange={(o) => !o && onClose()} title={isNew ? 'New user' : <span className="flex items-center gap-2">{f.full_name || u?.full_name}<StatusBadge status={f.is_active ? 'ACTIVE' : 'DISABLED'} />{f.is_superuser && <Badge tone="warning">superuser</Badge>}</span>} size="xl"><div className="space-y-4">
    <Tabs defaultValue="account"><TabsList><TabsTrigger value="account">Account</TabsTrigger><TabsTrigger value="access">Roles & properties</TabsTrigger><TabsTrigger value="overrides">Permission overrides</TabsTrigger><TabsTrigger value="limits">Authority limits</TabsTrigger>{!isNew && <TabsTrigger value="security">Security</TabsTrigger>}</TabsList>
      <TabsContent value="account"><div className="grid gap-3 md:grid-cols-3">
        <div className="flex flex-col gap-1"><Label>Username *</Label><Input value={f.username} onChange={(e) => setF({ ...f, username: e.target.value })} disabled={!editable} /></div><div className="flex flex-col gap-1"><Label>Full name *</Label><Input value={f.full_name} onChange={(e) => setF({ ...f, full_name: e.target.value })} disabled={!editable} /></div><div className="flex flex-col gap-1"><Label>Email</Label><Input type="email" value={f.email ?? ''} onChange={(e) => setF({ ...f, email: e.target.value })} disabled={!editable} /></div>
        <div className="flex flex-col gap-1"><Label>Phone</Label><Input value={f.phone ?? ''} onChange={(e) => setF({ ...f, phone: e.target.value })} disabled={!editable} /></div><LookupSelect label="Department" source="/departments" value={f.department_id} onChange={(v) => setF({ ...f, department_id: v })} disabled={!editable} /><LookupSelect label="Linked employee (HR)" source="/employees" sourceLabel="full_name" value={f.employee_id} onChange={(v) => setF({ ...f, employee_id: v })} disabled={!editable} />
        {isNew && <div className="flex flex-col gap-1"><Label>Initial password *</Label><Input type="text" value={f.password} onChange={(e) => setF({ ...f, password: e.target.value })} placeholder="Min 8 chars, letters + numbers" /></div>}
        <label className="flex items-center justify-between rounded border p-2 text-sm"><span>Active</span><Switch checked={!!f.is_active} onCheckedChange={(v) => setF({ ...f, is_active: v })} disabled={!editable} /></label><label className="flex items-center justify-between rounded border p-2 text-sm"><span>Must change password at next login</span><Switch checked={!!f.must_change_password} onCheckedChange={(v) => setF({ ...f, must_change_password: v })} disabled={!editable} /></label>{me?.is_superuser && <label className="flex items-center justify-between rounded border border-amber-400/50 p-2 text-sm"><span>Superuser (bypasses all permission checks)</span><Switch checked={!!f.is_superuser} onCheckedChange={(v) => setF({ ...f, is_superuser: v })} /></label>}
      </div>{!isNew && u && <KV className="mt-3" cols={4} items={[['Last login', u.last_login_at ? fmtDateTime(u.last_login_at) : 'never'], ['Created', fmtDateTime(u.created_at)], ['Failed logins', u.failed_login_count ?? 0], ['Locked until', u.locked_until ? fmtDateTime(u.locked_until) : '—']]} />}</TabsContent>
      <TabsContent value="access"><div className="grid gap-4 md:grid-cols-2"><Section title="Roles" description="Permissions are the union of all assigned roles."><div className="grid gap-1 sm:grid-cols-2">{roleList.map((r) => <label key={r.id} className="flex items-start gap-2 rounded border p-2 text-sm"><Checkbox checked={f.role_ids.includes(r.id)} onCheckedChange={(c) => setF({ ...f, role_ids: c ? [...f.role_ids, r.id] : f.role_ids.filter((x: string) => x !== r.id) })} disabled={!editable} /><span><span className="font-medium">{r.name}</span><span className="block text-xs text-muted-foreground">{r.description ?? r.code} · {r.permissions?.length ?? 0} perms</span></span></label>)}</div></Section>
        <Section title="Property access"><div className="space-y-1">{propList.map((p) => <label key={p.id} className="flex items-center gap-2 rounded border p-2 text-sm"><Checkbox checked={f.property_ids.includes(p.id)} onCheckedChange={(c) => setF({ ...f, property_ids: c ? [...f.property_ids, p.id] : f.property_ids.filter((x: string) => x !== p.id) })} disabled={!editable} /><span className="flex-1">{p.name} <span className="text-xs text-muted-foreground">{p.code}</span></span>{f.property_ids.includes(p.id) && <Button size="sm" variant={f.default_property_id === p.id ? 'secondary' : 'ghost'} className="h-6 text-xs" onClick={() => setF({ ...f, default_property_id: p.id })}>{f.default_property_id === p.id ? 'default' : 'make default'}</Button>}</label>)}</div></Section></div></TabsContent>
      <TabsContent value="overrides"><div className="mb-2 flex items-center gap-2 text-sm"><Input className="w-64" placeholder="Filter permissions…" value={permFilter} onChange={(e) => setPermFilter(e.target.value)} /><span className="text-xs text-muted-foreground">Overrides win over roles: DENY always blocks, ALLOW grants without changing the role.</span></div><div className="max-h-[50vh] space-y-3 overflow-auto pr-1">{Object.entries(modules).map(([mod, list]) => { const items = list.filter((p) => !permFilter || p.code.includes(permFilter) || p.description.toLowerCase().includes(permFilter.toLowerCase())); if (!items.length) return null; return <div key={mod}><div className="mb-1 text-xs font-semibold uppercase text-muted-foreground">{titleCase(mod)}</div><div className="grid gap-1 md:grid-cols-2">{items.map((p) => { const e = ovr(p.code); return <div key={p.code} className={`flex items-center gap-2 rounded border px-2 py-1 text-xs ${e === 'DENY' ? 'border-destructive/50 bg-destructive/5' : e === 'ALLOW' ? 'border-emerald-500/50 bg-emerald-50/50 dark:bg-emerald-950/20' : ''}`}><span className="flex-1"><span className="font-mono">{p.code}</span><span className="block text-muted-foreground">{p.description}</span></span><NativeSelect value={e ?? ''} onChange={(ev) => setOvr(p.code, (ev.target.value || undefined) as any)} className="h-7 w-24 text-xs" disabled={!editable}><option value="">inherit</option><option value="ALLOW">ALLOW</option><option value="DENY">DENY</option></NativeSelect></div>; })}</div></div>; })}</div></TabsContent>
      <TabsContent value="limits"><Section title="Per-user authority limits" description="Override the role limits for this person (e.g. a supervisor allowed 20% discount while the role allows 10%)."><div className="space-y-2">{f.limits.map((l: any, i: number) => <div key={i} className="flex items-center gap-2"><NativeSelect value={l.limit_code} onChange={(e) => setF({ ...f, limits: f.limits.map((x: any, j: number) => (j === i ? { ...x, limit_code: e.target.value } : x)) })} className="w-64"><option value="">Select limit…</option>{LIMIT_CODES.map((c) => <option key={c} value={c}>{titleCase(c)}</option>)}</NativeSelect><Input type="number" className="w-40" value={l.limit_value} onChange={(e) => setF({ ...f, limits: f.limits.map((x: any, j: number) => (j === i ? { ...x, limit_value: Number(e.target.value) } : x)) })} /><Button size="sm" variant="ghost" onClick={() => setF({ ...f, limits: f.limits.filter((_: any, j: number) => j !== i) })}>×</Button></div>)}<Button size="sm" variant="outline" onClick={() => setF({ ...f, limits: [...f.limits, { limit_code: '', limit_value: 0 }] })}><Plus />Add limit</Button></div></Section></TabsContent>
      {!isNew && <TabsContent value="security"><div className="space-y-3"><div className="flex flex-wrap gap-2">{can('users.reset_password') && <Button variant="outline" onClick={() => setPw(true)}><KeyRound />Reset password</Button>}{can('users.disable') && me?.id !== id && <Button variant="outline" loading={toggle.isPending} onClick={() => toggle.mutate(undefined as any)}><Power />{u?.is_active ? 'Disable account' : 'Enable account'}</Button>}{can('users.sessions') && <Button variant="outline" loading={revoke.isPending} onClick={() => revoke.mutate(undefined as any)}><LogOut />Sign out everywhere</Button>}</div>
        {sessions && <Section title="Sessions"><table className="w-full text-xs"><thead className="uppercase text-muted-foreground"><tr><th className="p-1 text-left">Started</th><th className="p-1 text-left">Last seen</th><th className="p-1 text-left">IP</th><th className="p-1 text-left">Device</th><th className="p-1">State</th></tr></thead><tbody className="divide-y">{(sessions.data ?? sessions).map((s: any) => <tr key={s.id}><td className="p-1">{fmtDateTime(s.created_at)}</td><td className="p-1">{fmtDateTime(s.last_seen_at)}</td><td className="p-1">{s.ip_address}</td><td className="p-1 max-w-xs truncate">{s.device_name ?? s.user_agent}</td><td className="p-1 text-center">{s.revoked_at ? <Badge tone="muted">revoked</Badge> : new Date(s.expires_at) < new Date() ? <Badge tone="muted">expired</Badge> : <Badge tone="success">active</Badge>}</td></tr>)}</tbody></table></Section>}
        {u?.login_history && <Section title="Recent logins"><ul className="divide-y text-xs">{u.login_history.map((h: any, i: number) => <li key={i} className="flex justify-between py-1"><span>{fmtDateTime(h.created_at)} · {h.ip_address}</span><StatusBadge status={h.action} /></li>)}</ul></Section>}</div></TabsContent>}
    </Tabs>
    {editable && <div className="flex justify-end border-t pt-3"><Button loading={save.isPending} disabled={!f.username || !f.full_name || (isNew && !f.password)} onClick={() => save.mutate(undefined as any)}><Save />{isNew ? 'Create user' : 'Save changes'}</Button></div>}
    <ConfirmDialog open={pw} onOpenChange={setPw} title="Reset password" description="The user will be asked to change it at next login." confirmLabel="Reset" fields={[{ name: 'newPassword', label: 'Temporary password', required: true }]} onConfirm={(v) => reset.mutateAsync(v)} />
  </div></Modal>;
}
export default function UsersPage() {
  const { can } = useAuth(); const [sel, setSel] = useState<string | 'new' | null>(null); const [tick, setTick] = useState(0);
  return <div className="space-y-4">
    <PageHeader title="Users" subtitle="Accounts, role assignment and property access. Permissions are enforced server-side on every request." crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'Users' }]} actions={can('users.create') && <Button onClick={() => setSel('new')}><Plus />New user</Button>} />
    <DataTable path="/users" defaultSort="full_name" refreshKey={tick} onRowClick={(r) => setSel(r.id)} exportName="users" filters={[{ key: 'role', label: 'Role', type: 'select', source: '/roles', sourceLabel: 'name' }, { key: 'active', label: 'Status', type: 'select', options: [{ value: 'true', label: 'Active' }, { value: 'false', label: 'Disabled' }] }]}
      columns={[{ key: 'full_name', label: 'Name', render: (r) => <span>{r.full_name}<span className="block text-xs text-muted-foreground">@{r.username}{r.email && ` · ${r.email}`}</span></span> }, { key: 'roles', label: 'Roles', render: (r) => <span className="flex flex-wrap gap-1">{(r.roles ?? []).map((x: any) => <Badge key={x.id ?? x.code ?? x} tone="muted">{x.name ?? x}</Badge>)}{r.is_superuser && <Badge tone="warning">superuser</Badge>}</span> }, { key: 'department_name', label: 'Department', hideOnMobile: true }, { key: 'default_property_name', label: 'Default property', hideOnMobile: true }, { key: 'last_login_at', label: 'Last login', type: 'datetime' }, { key: 'is_active', label: 'Status', render: (r) => <StatusBadge status={r.is_active ? 'ACTIVE' : 'DISABLED'} /> }]} />
    <UserEditor id={sel} onClose={() => setSel(null)} onSaved={(id) => { setTick((t) => t + 1); setSel(id); }} />
  </div>;
}
