'use client';
import React, { Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Plus, PackageCheck, Undo2, X } from 'lucide-react';
import { post, get } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, KV, Section } from '@/components/shared/page';
import { DataTable } from '@/components/shared/data-table';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Modal } from '@/components/ui/dialog';
import { Input, Label, Textarea } from '@/components/ui/input';
import { LookupSelect, ConfirmDialog } from '@/components/shared/form';
import { Switch } from '@/components/ui/misc';
import { ProductSearch, LinesTable } from '@/components/inventory/product-lines';
import { AuditTrail } from '@/components/shared/audit-trail';
import { Attachments } from '@/components/shared/attachments';
import { fmtDate, fmtDateTime, fmtMoney, fmtNum, today } from '@/lib/utils';

interface Line { key: string; po_item_id?: string | null; product_id?: string | null; description: string; sku?: string; unit?: string; ordered?: number; outstanding?: number; received_qty: string | number; accepted_qty: string | number; rejected_qty: string | number; damaged_qty: string | number; unit_cost: string | number; tax_id?: string | null; batch_no: string; expiry_date: string; track_expiry?: boolean; track_batches?: boolean; rejection_reason: string }
/** Receiving screen: lines come from the PO (outstanding quantities) or are added ad hoc for direct receipts. Accepted qty enters stock at unit cost. */
function NewGRN({ open, onOpenChange, poId, onCreated }: { open: boolean; onOpenChange: (o: boolean) => void; poId?: string | null; onCreated: (g: any) => void }) {
  const { currency, can } = useAuth();
  const [po, setPo] = useState<any>(null); const [f, setF] = useState<any>({ supplier_id: '', store_id: '', delivery_note_no: '', received_date: today(), notes: '', complete: true }); const [lines, setLines] = useState<Line[]>([]);
  const set = (k: string, v: any) => setF((x: any) => ({ ...x, [k]: v }));
  useEffect(() => { if (!poId) return; (async () => { const p = await get(`/purchase-orders/${poId}`); setPo(p); setF((x: any) => ({ ...x, supplier_id: p.supplier_id, store_id: p.store_id ?? '' })); setLines((p.items ?? []).filter((i: any) => Number(i.outstanding_qty) > 0).map((i: any) => ({ key: i.id, po_item_id: i.id, product_id: i.product_id, description: i.product_name ?? i.description, sku: i.sku, unit: i.unit, ordered: Number(i.quantity), outstanding: Number(i.outstanding_qty), received_qty: Number(i.outstanding_qty), accepted_qty: Number(i.outstanding_qty), rejected_qty: 0, damaged_qty: 0, unit_cost: Number(i.unit_price), tax_id: i.tax_id, batch_no: '', expiry_date: '', track_expiry: i.track_expiry, track_batches: i.track_batches, rejection_reason: '' }))); })(); }, [poId]);
  const setAt = (k: string, patch: Partial<Line>) => setLines((ls) => ls.map((l) => (l.key === k ? { ...l, ...patch } : l)));
  const onRecv = (l: Line, v: string) => { const r = Number(v || 0); setAt(l.key, { received_qty: v, accepted_qty: Math.max(0, r - Number(l.rejected_qty || 0) - Number(l.damaged_qty || 0)) }); };
  const total = lines.reduce((s, l) => s + Number(l.accepted_qty || 0) * Number(l.unit_cost || 0), 0);
  const create = useAction(() => post('/grns', { purchase_order_id: poId ?? null, supplier_id: f.supplier_id || undefined, store_id: f.store_id, delivery_note_no: f.delivery_note_no || null, received_date: f.received_date, notes: f.notes || null, complete: f.complete, items: lines.filter((l) => Number(l.received_qty) > 0).map((l) => ({ po_item_id: l.po_item_id ?? null, product_id: l.product_id ?? null, description: l.product_id ? null : l.description, received_qty: Number(l.received_qty), accepted_qty: Number(l.accepted_qty), rejected_qty: Number(l.rejected_qty || 0), damaged_qty: Number(l.damaged_qty || 0), unit_cost: Number(l.unit_cost), tax_id: l.tax_id ?? null, batch_no: l.batch_no || null, expiry_date: l.expiry_date || null, rejection_reason: l.rejection_reason || null })) }, true), { success: f.complete ? 'Goods received — stock updated' : 'GRN saved as draft', invalidate: ['/grns', '/purchase-orders', '/stock', '/journals'], onSuccess: (g: any) => { onOpenChange(false); onCreated(g); } });
  return <Modal open={open} onOpenChange={onOpenChange} title={po ? `Receive goods · ${po.number} · ${po.supplier_name}` : 'Direct goods receipt (no PO)'} size="xl"><div className="space-y-3">
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
      {!po && <div className="flex flex-col gap-1"><Label>Supplier</Label><LookupSelect source="/suppliers" value={f.supplier_id} onChange={(v) => set('supplier_id', v)} allowEmpty={false} placeholder="Select supplier" /></div>}
      <div className="flex flex-col gap-1"><Label>Receiving store</Label><LookupSelect source="/stores" value={f.store_id} onChange={(v) => set('store_id', v)} allowEmpty={false} placeholder="Select store" /></div>
      <div className="flex flex-col gap-1"><Label>Delivery note no.</Label><Input value={f.delivery_note_no} onChange={(e) => set('delivery_note_no', e.target.value)} /></div>
      <div className="flex flex-col gap-1"><Label>Received date</Label><Input type="date" value={f.received_date} onChange={(e) => set('received_date', e.target.value)} /></div>
      <div className="flex flex-col gap-1 col-span-2 md:col-span-4"><Label>Notes / QC remarks</Label><Input value={f.notes} onChange={(e) => set('notes', e.target.value)} /></div>
    </div>
    {!po && can('purchases.create') && <ProductSearch stockOnly={false} onPick={(p) => setLines([...lines, { key: `${p.id}-${Date.now()}`, product_id: p.id, description: p.name, sku: p.sku, unit: p.unit, received_qty: 1, accepted_qty: 1, rejected_qty: 0, damaged_qty: 0, unit_cost: Number(p.cost_price ?? 0), tax_id: p.tax_id, batch_no: '', expiry_date: '', track_expiry: p.track_expiry, track_batches: p.track_batches, rejection_reason: '' }])} />}
    <div className="overflow-x-auto rounded-md border"><table className="w-full text-sm min-w-[900px]"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Item</th>{po && <th className="p-2 text-right">Outstanding</th>}<th className="p-2 text-right w-24">Received</th><th className="p-2 text-right w-24">Rejected</th><th className="p-2 text-right w-24">Damaged</th><th className="p-2 text-right w-24">Accepted</th><th className="p-2 text-right w-28">Unit cost</th><th className="p-2 text-left w-40">Batch / expiry</th><th className="p-2 text-right">Value</th><th className="w-8" /></tr></thead>
      <tbody className="divide-y">{lines.map((l) => <tr key={l.key} className={Number(l.received_qty) > (l.outstanding ?? Infinity) ? 'bg-amber-500/5' : ''}><td className="p-2"><div className="font-medium">{l.description}</div><div className="text-xs text-muted-foreground">{l.sku} · {l.unit}{Number(l.rejected_qty) + Number(l.damaged_qty) > 0 && <Input className="mt-1 h-7" placeholder="Rejection reason" value={l.rejection_reason} onChange={(e) => setAt(l.key, { rejection_reason: e.target.value })} />}</div></td>{po && <td className="p-2 text-right tabular">{fmtNum(l.outstanding, 2)}<div className="text-xs text-muted-foreground">of {fmtNum(l.ordered, 2)}</div></td>}<td className="p-1"><Input type="number" step="any" min={0} className="text-right" value={l.received_qty} onChange={(e) => onRecv(l, e.target.value)} /></td><td className="p-1"><Input type="number" step="any" min={0} className="text-right" value={l.rejected_qty} onChange={(e) => setAt(l.key, { rejected_qty: e.target.value, accepted_qty: Math.max(0, Number(l.received_qty) - Number(e.target.value || 0) - Number(l.damaged_qty || 0)) })} /></td><td className="p-1"><Input type="number" step="any" min={0} className="text-right" value={l.damaged_qty} onChange={(e) => setAt(l.key, { damaged_qty: e.target.value, accepted_qty: Math.max(0, Number(l.received_qty) - Number(l.rejected_qty || 0) - Number(e.target.value || 0)) })} /></td><td className="p-2 text-right tabular font-medium">{fmtNum(l.accepted_qty, 2)}</td><td className="p-1"><Input type="number" step="0.01" className="text-right" value={l.unit_cost} onChange={(e) => setAt(l.key, { unit_cost: e.target.value })} /></td><td className="p-1 space-y-1">{(l.track_batches || l.track_expiry) ? <><Input className="h-7" placeholder="Batch no." value={l.batch_no} onChange={(e) => setAt(l.key, { batch_no: e.target.value })} /><Input type="date" className="h-7" value={l.expiry_date} onChange={(e) => setAt(l.key, { expiry_date: e.target.value })} /></> : <span className="text-xs text-muted-foreground">—</span>}</td><td className="p-2 text-right tabular">{fmtMoney(Number(l.accepted_qty || 0) * Number(l.unit_cost || 0), currency)}</td><td className="p-1"><Button size="icon" variant="ghost" className="h-7 w-7" onClick={() => setLines(lines.filter((x) => x.key !== l.key))}>×</Button></td></tr>)}{lines.length === 0 && <tr><td colSpan={10} className="p-6 text-center text-muted-foreground">{po ? 'Everything on this PO has been received.' : 'Add products to receive.'}</td></tr>}</tbody></table></div>
    <div className="flex flex-wrap items-center justify-between gap-2"><label className="flex items-center gap-2 text-sm"><Switch checked={f.complete} onCheckedChange={(v) => set('complete', v)} /> Complete now (post to stock & GRN accrual). Off = save for QC check.</label><div className="flex items-center gap-3"><span className="text-sm">Accepted value <b>{fmtMoney(total, currency)}</b></span><Button loading={create.isPending} disabled={!f.store_id || lines.filter((l) => Number(l.received_qty) > 0).length === 0 || (!po && !f.supplier_id)} onClick={() => create.mutate(undefined as any)}><PackageCheck />{f.complete ? 'Receive & post' : 'Save draft GRN'}</Button></div></div>
  </div></Modal>;
}
function GRNDetail({ id, onClose }: { id: string | null; onClose: () => void }) {
  const { can, currency } = useAuth(); const router = useRouter(); const { data: g, refetch } = useApi<any>(id ? `/grns/${id}` : null);
  const [cancel, setCancel] = useState(false); const [ret, setRet] = useState(false); const [retQty, setRetQty] = useState<Record<string, string>>({}); const [reason, setReason] = useState('');
  const inv = ['/grns', '/purchase-orders', '/stock', '/journals'];
  const completeM = useAction(() => post(`/grns/${id}/complete`), { success: 'GRN completed — stock posted', invalidate: inv, onSuccess: () => refetch() });
  const cancelM = useAction((v: any) => post(`/grns/${id}/cancel`, v), { success: 'GRN cancelled', invalidate: inv, onSuccess: () => { setCancel(false); refetch(); } });
  const returnM = useAction(() => post(`/grns/${id}/return`, { reason, items: Object.entries(retQty).filter(([, q]) => Number(q) > 0).map(([grn_item_id, q]) => ({ grn_item_id, quantity: Number(q) })) }, true), { success: 'Return to supplier posted', invalidate: inv, onSuccess: () => { setRet(false); setRetQty({}); refetch(); } });
  if (!id) return null;
  return <Modal open={!!id} onOpenChange={(o) => !o && onClose()} title={g ? <span className="flex items-center gap-2">{g.number} <StatusBadge status={g.status} /></span> : 'GRN'} size="xl">{g && <div className="space-y-4">
    <KV cols={4} items={[['Supplier', g.supplier_name], ['Purchase order', g.po_number ? <a key="po" className="underline" href={`/procurement/purchase-orders?id=${g.purchase_order_id}`}>{g.po_number}</a> : 'Direct receipt'], ['Store', g.store_name], ['Delivery note', g.delivery_note_no ?? '—'], ['Received', `${fmtDate(g.received_date)} · ${g.received_by_name}`], ['Completed', g.completed_at ? fmtDateTime(g.completed_at) : '—'], ['Total value', <b key="v">{fmtMoney(g.total_value, currency)}</b>], ['Journal', g.journal_entry_id ? <a key="j" className="underline" href={`/finance/journals?id=${g.journal_entry_id}`}>view</a> : '—']]} />
    <LinesTable rows={g.items} columns={[{ key: 'product_name', label: 'Item', render: (i) => <div><div className="font-medium">{i.product_name ?? i.description}</div><div className="text-xs text-muted-foreground">{i.sku}{i.batch_no ? ` · batch ${i.batch_no}` : ''}{i.expiry_date ? ` · exp ${fmtDate(i.expiry_date)}` : ''}{i.rejection_reason ? ` · ${i.rejection_reason}` : ''}</div></div> }, { key: 'ordered_qty', label: 'Ordered', align: 'right', render: (i) => (i.ordered_qty == null ? '—' : fmtNum(i.ordered_qty, 2)) }, { key: 'received_qty', label: 'Received', align: 'right', render: (i) => fmtNum(i.received_qty, 2) }, { key: 'rejected_qty', label: 'Rejected', align: 'right', render: (i) => fmtNum(i.rejected_qty, 2) }, { key: 'damaged_qty', label: 'Damaged', align: 'right', render: (i) => fmtNum(i.damaged_qty, 2) }, { key: 'accepted_qty', label: 'Accepted', align: 'right', render: (i) => <b>{fmtNum(i.accepted_qty, 2)}</b> }, { key: 'unit_cost', label: 'Unit cost', align: 'right', render: (i) => fmtMoney(i.unit_cost, currency) }, { key: 'value', label: 'Value', align: 'right', render: (i) => fmtMoney(Number(i.accepted_qty) * Number(i.unit_cost), currency) }, ...(ret ? [{ key: 'ret', label: 'Return qty', align: 'right' as const, render: (i: any) => <Input type="number" step="any" min={0} max={i.accepted_qty} className="w-24 text-right ml-auto" value={retQty[i.id] ?? ''} onChange={(e) => setRetQty({ ...retQty, [i.id]: e.target.value })} /> }] : [])]} />
    {ret ? <div className="flex items-end gap-3"><div className="flex-1 flex flex-col gap-1"><Label>Return reason</Label><Textarea rows={1} value={reason} onChange={(e) => setReason(e.target.value)} /></div><Button variant="ghost" onClick={() => setRet(false)}>Back</Button><Button loading={returnM.isPending} disabled={reason.length < 2 || !Object.values(retQty).some((q) => Number(q) > 0)} onClick={() => returnM.mutate(undefined as any)}><Undo2 />Post return</Button></div>
      : <div className="flex flex-wrap gap-2">{['DRAFT', 'PENDING_QC'].includes(g.status) && can('purchases.receive') && <Button onClick={() => completeM.mutate(undefined as any)}><PackageCheck />Complete & post</Button>}{g.status === 'COMPLETED' && can('purchases.receive', 'purchases.invoice') && <Button variant="outline" onClick={() => setRet(true)}><Undo2 />Return to supplier</Button>}{g.status === 'COMPLETED' && can('purchases.invoice') && <Button variant="outline" onClick={() => router.push(`/procurement/supplier-invoices?new=1&grn=${g.id}`)}>Record supplier invoice</Button>}{['DRAFT', 'PENDING_QC'].includes(g.status) && can('purchases.receive') && <Button variant="ghost" onClick={() => setCancel(true)}><X />Cancel</Button>}</div>}
    <Attachments entity="grn" entityId={id} title="Delivery note & photos" />
    <AuditTrail entity="grn" entityId={id} />
    <ConfirmDialog open={cancel} onOpenChange={setCancel} title="Cancel GRN" destructive confirmLabel="Cancel GRN" fields={[{ name: 'reason', label: 'Reason', required: true }]} onConfirm={(v) => cancelM.mutateAsync(v)} />
  </div>}</Modal>;
}
function GRNsPageInner() {
  const { can } = useAuth(); const sp = useSearchParams(); const router = useRouter();
  const [open, setOpen] = useState<{ po?: string | null } | null>(null); const [sel, setSel] = useState<string | null>(null);
  useEffect(() => { if (sp.get('new')) setOpen({ po: sp.get('po') }); if (sp.get('id')) setSel(sp.get('id')); }, [sp]);
  return <div className="space-y-4">
    <PageHeader title="Goods received notes" subtitle="Receiving against purchase orders (or direct for cash purchases). Accepted quantities enter stock at cost and accrue to GRN/IR until the supplier invoice arrives." actions={can('purchases.receive') && can('purchases.create') && <Button variant="outline" onClick={() => setOpen({})}><Plus />Direct receipt</Button>} />
    <DataTable path="/grns" defaultSort="created_at" onRowClick={(r) => setSel(r.id)} filters={[{ key: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PENDING_QC', 'COMPLETED', 'CANCELLED'] }, { key: 'supplier_id', label: 'Supplier', type: 'select', source: '/suppliers' }, { key: 'store_id', label: 'Store', type: 'select', source: '/stores' }]}
      columns={[{ key: 'number', label: 'GRN' }, { key: 'received_date', label: 'Date', type: 'date' }, { key: 'supplier_name', label: 'Supplier' }, { key: 'po_number', label: 'PO', render: (r) => r.po_number ?? <Badge tone="muted">Direct</Badge> }, { key: 'store_name', label: 'Store' }, { key: 'delivery_note_no', label: 'Delivery note' }, { key: 'item_count', label: 'Lines', type: 'number', decimals: 0 }, { key: 'total_value', label: 'Value', type: 'money' }, { key: 'received_by_name', label: 'Received by' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }]} />
    {open && <NewGRN open={!!open} poId={open.po} onOpenChange={(o) => { if (!o) { setOpen(null); router.replace('/procurement/grns'); } }} onCreated={(g) => setSel(g.id)} />}
    <GRNDetail id={sel} onClose={() => { setSel(null); if (sp.get('id')) router.replace('/procurement/grns'); }} />
  </div>;
}
export default function GRNsPage() { return <Suspense fallback={null}><GRNsPageInner /></Suspense>; }
