'use client';
import React, { useEffect, useState } from 'react';
import { Plus, Save, Trash2, Copy } from 'lucide-react';
import { post, put, del } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input, Label, Textarea, NativeSelect } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/misc';
import { ConfirmDialog } from '@/components/shared/form';
import { titleCase } from '@/lib/utils';

const LIMIT_CODES = ['discount_percent', 'refund_amount', 'cash_variance_amount', 'purchase_approval_amount', 'expense_approval_amount', 'credit_limit_override', 'void_amount'];
export default function RolesPage() {
  const { can } = useAuth(); const { data: roles, refetch } = useApi<any>('/roles'); const { data: perms } = useApi<any>('/permissions'); const [sel, setSel] = useState<any>(null); const [f, setF] = useState<any>(null); const [filter, setFilter] = useState(''); const [delOpen, setDelOpen] = useState(false);
  const list: any[] = roles?.data ?? []; const modules: Record<string, { code: string; description: string }[]> = perms?.modules ?? {};
  useEffect(() => { if (!sel && list.length) setSel(list[0]); }, [list, sel]);
  useEffect(() => { if (sel) setF({ id: sel.id, code: sel.code ?? '', name: sel.name ?? '', description: sel.description ?? '', permissions: [...(sel.permissions ?? [])], limits: [...(sel.limits ?? [])], is_system: sel.is_system }); }, [sel]);
  const save = useAction(() => (f.id ? put(`/roles/${f.id}`, { code: f.code, name: f.name, description: f.description || null, permissions: f.permissions, limits: f.limits.filter((l: any) => l.limit_code) }) : post('/roles', { code: f.code, name: f.name, description: f.description || null, permissions: f.permissions, limits: f.limits.filter((l: any) => l.limit_code) })), { success: 'Role saved', invalidate: ['/roles', '/users'], onSuccess: async (r: any) => { const d = await refetch(); const fresh = (d.data?.data ?? []).find((x: any) => x.id === (r?.id ?? f.id)); if (fresh) setSel(fresh); } });
  const remove = useAction(() => del(`/roles/${f.id}`), { success: 'Role deleted', invalidate: ['/roles'], onSuccess: () => { setDelOpen(false); setSel(null); refetch(); } });
  const has = (c: string) => f?.permissions.includes(c); const toggle = (c: string, on: boolean) => setF({ ...f, permissions: on ? Array.from(new Set([...f.permissions, c])) : f.permissions.filter((x: string) => x !== c) });
  const toggleModule = (mod: string, on: boolean) => { const codes = modules[mod].map((p) => p.code); setF({ ...f, permissions: on ? Array.from(new Set([...f.permissions, ...codes])) : f.permissions.filter((x: string) => !codes.includes(x)) }); };
  const editable = f && (f.id ? can('roles.edit') : can('roles.create'));
  return <div className="space-y-4">
    <PageHeader title="Roles & permissions" subtitle={`${perms?.data?.length ?? 0} granular permissions across ${Object.keys(modules).length} modules. Roles are data — create as many as the organisation needs.`} crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'Roles' }]} actions={can('roles.create') && <div className="flex gap-2">{f?.id && <Button variant="outline" onClick={() => { setSel(null); setF({ ...f, id: null, code: `${f.code}_COPY`, name: `${f.name} (copy)`, is_system: false }); }}><Copy />Duplicate</Button>}<Button onClick={() => { setSel(null); setF({ id: null, code: '', name: '', description: '', permissions: [], limits: [], is_system: false }); }}><Plus />New role</Button></div>} />
    <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
      <aside className="rounded-lg border bg-card p-2 lg:max-h-[75vh] lg:overflow-auto">{list.map((r) => <button key={r.id} type="button" onClick={() => setSel(r)} className={`block w-full rounded px-2 py-1.5 text-left text-sm ${f?.id === r.id ? 'bg-primary/10 font-medium text-primary' : 'hover:bg-accent'}`}><div className="flex items-center justify-between">{r.name}{r.is_system && <Badge tone="muted">system</Badge>}</div><div className="text-xs text-muted-foreground">{r.code} · {r.permissions?.length ?? 0} perms · {r.user_count} user(s)</div></button>)}</aside>
      {f && <div className="space-y-4">
        <Section title={f.id ? 'Role details' : 'New role'} actions={editable && <div className="flex gap-2">{f.id && can('roles.delete') && !f.is_system && <Button size="sm" variant="ghost" className="text-destructive" onClick={() => setDelOpen(true)}><Trash2 />Delete</Button>}<Button size="sm" loading={save.isPending} disabled={!f.code || !f.name} onClick={() => save.mutate(undefined as any)}><Save />Save</Button></div>}><div className="grid gap-3 md:grid-cols-3"><div className="flex flex-col gap-1"><Label>Code (UPPER_SNAKE)</Label><Input value={f.code} onChange={(e) => setF({ ...f, code: e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g, '_') })} disabled={!editable || f.is_system} /></div><div className="flex flex-col gap-1"><Label>Name</Label><Input value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} disabled={!editable} /></div><div className="flex flex-col gap-1"><Label>Description</Label><Input value={f.description} onChange={(e) => setF({ ...f, description: e.target.value })} disabled={!editable} /></div></div></Section>
        <Section title="Authority limits" description="Numeric ceilings checked by the backend (e.g. max discount % a waiter can give before a supervisor approval is required)."><div className="space-y-2">{f.limits.map((l: any, i: number) => <div key={i} className="flex items-center gap-2"><NativeSelect value={l.limit_code} onChange={(e) => setF({ ...f, limits: f.limits.map((x: any, j: number) => (j === i ? { ...x, limit_code: e.target.value } : x)) })} className="w-64" disabled={!editable}><option value="">Select limit…</option>{LIMIT_CODES.map((c) => <option key={c} value={c}>{titleCase(c)}</option>)}</NativeSelect><Input type="number" className="w-40" value={l.limit_value} onChange={(e) => setF({ ...f, limits: f.limits.map((x: any, j: number) => (j === i ? { ...x, limit_value: Number(e.target.value) } : x)) })} disabled={!editable} /><Button size="sm" variant="ghost" onClick={() => setF({ ...f, limits: f.limits.filter((_: any, j: number) => j !== i) })} disabled={!editable}>×</Button></div>)}{editable && <Button size="sm" variant="outline" onClick={() => setF({ ...f, limits: [...f.limits, { limit_code: '', limit_value: 0 }] })}><Plus />Add limit</Button>}</div></Section>
        <Section title={`Permissions (${f.permissions.length})`} actions={<Input className="h-8 w-56" placeholder="Filter…" value={filter} onChange={(e) => setFilter(e.target.value)} />}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(modules).map(([mod, items]) => { const shown = items.filter((p) => !filter || p.code.includes(filter.toLowerCase()) || p.description.toLowerCase().includes(filter.toLowerCase())); if (!shown.length) return null; const all = items.every((p) => has(p.code)); const some = items.some((p) => has(p.code)); return <div key={mod} className="rounded border"><label className="flex items-center gap-2 border-b bg-muted/40 px-2 py-1.5 text-sm font-medium"><Checkbox checked={all ? true : some ? 'indeterminate' : false} onCheckedChange={(c) => toggleModule(mod, !!c)} disabled={!editable} />{titleCase(mod)}<span className="ml-auto text-xs font-normal text-muted-foreground">{items.filter((p) => has(p.code)).length}/{items.length}</span></label><div className="p-1">{shown.map((p) => <label key={p.code} className="flex items-start gap-2 rounded px-1 py-1 text-xs hover:bg-accent/50"><Checkbox className="mt-0.5" checked={has(p.code)} onCheckedChange={(c) => toggle(p.code, !!c)} disabled={!editable} /><span><span className="font-mono">{p.code}</span><span className="block text-muted-foreground">{p.description}</span></span></label>)}</div></div>; })}</div></Section>
      </div>}
    </div>
    <ConfirmDialog open={delOpen} onOpenChange={setDelOpen} title={`Delete role ${f?.name}?`} description="Users holding only this role will lose access. Roles that are still assigned cannot be deleted." destructive confirmLabel="Delete" onConfirm={() => remove.mutateAsync(undefined as any)} />
  </div>;
}
