'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { Plus, ArrowDownToLine, ArrowUpFromLine, Scale, Wallet } from 'lucide-react';
import { post, put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { FormDialog, ConfirmDialog } from '@/components/shared/form';
import { fmtDate, fmtDateTime, fmtMoney, titleCase } from '@/lib/utils';
import { ExpenseDetail } from '../expenses/expenses-view';

const fundFields = [{ name: 'name', label: 'Fund name', required: true }, { name: 'custodian_user_id', label: 'Custodian', type: 'lookup' as const, source: '/users', sourceLabel: 'full_name', required: true }, { name: 'department_id', label: 'Department', type: 'lookup' as const, source: '/departments', sourceLabel: 'name' }, { name: 'float_amount', label: 'Float (imprest) amount', type: 'money' as const, required: true }, { name: 'account_id', label: 'GL account (default: petty cash mapping)', type: 'lookup' as const, source: '/accounts', sourceQuery: { type: 'ASSET', header: 'false', pageSize: 500 }, sourceLabel: (a: any) => `${a.code} · ${a.name}` }];
const TX_TONE: Record<string, any> = { REPLENISH: 'success', EXPENSE: 'warning', RETURN: 'muted', RECONCILE: 'info', OPENING: 'muted' };
function FundPanel({ fundId }: { fundId: string }) {
  const { can, currency, user } = useAuth(); const { data: f, refetch } = useApi<any>(`/petty-cash/funds/${fundId}`); const { data: txs, refetch: refetchTx } = useApi<any>(`/petty-cash/funds/${fundId}/transactions`, { pageSize: 100 }); const [dlg, setDlg] = useState<'replenish' | 'return' | 'reconcile' | 'edit' | null>(null); const [exp, setExp] = useState<string | null>(null);
  const done = { invalidate: ['/petty-cash', '/payments'], onSuccess: () => { setDlg(null); refetch(); refetchTx(); } };
  const replenish = useAction((v: any) => post(`/petty-cash/funds/${fundId}/replenish`, v), { success: 'Fund replenished', ...done });
  const ret = useAction((v: any) => post(`/petty-cash/funds/${fundId}/return`, v), { success: 'Cash returned to bank', ...done });
  const reconcile = useAction((v: any) => post(`/petty-cash/funds/${fundId}/reconcile`, v), { success: 'Fund reconciled', ...done });
  const edit = useAction((v: any) => put(`/petty-cash/funds/${fundId}`, v), { success: 'Fund updated', ...done });
  if (!f) return null; const rows: any[] = txs?.data ?? (Array.isArray(txs) ? txs : []); const spent = Number(f.float_amount) - Number(f.balance); const custodian = user?.id === f.custodian_user_id; const supervisor = can('petty_cash.reconcile');
  return <div className="space-y-4">
    <div className="grid gap-3 grid-cols-2 md:grid-cols-5"><div className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">Cash on hand</div><div className="text-xl font-semibold tabular">{fmtMoney(f.balance, currency)}</div></div><div className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">Float</div><div className="text-xl font-semibold tabular">{fmtMoney(f.float_amount, currency)}</div></div><div className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">Spent since top-up</div><div className="text-xl font-semibold tabular">{fmtMoney(Math.max(0, spent), currency)}</div><div className="text-xs text-muted-foreground">{f.float_amount > 0 ? `${Math.round((Math.max(0, spent) / Number(f.float_amount)) * 100)}% used` : ''}</div></div><div className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">Approved, unpaid</div><div className="text-xl font-semibold tabular">{fmtMoney(f.approved_unpaid, currency)}</div></div><div className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">Custodian</div><div className="font-medium">{f.custodian_name}</div><div className="text-xs text-muted-foreground">{f.department_name ?? '—'} · last count {f.last_reconciled_at ? fmtDate(f.last_reconciled_at) : 'never'}</div></div></div>
    <div className="flex flex-wrap gap-2">{(custodian || supervisor || can('petty_cash.manage')) && <Button onClick={() => setDlg('replenish')}><ArrowDownToLine />Replenish (top-up)</Button>}{(custodian || supervisor) && <Button variant="outline" onClick={() => setDlg('return')}><ArrowUpFromLine />Return cash to bank</Button>}{(custodian || supervisor) && <Button variant="outline" onClick={() => setDlg('reconcile')}><Scale />Count & reconcile</Button>}{supervisor && <Button variant="ghost" onClick={() => setDlg('edit')}>Edit fund</Button>}<Link href="/finance/expenses?new=1" className="ml-auto"><Button variant="secondary"><Plus />New petty cash expense</Button></Link></div>
    {(f.pending_expenses ?? []).length > 0 && <Section title="Expenses waiting on this fund"><ul className="divide-y text-sm">{f.pending_expenses.map((e: any) => <li key={e.id} className="flex items-center justify-between py-1.5"><button type="button" className="text-left hover:underline" onClick={() => setExp(e.id)}>{e.number} · {e.description}<span className="text-xs text-muted-foreground"> · {e.requested_by_name}</span></button><span className="flex items-center gap-2"><StatusBadge status={e.status} /><b className="tabular">{fmtMoney(e.total, currency)}</b></span></li>)}</ul></Section>}
    <Section title="Fund ledger" description="Every movement — top-ups, disbursements, returns and count variances — with the resulting balance."><div className="max-h-[50vh] overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">When</th><th className="p-2 text-left">Type</th><th className="p-2 text-left">Description</th><th className="p-2 text-left">By</th><th className="p-2 text-right">Amount</th><th className="p-2 text-right">Balance after</th></tr></thead><tbody className="divide-y">{rows.map((t: any) => <tr key={t.id}><td className="p-2 whitespace-nowrap">{fmtDateTime(t.created_at)}</td><td className="p-2"><Badge tone={TX_TONE[t.type] ?? 'muted'}>{titleCase(t.type)}</Badge></td><td className="p-2">{t.expense_id ? <button type="button" className="hover:underline" onClick={() => setExp(t.expense_id)}>{t.expense_number} · {t.expense_description}</button> : t.description}{t.reference && <span className="text-xs text-muted-foreground"> · {t.reference}</span>}{t.type === 'RECONCILE' && <span className="text-xs text-muted-foreground"> · counted {fmtMoney(t.counted_amount, currency)}, variance {fmtMoney(t.variance, currency)}</span>}</td><td className="p-2 text-xs">{t.created_by_name}</td><td className={`p-2 text-right tabular ${Number(t.amount) < 0 ? 'text-destructive' : 'text-emerald-600'}`}>{fmtMoney(t.amount, currency)}</td><td className="p-2 text-right tabular">{fmtMoney(t.balance_after, currency)}</td></tr>)}{rows.length === 0 && <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">No transactions yet.</td></tr>}</tbody></table></div></Section>
    <ConfirmDialog open={dlg === 'replenish'} onOpenChange={(o) => !o && setDlg(null)} title="Replenish fund" description={`Top the float back up. Suggested: ${fmtMoney(Math.max(0, spent), currency)} (spent since last top-up).`} confirmLabel="Replenish" fields={[{ name: 'amount', label: 'Amount', type: 'money', required: true, default: Math.max(0, spent) }, { name: 'payment_method_id', label: 'Paid from (method)', type: 'lookup', source: '/payment-methods', sourceLabel: 'name' }, { name: 'reference', label: 'Reference (cheque / withdrawal)' }]} onConfirm={(v) => replenish.mutateAsync({ amount: Number(v.amount), payment_method_id: v.payment_method_id || undefined, reference: v.reference || null })} />
    <ConfirmDialog open={dlg === 'return'} onOpenChange={(o) => !o && setDlg(null)} title="Return cash to bank" confirmLabel="Return" fields={[{ name: 'amount', label: 'Amount (blank = full balance)', type: 'money' }, { name: 'payment_method_id', label: 'Deposit to (method)', type: 'lookup', source: '/payment-methods', sourceLabel: 'name' }, { name: 'reference', label: 'Deposit slip no.' }, { name: 'notes', label: 'Notes' }]} onConfirm={(v) => ret.mutateAsync({ amount: v.amount ? Number(v.amount) : undefined, payment_method_id: v.payment_method_id || undefined, reference: v.reference || null, notes: v.notes || null })} />
    <ConfirmDialog open={dlg === 'reconcile'} onOpenChange={(o) => !o && setDlg(null)} title="Count & reconcile" description={`System balance is ${fmtMoney(f.balance, currency)}. Any difference is posted to cash over/short and recorded on the fund ledger.`} confirmLabel="Post count" fields={[{ name: 'counted_amount', label: 'Physically counted amount', type: 'money', required: true }, { name: 'notes', label: 'Notes' }]} onConfirm={(v) => reconcile.mutateAsync({ counted_amount: Number(v.counted_amount), notes: v.notes || null })} />
    <FormDialog open={dlg === 'edit'} onOpenChange={(o) => !o && setDlg(null)} title="Edit fund" fields={[...fundFields.filter((x) => x.name !== 'account_id'), { name: 'is_active', label: 'Active', type: 'switch' as const }]} initial={f} onSubmit={(v) => edit.mutateAsync({ name: v.name, custodian_user_id: v.custodian_user_id, department_id: v.department_id || null, float_amount: Number(v.float_amount), is_active: v.is_active })} />
    <ExpenseDetail id={exp} onClose={() => { setExp(null); refetch(); refetchTx(); }} onEdit={() => setExp(null)} />
  </div>;
}
export default function PettyCashPage() {
  const { can, currency } = useAuth(); const { data: funds, refetch } = useApi<any>('/petty-cash/funds'); const [sel, setSel] = useState<string | null>(null); const [create, setCreate] = useState(false);
  const list: any[] = funds?.data ?? (Array.isArray(funds) ? funds : []); const current = sel ?? list[0]?.id;
  const createM = useAction((v: any) => post('/petty-cash/funds', { ...v, float_amount: Number(v.float_amount), department_id: v.department_id || null, account_id: v.account_id || undefined }), { success: 'Fund created', invalidate: ['/petty-cash'], onSuccess: (r: any) => { setCreate(false); refetch(); setSel(r?.id); } });
  return <div className="space-y-4">
    <PageHeader title="Petty cash" subtitle="Imprest funds per custodian: disbursements against approved expenses, top-ups from bank, physical counts with variance posting." actions={can('petty_cash.reconcile', 'settings.edit') && <Button onClick={() => setCreate(true)}><Plus />New fund</Button>} />
    {list.length === 0 ? <div className="rounded-lg border border-dashed p-10 text-center text-muted-foreground"><Wallet className="mx-auto mb-2 h-8 w-8" />No petty cash funds yet.</div> : <div className="flex flex-wrap gap-2">{list.map((f) => <button key={f.id} type="button" onClick={() => setSel(f.id)} className={`rounded-lg border px-3 py-2 text-left text-sm ${current === f.id ? 'border-primary bg-primary/5' : 'bg-card hover:bg-accent'}`}><div className="font-medium">{f.name}{!f.is_active && <Badge tone="muted" className="ml-1">inactive</Badge>}</div><div className="text-xs text-muted-foreground">{f.custodian_name} · {fmtMoney(f.balance, currency)} / {fmtMoney(f.float_amount, currency)}</div></button>)}</div>}
    {current && <FundPanel key={current} fundId={current} />}
    <FormDialog open={create} onOpenChange={setCreate} title="New petty cash fund" fields={fundFields} onSubmit={(v) => createM.mutateAsync(v)} />
  </div>;
}
