'use client';
import React, { useEffect, useState } from 'react';
import { Save, Hash } from 'lucide-react';
import { put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Input, Label, Textarea, NativeSelect } from '@/components/ui/input';
import { Switch } from '@/components/ui/misc';
import { Badge } from '@/components/ui/badge';
import { FormDialog } from '@/components/shared/form';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { fmtDateTime, titleCase } from '@/lib/utils';

type Opt = string | { value: string; label: string };
type Def = { key: string; label: string; type: 'text' | 'time' | 'number' | 'bool' | 'textarea' | 'select'; options?: Opt[]; help?: string };
const PAPER_OPTS: Opt[] = [{ value: 'a4', label: 'A4 sheet' }, { value: 'a5', label: 'A5 sheet' }, { value: 'letter', label: 'US Letter' }, { value: 'thermal80', label: '80 mm thermal roll' }, { value: 'thermal58', label: '58 mm thermal roll' }];
const GROUPS: { title: string; items: Def[] }[] = [
  { title: 'Front office', items: [{ key: 'hotel.checkin_time', label: 'Standard check-in time', type: 'time' }, { key: 'hotel.checkout_time', label: 'Standard check-out time', type: 'time' }, { key: 'hotel.late_checkout_fee_percent', label: 'Late check-out fee (% of nightly rate)', type: 'number' }, { key: 'hotel.default_deposit_percent', label: 'Default reservation deposit (%)', type: 'number' }, { key: 'hotel.high_balance_threshold', label: 'High-balance folio alert threshold', type: 'number', help: 'Flagged on the night audit checklist.' }, { key: 'hotel.cancellation_policy', label: 'Cancellation policy text', type: 'textarea', help: 'Printed on confirmations.' }, { key: 'hotel.allow_overbooking', label: 'Allow overbooking (with permission)', type: 'bool' }] },
  { title: 'Point of sale', items: [{ key: 'pos.require_shift', label: 'Require an open cashier shift to take payments', type: 'bool' }, { key: 'pos.auto_send_kitchen', label: 'Auto-send items to kitchen on order save', type: 'bool' }, { key: 'pos.service_charge_percent', label: 'Service charge (%)', type: 'number' }, { key: 'pos.max_discount_percent', label: 'Max line discount without approval (%)', type: 'number' }] },
  { title: 'Inventory & procurement', items: [{ key: 'inventory.grn_auto_post', label: 'Post GRN to stock & ledger on completion', type: 'bool' }, { key: 'inventory.costing_method', label: 'Costing method', type: 'select', options: ['WEIGHTED_AVERAGE', 'FIFO'] }, { key: 'purchases.price_tolerance_percent', label: 'Invoice vs PO price tolerance (%)', type: 'number' }, { key: 'notifications.low_stock', label: 'Low-stock notifications', type: 'bool' }] },
  { title: 'Printing', items: [{ key: 'print.receipt_paper', label: 'Receipts & bills print on', type: 'select', options: PAPER_OPTS, help: 'Each till can override this from the print button menu.' }, { key: 'print.kitchen_paper', label: 'Kitchen / bar tickets print on', type: 'select', options: PAPER_OPTS }, { key: 'print.document_paper', label: 'Folios, confirmations, POs, BEOs print on', type: 'select', options: PAPER_OPTS }, { key: 'print.receipt_copies', label: 'Receipt copies', type: 'number' }, { key: 'print.kot_on_send', label: 'Print kitchen tickets automatically when an order is sent', type: 'bool' }, { key: 'print.show_logo', label: 'Print the property logo on documents', type: 'bool' }, { key: 'print.receipt_footer', label: 'Receipt footer text', type: 'textarea', help: 'e.g. thank-you note, PIN / VAT number, return policy.' }, { key: 'print.document_footer', label: 'Document footer text', type: 'textarea', help: 'Printed on folios, confirmations and purchase orders.' }] },
  { title: 'Finance', items: [{ key: 'finance.fiscal_integration', label: 'Fiscal / e-invoicing integration', type: 'select', options: ['NONE', 'KRA_ETIMS', 'CUSTOM'] }, { key: 'finance.cash_variance_tolerance', label: 'Cash variance auto-approve tolerance', type: 'number' }, { key: 'finance.lock_days_after_audit', label: 'Lock postings older than (days)', type: 'number' }] },
];
function Numbering() {
  const { can } = useAuth(); const { data, refetch } = useApi<any>('/settings/numbering'); const [edit, setEdit] = useState<any>(null);
  const save = useAction((v: any) => put('/settings/numbering', { doc_type: edit.doc_type, prefix: v.prefix, padding: Number(v.padding), next_value: Number(v.next_value), reset_yearly: !!v.reset_yearly }), { success: 'Numbering updated', onSuccess: () => { setEdit(null); refetch(); } });
  const rows: any[] = data?.data ?? [];
  return <Section title="Document numbering" description="Prefixes and counters per document type. Property-specific rows override the global default."><table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left">Document</th><th className="p-2 text-left">Prefix</th><th className="p-2 text-left">Example</th><th className="p-2 text-right">Next</th><th className="p-2">Yearly reset</th><th className="p-2">Scope</th><th /></tr></thead><tbody className="divide-y">{rows.map((r) => <tr key={r.id}><td className="p-2 font-medium">{titleCase(r.doc_type)}</td><td className="p-2 font-mono">{r.prefix}</td><td className="p-2 font-mono text-xs text-muted-foreground">{r.prefix}-{r.reset_yearly ? `${r.current_year ?? new Date().getFullYear()}-` : ''}{String(r.next_value).padStart(r.padding, '0')}</td><td className="p-2 text-right tabular">{r.next_value}</td><td className="p-2 text-center">{r.reset_yearly ? '✓' : ''}</td><td className="p-2 text-center">{r.property_id ? <Badge tone="info">property</Badge> : <Badge tone="muted">global</Badge>}</td><td className="p-2 text-right">{can('settings.edit') && <Button size="sm" variant="ghost" onClick={() => setEdit(r)}>Edit</Button>}</td></tr>)}</tbody></table>
    <FormDialog open={!!edit} onOpenChange={(o) => !o && setEdit(null)} title={edit ? `Numbering: ${titleCase(edit.doc_type)}` : ''} description="Changing the counter below an already-issued number will cause duplicates — only increase it." fields={[{ name: 'prefix', label: 'Prefix', required: true }, { name: 'padding', label: 'Digits', type: 'number', required: true }, { name: 'next_value', label: 'Next number', type: 'number', required: true }, { name: 'reset_yearly', label: 'Reset every year (adds the year)', type: 'switch' }]} initial={edit ?? undefined} onSubmit={(v) => save.mutateAsync(v)} /></Section>;
}
export default function GeneralSettingsPage() {
  const { can, property } = useAuth(); const { data, refetch } = useApi<any>('/settings'); const [vals, setVals] = useState<Record<string, any>>({}); const [dirty, setDirty] = useState<Set<string>>(new Set()); const [scope, setScope] = useState<'PROPERTY' | 'GLOBAL'>('PROPERTY');
  useEffect(() => { if (data?.settings) { setVals(data.settings); setDirty(new Set()); } }, [data]);
  const rowsByKey: Record<string, any[]> = (data?.rows ?? []).reduce((m: any, r: any) => { (m[r.key] ??= []).push(r); return m; }, {});
  const save = useAction(async () => { for (const k of Array.from(dirty)) await put('/settings', { key: k, value: vals[k], scope }); }, { success: 'Settings saved', invalidate: ['/settings'], onSuccess: () => refetch() });
  const set = (k: string, v: any) => { setVals({ ...vals, [k]: v }); setDirty(new Set(dirty).add(k)); };
  return <div className="space-y-4">
    <PageHeader title="Hotel settings" subtitle={`Configuration for ${property?.name ?? 'this property'}. Values saved at property scope override the global defaults.`} crumbs={[{ label: 'Settings', href: '/settings' }, { label: 'General' }]} actions={can('settings.edit') && <div className="flex items-center gap-2"><NativeSelect value={scope} onChange={(e) => setScope(e.target.value as any)} className="w-44"><option value="PROPERTY">Save for this property</option><option value="GLOBAL">Save as global default</option></NativeSelect><Button loading={save.isPending} disabled={dirty.size === 0} onClick={() => save.mutate(undefined as any)}><Save />Save {dirty.size > 0 && `(${dirty.size})`}</Button></div>} />
    <Tabs defaultValue="settings"><TabsList><TabsTrigger value="settings">Settings</TabsTrigger><TabsTrigger value="numbering"><Hash className="mr-1 h-3.5 w-3.5" />Numbering</TabsTrigger></TabsList>
      <TabsContent value="settings" className="grid gap-4 lg:grid-cols-2">{GROUPS.map((g) => <Section key={g.title} title={g.title}><div className="space-y-3">{g.items.map((d) => { const v = vals[d.key]; const src = rowsByKey[d.key]?.find((r: any) => r.property_id) ? 'property' : rowsByKey[d.key] ? 'global' : null; return <div key={d.key} className="grid grid-cols-[1fr_auto] items-center gap-3"><div><Label>{d.label}</Label>{d.help && <div className="text-xs text-muted-foreground">{d.help}</div>}<div className="text-[10px] text-muted-foreground">{d.key}{src && <Badge tone={src === 'property' ? 'info' : 'muted'} className="ml-1">{src}</Badge>}{dirty.has(d.key) && <Badge tone="warning" className="ml-1">unsaved</Badge>}</div></div><div className="w-56">{d.type === 'bool' ? <Switch checked={!!v} onCheckedChange={(c) => set(d.key, c)} disabled={!can('settings.edit')} /> : d.type === 'textarea' ? <Textarea rows={3} value={v ?? ''} onChange={(e) => set(d.key, e.target.value)} disabled={!can('settings.edit')} /> : d.type === 'select' ? <NativeSelect value={v ?? ''} onChange={(e) => set(d.key, e.target.value)} disabled={!can('settings.edit')}><option value="">—</option>{d.options!.map((o) => typeof o === 'string' ? <option key={o} value={o}>{titleCase(o)}</option> : <option key={o.value} value={o.value}>{o.label}</option>)}</NativeSelect> : <Input type={d.type === 'number' ? 'number' : d.type} value={v ?? ''} onChange={(e) => set(d.key, d.type === 'number' ? (e.target.value === '' ? null : Number(e.target.value)) : e.target.value)} disabled={!can('settings.edit')} />}</div></div>; })}</div></Section>)}
        <Section title="All stored keys" className="lg:col-span-2" description="Raw view of every setting row, including ones not surfaced above."><table className="w-full text-xs"><thead className="uppercase text-muted-foreground"><tr><th className="p-1 text-left">Key</th><th className="p-1 text-left">Value</th><th className="p-1 text-left">Scope</th><th className="p-1 text-left">Updated</th></tr></thead><tbody className="divide-y">{(data?.rows ?? []).map((r: any, i: number) => <tr key={i}><td className="p-1 font-mono">{r.key}</td><td className="p-1 max-w-md truncate">{typeof r.value === 'object' ? JSON.stringify(r.value) : String(r.value)}</td><td className="p-1">{r.property_id ? 'property' : 'global'}</td><td className="p-1">{fmtDateTime(r.updated_at)}</td></tr>)}</tbody></table></Section>
      </TabsContent>
      <TabsContent value="numbering"><Numbering /></TabsContent>
    </Tabs>
  </div>;
}
