'use client';
import React, { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, LogIn, LogOut, Trash2, CalendarPlus } from 'lucide-react';
import { post, del } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Modal } from '@/components/ui/dialog';
import { Input, Label, NativeSelect } from '@/components/ui/input';
import { LookupSelect } from '@/components/shared/form';
import { today, addDays, fmtDate, fmtTime } from '@/lib/utils';
import { toast } from 'sonner';

/** Weekly roster grid (employees × days). Click a cell to assign a shift template; click a shift chip to clock in/out or remove. */
export default function RosterPage() {
  const { can } = useAuth(); const [from, setFrom] = useState(() => { const d = new Date(); const dow = (d.getDay() + 6) % 7; return addDays(today(), -dow); }); const to = addDays(from, 6);
  const [dept, setDept] = useState(''); const days = useMemo(() => Array.from({ length: 7 }, (_, i) => addDays(from, i)), [from]);
  const { data, refetch } = useApi<any>('/staff-shifts/roster', { from, to, department_id: dept || undefined });
  const { data: templates } = useApi<any>('/shift-templates', { pageSize: 100, is_active: true });
  const [cell, setCell] = useState<{ employee: any; date: string } | null>(null); const [tpl, setTpl] = useState(''); const [outlet, setOutlet] = useState(''); const [bulk, setBulk] = useState(false); const [chip, setChip] = useState<any>(null);
  const assign = useAction((assignments: any[]) => post('/staff-shifts', { assignments }), { success: 'Roster updated', onSuccess: () => { setCell(null); setBulk(false); refetch(); } });
  const clock = useAction(({ id, action }: any) => post(`/staff-shifts/${id}/clock`, { action }), { success: 'Attendance recorded', onSuccess: () => { setChip(null); refetch(); } });
  const remove = useAction((id: string) => del(`/staff-shifts/${id}`), { success: 'Shift removed', onSuccess: () => { setChip(null); refetch(); } });
  const tpls: any[] = templates?.data ?? []; const employees: any[] = data?.employees ?? [];
  const byDept = useMemo(() => { const m = new Map<string, any[]>(); for (const e of employees) { const k = e.department_name ?? 'No department'; if (!m.has(k)) m.set(k, []); m.get(k)!.push(e); } return [...m.entries()]; }, [employees]);
  return <div className="space-y-4">
    <PageHeader title="Staff roster" subtitle="Weekly shift plan per department with clock in/out attendance." actions={can('employees.manage') && <Button onClick={() => { setTpl(tpls[0]?.id ?? ''); setBulk(true); }}><CalendarPlus />Bulk assign</Button>} />
    <div className="flex flex-wrap items-center gap-2"><Button size="icon" variant="outline" onClick={() => setFrom(addDays(from, -7))}><ChevronLeft /></Button><span className="text-sm font-medium">{fmtDate(from)} – {fmtDate(to)}</span><Button size="icon" variant="outline" onClick={() => setFrom(addDays(from, 7))}><ChevronRight /></Button><Button size="sm" variant="ghost" onClick={() => { const d = new Date(); setFrom(addDays(today(), -((d.getDay() + 6) % 7))); }}>This week</Button><div className="w-56"><LookupSelect source="/departments" value={dept} onChange={setDept} placeholder="All departments" /></div></div>
    <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="p-2 text-left w-48">Employee</th>{days.map((d) => <th key={d} className={`p-2 text-left ${d === today() ? 'text-primary' : ''}`}>{new Date(d + 'T00:00:00').toLocaleDateString('en-GB', { weekday: 'short' })} <span className="font-normal">{d.slice(5)}</span></th>)}</tr></thead>
      <tbody>{byDept.map(([dname, list]) => <React.Fragment key={dname}><tr className="bg-muted/30"><td colSpan={8} className="px-2 py-1 text-xs font-semibold uppercase text-muted-foreground">{dname}</td></tr>{list.map((e: any) => <tr key={e.employee_id} className="border-t"><td className="p-2"><div className="font-medium">{e.employee_name}</div><div className="text-xs text-muted-foreground">{e.position}</div></td>{days.map((d) => { const shifts = (e.shifts ?? []).filter((s: any) => String(s.date).slice(0, 10) === d); return <td key={d} className="p-1 align-top" onClick={() => can('employees.manage') && shifts.length === 0 && (setTpl(tpls[0]?.id ?? ''), setCell({ employee: e, date: d }))}><div className="min-h-[3rem] rounded hover:bg-accent/60 cursor-pointer p-1 space-y-1">{shifts.map((s: any) => <button type="button" key={s.id} onClick={(ev) => { ev.stopPropagation(); setChip({ ...s, employee: e }); }} className={`block w-full rounded px-1.5 py-1 text-left text-xs ${s.clock_out ? 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300' : s.clock_in ? 'bg-amber-500/20 text-amber-800 dark:text-amber-200' : 'bg-primary/10 text-primary'}`}><div className="font-medium">{s.shift}</div><div>{String(s.start).slice(0, 5)}–{String(s.end).slice(0, 5)}</div>{s.clock_in && <div className="opacity-80">in {fmtTime(s.clock_in)}{s.clock_out && ` · out ${fmtTime(s.clock_out)}`}</div>}</button>)}{shifts.length === 0 && can('employees.manage') && <div className="text-center text-xs text-muted-foreground/40">+</div>}</div></td>; })}</tr>)}</React.Fragment>)}{employees.length === 0 && <tr><td colSpan={8} className="p-8 text-center text-muted-foreground">No active employees{dept ? ' in this department' : ''}. Add staff under HR → Employees.</td></tr>}</tbody></table></div>
    <Modal open={!!cell} onOpenChange={(o) => !o && setCell(null)} title={cell ? `Assign shift · ${cell.employee.employee_name} · ${fmtDate(cell.date)}` : ''} size="sm"><div className="space-y-3"><div className="flex flex-col gap-1"><Label>Shift template</Label><NativeSelect value={tpl} onChange={(e) => setTpl(e.target.value)}>{tpls.map((t) => <option key={t.id} value={t.id}>{t.name} ({String(t.start_time).slice(0, 5)}–{String(t.end_time).slice(0, 5)})</option>)}</NativeSelect></div><div className="flex flex-col gap-1"><Label>Outlet (optional)</Label><LookupSelect source="/outlets" value={outlet} onChange={setOutlet} placeholder="None" /></div><div className="flex justify-end"><Button loading={assign.isPending} disabled={!tpl} onClick={() => assign.mutate([{ shift_template_id: tpl, employee_id: cell!.employee.employee_id, shift_date: cell!.date, outlet_id: outlet || null }])}>Assign</Button></div></div></Modal>
    <BulkAssign open={bulk} onOpenChange={setBulk} employees={employees} templates={tpls} days={days} onSubmit={(a) => assign.mutate(a)} pending={assign.isPending} />
    <Modal open={!!chip} onOpenChange={(o) => !o && setChip(null)} title={chip ? `${chip.employee.employee_name} · ${chip.shift} · ${fmtDate(chip.date)}` : ''} size="sm">{chip && <div className="space-y-3 text-sm"><div>Planned {String(chip.start).slice(0, 5)}–{String(chip.end).slice(0, 5)}{chip.clock_in && <> · clocked in {fmtTime(chip.clock_in)}</>}{chip.clock_out && <> · out {fmtTime(chip.clock_out)}</>}</div><div className="flex flex-wrap gap-2">{!chip.clock_in && <Button onClick={() => clock.mutate({ id: chip.id, action: 'IN' })}><LogIn />Clock in</Button>}{chip.clock_in && !chip.clock_out && <Button onClick={() => clock.mutate({ id: chip.id, action: 'OUT' })}><LogOut />Clock out</Button>}{can('employees.manage') && !chip.clock_in && <Button variant="destructive" onClick={() => remove.mutate(chip.id)}><Trash2 />Remove</Button>}</div></div>}</Modal>
  </div>;
}
function BulkAssign({ open, onOpenChange, employees, templates, days, onSubmit, pending }: { open: boolean; onOpenChange: (o: boolean) => void; employees: any[]; templates: any[]; days: string[]; onSubmit: (a: any[]) => void; pending: boolean }) {
  const [tpl, setTpl] = useState(''); const [sel, setSel] = useState<Set<string>>(new Set()); const [dsel, setDsel] = useState<Set<string>>(new Set(days.slice(0, 5)));
  const toggle = (set: Set<string>, v: string, fn: (s: Set<string>) => void) => { const n = new Set(set); n.has(v) ? n.delete(v) : n.add(v); fn(n); };
  const t = tpl || templates[0]?.id;
  return <Modal open={open} onOpenChange={onOpenChange} title="Bulk assign shifts" size="md"><div className="space-y-3">
    <div className="flex flex-col gap-1"><Label>Shift template</Label><NativeSelect value={t ?? ''} onChange={(e) => setTpl(e.target.value)}>{templates.map((x) => <option key={x.id} value={x.id}>{x.name} ({String(x.start_time).slice(0, 5)}–{String(x.end_time).slice(0, 5)})</option>)}</NativeSelect></div>
    <div><Label>Days</Label><div className="mt-1 flex flex-wrap gap-1">{days.map((d) => <Button key={d} size="sm" variant={dsel.has(d) ? 'default' : 'outline'} onClick={() => toggle(dsel, d, setDsel)}>{new Date(d + 'T00:00:00').toLocaleDateString('en-GB', { weekday: 'short' })} {d.slice(8)}</Button>)}</div></div>
    <div><div className="flex justify-between"><Label>Employees ({sel.size})</Label><Button size="sm" variant="ghost" onClick={() => setSel(sel.size === employees.length ? new Set() : new Set(employees.map((e) => e.employee_id)))}>{sel.size === employees.length ? 'Clear' : 'Select all'}</Button></div><div className="mt-1 max-h-64 overflow-auto rounded border divide-y">{employees.map((e) => <label key={e.employee_id} className="flex items-center gap-2 px-2 py-1.5 text-sm hover:bg-accent"><input type="checkbox" checked={sel.has(e.employee_id)} onChange={() => toggle(sel, e.employee_id, setSel)} /><span className="flex-1">{e.employee_name}</span><span className="text-xs text-muted-foreground">{e.department_name}</span></label>)}</div></div>
    <div className="flex justify-end"><Button loading={pending} disabled={!t || sel.size === 0 || dsel.size === 0} onClick={() => { const a: any[] = []; for (const emp of sel) for (const d of dsel) a.push({ shift_template_id: t, employee_id: emp, shift_date: d, outlet_id: null }); if (a.length > 200) return toast.error('Too many assignments at once (max 200)'); onSubmit(a); }}>Assign {sel.size * dsel.size} shifts</Button></div>
  </div></Modal>;
}
