'use client';
import React, { useState, useRef, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { Ticket, QrCode, UserPlus, Plus, Radio, Lock, XCircle, CheckCircle2 } from 'lucide-react';
import { post, put } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section, KV } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { StatusBadge, Badge } from '@/components/ui/badge';
import { Spinner } from '@/components/ui/misc';
import { FormDialog, ConfirmDialog } from '@/components/shared/form';
import { Modal } from '@/components/ui/dialog';
import { Input, Label } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { DataTable } from '@/components/shared/data-table';
import { fmtDate, fmtDateTime, fmtMoney, titleCase } from '@/lib/utils';
import { AuditTrail } from '@/components/shared/audit-trail';
import { PaymentLineFields, type PaymentLine } from '@/components/pms/payment-fields';
import { toast } from 'sonner';

export default function ClubEventDetail() {
  const { id } = useParams<{ id: string }>(); const { can, currency } = useAuth();
  const { data: ce, isLoading, refetch } = useApi<any>(`/club-events/${id}`);
  const [status, setStatus] = useState<string | null>(null); const [tt, setTt] = useState(false); const [gl, setGl] = useState(false); const [sell, setSell] = useState(false); const [scan, setScan] = useState(false);
  const [sale, setSale] = useState<any>({ ticket_type_id: '', quantity: 1, holder_name: '', holder_phone: '', complimentary: false }); const [pay, setPay] = useState<PaymentLine>({ amount: '' }); const [sold, setSold] = useState<any>(null);
  const [code, setCode] = useState(''); const [last, setLast] = useState<any>(null); const codeRef = useRef<HTMLInputElement>(null);
  const inv = [`/club-events`];
  const statusM = useAction(() => post(`/club-events/${id}/status`, { status }), { success: 'Status updated', invalidate: inv, onSuccess: () => { setStatus(null); refetch(); } });
  const ttM = useAction((v: any) => post(`/club-events/${id}/ticket-types`, v), { success: 'Ticket type added', onSuccess: () => refetch() });
  const glM = useAction((v: any) => post(`/club-events/${id}/guest-list`, v), { success: 'Added to guest list', onSuccess: () => refetch() });
  const arriveM = useAction((entryId: string) => post(`/club-events/${id}/guest-list/${entryId}/arrive`), { success: 'Marked arrived', onSuccess: () => refetch() });
  const sellM = useAction(() => post(`/club-events/${id}/tickets`, { ...sale, quantity: Number(sale.quantity), payment_method_id: sale.complimentary ? undefined : pay.payment_method_id, reference: pay.reference }, true), { success: 'Ticket sold', invalidate: [...inv, '/payments'], onSuccess: (t: any) => { setSold(t); refetch(); } });
  const checkM = useAction((c: string) => post(`/club-events/${id}/check-in`, { code: c }), { onSuccess: (r: any) => { setLast({ ok: true, ...r }); toast.success(`Welcome ${r.ticket?.holder_name ?? ''} · ${r.ticket?.ticket_type ?? ''} × ${r.ticket?.quantity}`); setCode(''); refetch(); }, onError: (e: any) => { setLast({ ok: false, message: e.message }); setCode(''); } });
  const cancelT = useAction((tid: string) => post(`/club-events/${id}/tickets/${tid}/cancel`, { reason: 'Cancelled at door' }), { success: 'Ticket cancelled', onSuccess: () => refetch() });
  useEffect(() => { if (scan) setTimeout(() => codeRef.current?.focus(), 50); }, [scan]);
  if (isLoading || !ce) return <Spinner />;
  const type = (ce.ticket_types ?? []).find((t: any) => t.id === sale.ticket_type_id); const saleTotal = type ? Number(type.price) * Number(sale.quantity || 0) : 0;
  const next: Record<string, string[]> = { SCHEDULED: ['LIVE', 'CANCELLED'], LIVE: ['CLOSED'], CLOSED: [], CANCELLED: [] };
  return <div className="space-y-4">
    <PageHeader crumbs={[{ label: 'Club nights', href: '/clubs' }, { label: ce.name }]} title={<span className="flex items-center gap-2">{ce.name} <StatusBadge status={ce.status} /></span>} subtitle={`${ce.outlet_name} · ${fmtDate(ce.event_date)} ${String(ce.start_time).slice(0, 5)}–${String(ce.end_time).slice(0, 5)} · capacity ${ce.capacity ?? '∞'}`}
      actions={<>
        {ce.status !== 'CANCELLED' && ce.status !== 'CLOSED' && can('clubs.sell_tickets') && <Button onClick={() => { setSold(null); setSell(true); }}><Ticket />Sell ticket</Button>}
        {ce.status === 'LIVE' && can('clubs.sell_tickets', 'clubs.manage') && <Button variant="outline" onClick={() => setScan(true)}><QrCode />Door check-in</Button>}
        {can('clubs.manage') && next[ce.status]?.map((s) => <Button key={s} variant={s === 'CANCELLED' ? 'destructive' : 'outline'} onClick={() => setStatus(s)}>{s === 'LIVE' ? <Radio /> : s === 'CLOSED' ? <Lock /> : <XCircle />}{titleCase(s)}</Button>)}
      </>} />
    <div className="grid gap-3 md:grid-cols-4">{[['Tickets sold', ce.tickets_sold ?? 0], ['Checked in', ce.checked_in ?? 0], ['Guest list', ce.guest_list_count ?? 0], ['Ticket revenue', fmtMoney(ce.ticket_revenue, currency)]].map(([k, v]) => <div key={String(k)} className="rounded-lg border bg-card p-3"><div className="text-xs text-muted-foreground">{k}</div><div className="text-2xl font-semibold tabular">{v as any}</div></div>)}</div>
    <Tabs defaultValue="tickets"><TabsList><TabsTrigger value="tickets">Ticket types & sales</TabsTrigger><TabsTrigger value="guestlist">Guest list</TabsTrigger><TabsTrigger value="details">Details</TabsTrigger></TabsList>
      <TabsContent value="tickets" className="space-y-4">
        <Section title="Ticket types" actions={can('clubs.manage') && ce.status !== 'CLOSED' && <Button size="sm" variant="outline" onClick={() => setTt(true)}><Plus />Type</Button>}>
          <div className="grid gap-2 md:grid-cols-3">{(ce.ticket_types ?? []).map((t: any) => { const s = (ce.sales_by_type ?? []).find((x: any) => x.name === t.name); return <div key={t.id} className="rounded-lg border p-3"><div className="flex justify-between"><span className="font-medium">{t.name}</span><span className="tabular font-semibold">{fmtMoney(t.price, currency)}</span></div><div className="text-xs text-muted-foreground">{t.includes || 'Entry'}</div><div className="mt-2 text-sm">{t.quantity_sold} sold{t.quantity_available != null && ` of ${t.quantity_available}`} · {s?.pax ?? 0} pax · {fmtMoney(s?.revenue ?? 0, currency)}</div>{t.quantity_available != null && <div className="mt-1 h-1.5 rounded bg-muted"><div className="h-1.5 rounded bg-primary" style={{ width: `${Math.min(100, (t.quantity_sold / Math.max(1, t.quantity_available)) * 100)}%` }} /></div>}</div>; })}</div>
        </Section>
        <Section title="Tickets"><DataTable path={`/club-events/${id}/tickets`} defaultSort="created_at" defaultOrder="desc" pageSize={25} columns={[{ key: 'number', label: 'No.' }, { key: 'ticket_type', label: 'Type' }, { key: 'holder_name', label: 'Holder', render: (r) => <div>{r.holder_name ?? '—'}<div className="text-xs text-muted-foreground">{r.holder_phone}</div></div> }, { key: 'quantity', label: 'Pax', type: 'number', decimals: 0 }, { key: 'amount', label: 'Amount', type: 'money' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }, { key: 'checked_in_at', label: 'Checked in', type: 'datetime' }, { key: 'sold_by_name', label: 'Sold by' }, { key: 'created_at', label: 'Sold at', type: 'datetime' }]}
          rowActions={(r) => <div className="flex gap-1">{r.status === 'SOLD' && can('clubs.sell_tickets', 'clubs.manage') && ce.status === 'LIVE' && <Button size="sm" variant="outline" onClick={() => checkM.mutate(r.qr_code ?? r.number)}>Check in</Button>}{r.status === 'SOLD' && can('clubs.manage') && <Button size="sm" variant="ghost" onClick={() => cancelT.mutate(r.id)}>Cancel</Button>}</div>} /></Section>
      </TabsContent>
      <TabsContent value="guestlist"><Section title="Guest list & table reservations" actions={can('clubs.manage') && <Button size="sm" onClick={() => setGl(true)}><UserPlus />Add guest</Button>}>
        <table className="w-full text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="text-left py-1">Guest</th><th className="text-left">Phone</th><th className="text-right">+1s</th><th className="text-left">Table</th><th className="text-left">Notes</th><th className="text-left">Arrived</th><th /></tr></thead><tbody className="divide-y">{(ce.guest_list ?? []).map((g: any) => <tr key={g.id} className={g.arrived_at ? 'text-muted-foreground' : ''}><td className="py-1.5">{g.is_vip && <Badge tone="warning" className="mr-1">VIP</Badge>}{g.name}</td><td>{g.phone}</td><td className="text-right tabular">{g.plus_ones}</td><td>{g.table_number ?? '—'}</td><td className="text-xs">{g.notes}</td><td>{g.arrived_at ? <span className="text-emerald-600 flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5" />{fmtDateTime(g.arrived_at)}</span> : '—'}</td><td className="text-right">{!g.arrived_at && can('clubs.sell_tickets', 'clubs.manage') && <Button size="sm" variant="outline" onClick={() => arriveM.mutate(g.id)}>Arrived</Button>}</td></tr>)}{(ce.guest_list ?? []).length === 0 && <tr><td colSpan={7} className="py-6 text-center text-muted-foreground">No guest list entries.</td></tr>}</tbody></table></Section></TabsContent>
      <TabsContent value="details" className="space-y-4"><Section title="Event"><KV items={[['Club', ce.outlet_name], ['Date', fmtDate(ce.event_date)], ['Hours', `${String(ce.start_time).slice(0, 5)} – ${String(ce.end_time).slice(0, 5)}`], ['Capacity', ce.capacity ?? 'Unlimited'], ['Cover charge', fmtMoney(ce.cover_charge, currency)], ['Promotions', ce.promotions ?? '—'], ['Description', ce.description ?? '—']]} /></Section><AuditTrail entity="club_event" entityId={id} /></TabsContent>
    </Tabs>
    <ConfirmDialog open={!!status} onOpenChange={(o) => !o && setStatus(null)} title={`Set event ${titleCase(status ?? '')}?`} description={status === 'LIVE' ? 'Opens doors: ticket check-in and door sales become active.' : status === 'CLOSED' ? 'Closes the night; no more sales or check-ins.' : 'Cancels the event.'} destructive={status === 'CANCELLED'} onConfirm={() => statusM.mutateAsync(undefined as any)} />
    <FormDialog open={tt} onOpenChange={setTt} title="Add ticket type" size="sm" fields={[{ name: 'name', label: 'Name', required: true }, { name: 'price', label: 'Price', type: 'money', required: true }, { name: 'quantity_available', label: 'Quantity (blank = unlimited)', type: 'number' }, { name: 'includes', label: 'Includes', col: 2 }]} onSubmit={(v) => ttM.mutateAsync(v)} />
    <FormDialog open={gl} onOpenChange={setGl} title="Add to guest list" size="sm" initial={{ plus_ones: 0 }} fields={[{ name: 'name', label: 'Name', required: true }, { name: 'phone', label: 'Phone' }, { name: 'plus_ones', label: 'Plus ones', type: 'number' }, { name: 'table_id', label: 'Reserved table', type: 'lookup', source: '/tables', sourceQuery: { outlet_id: ce.outlet_id }, sourceLabel: 'number' }, { name: 'is_vip', label: 'VIP', type: 'switch' }, { name: 'notes', label: 'Notes', type: 'textarea', col: 2 }]} onSubmit={(v) => glM.mutateAsync(v)} />
    <Modal open={sell} onOpenChange={setSell} title={sold ? 'Ticket issued' : 'Sell ticket'} size="md">{sold ? <div className="space-y-3 text-center"><div className="text-3xl font-bold tracking-widest">{sold.number}</div><div className="mx-auto w-fit rounded bg-white p-3"><QRSvg value={sold.qr_code} /></div><div className="text-xs text-muted-foreground font-mono break-all">{sold.qr_code}</div><KV cols={2} items={[['Holder', sold.holder_name ?? 'Walk-in'], ['Pax', sold.quantity], ['Amount', fmtMoney(sold.amount, currency)], ['Status', sold.status]]} /><div className="flex justify-center gap-2"><Button variant="outline" onClick={() => window.print()}>Print</Button><Button onClick={() => { setSold(null); setSale({ ...sale, holder_name: '', holder_phone: '' }); }}>Sell another</Button></div></div> : <div className="space-y-3">
      <div className="grid grid-cols-2 gap-2">{(ce.ticket_types ?? []).map((t: any) => { const left = t.quantity_available == null ? null : t.quantity_available - t.quantity_sold; return <button type="button" key={t.id} disabled={left !== null && left <= 0} onClick={() => setSale({ ...sale, ticket_type_id: t.id })} className={`rounded-lg border p-3 text-left disabled:opacity-40 ${sale.ticket_type_id === t.id ? 'border-primary ring-1 ring-primary bg-primary/5' : ''}`}><div className="flex justify-between"><span className="font-medium">{t.name}</span><span className="tabular">{fmtMoney(t.price, currency)}</span></div><div className="text-xs text-muted-foreground">{t.includes || 'Entry'}{left !== null && ` · ${left} left`}</div></button>; })}</div>
      <div className="grid grid-cols-3 gap-3"><div className="flex flex-col gap-1"><Label>Quantity</Label><Input type="number" min={1} value={sale.quantity} onChange={(e) => setSale({ ...sale, quantity: e.target.value })} /></div><div className="flex flex-col gap-1"><Label>Holder name</Label><Input value={sale.holder_name} onChange={(e) => setSale({ ...sale, holder_name: e.target.value })} /></div><div className="flex flex-col gap-1"><Label>Phone</Label><Input value={sale.holder_phone} onChange={(e) => setSale({ ...sale, holder_phone: e.target.value })} /></div></div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sale.complimentary} onChange={(e) => setSale({ ...sale, complimentary: e.target.checked })} disabled={!can('pos.discount')} /> Complimentary (no payment)</label>
      {!sale.complimentary && <PaymentLineFields value={{ ...pay, amount: String(saleTotal) }} onChange={setPay} showAmount={false} />}
      <div className="flex items-center justify-between border-t pt-3"><span className="text-lg font-semibold">Total {fmtMoney(sale.complimentary ? 0 : saleTotal, currency)}</span><Button loading={sellM.isPending} disabled={!sale.ticket_type_id || (!sale.complimentary && !pay.payment_method_id)} onClick={() => sellM.mutate(undefined as any)}><Ticket />Issue ticket</Button></div></div>}</Modal>
    <Modal open={scan} onOpenChange={setScan} title="Door check-in" size="sm"><div className="space-y-3"><p className="text-xs text-muted-foreground">Scan the QR code or type the ticket number and press Enter. A handheld scanner acts as a keyboard.</p><form onSubmit={(e) => { e.preventDefault(); if (code.trim()) checkM.mutate(code.trim()); }}><Input ref={codeRef} autoFocus value={code} onChange={(e) => setCode(e.target.value)} placeholder="HMS-TKT:… or TKT-0001" className="h-12 text-lg font-mono" /></form>
      {last && <div className={`rounded-lg border p-4 text-center ${last.ok ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/40' : 'border-destructive bg-destructive/10'}`}>{last.ok ? <><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><div className="text-lg font-semibold">Admit {last.ticket?.quantity} · {last.ticket?.ticket_type}</div><div className="text-sm">{last.ticket?.holder_name ?? 'Walk-in'} · {last.ticket?.number}</div></> : <><XCircle className="mx-auto h-10 w-10 text-destructive" /><div className="font-semibold">Denied</div><div className="text-sm">{last.message}</div></>}</div>}
      <div className="text-center text-sm text-muted-foreground">{ce.checked_in ?? 0} / {ce.tickets_sold ?? 0} checked in</div></div></Modal>
  </div>;
}
/** Minimal QR-ish visual: real QR encoding lives in the printable receipt/ticket service; here we render a deterministic matrix from the code so door staff can visually match, and print includes the text code which scanners read as keyboard input. */
function QRSvg({ value }: { value: string }) {
  const n = 21; let h = 2166136261; const cells: boolean[] = [];
  for (let i = 0; i < n * n; i++) { h ^= value.charCodeAt(i % value.length) + i; h = Math.imul(h, 16777619) >>> 0; cells.push((h & 0x8000) !== 0); }
  const finder = (r: number, c: number) => (r < 7 && c < 7) || (r < 7 && c >= n - 7) || (r >= n - 7 && c < 7);
  return <svg width={168} height={168} viewBox={`0 0 ${n} ${n}`} shapeRendering="crispEdges">{cells.map((on, i) => { const r = Math.floor(i / n), c = i % n; const f = finder(r, c); const fill = f ? ((r % (n - 1) < 7 ? r % 7 : (r - (n - 7))) === 0 || (r % 7 === 6 && r < 7) || (r === n - 1) || (c % 7 === 0 && c < 7) || c === 6 || c === n - 7 || c === n - 1 || ((r >= 2 && r <= 4 || r >= n - 5 && r <= n - 3) && (c >= 2 && c <= 4 || c >= n - 5 && c <= n - 3))) : on; return fill ? <rect key={i} x={c} y={r} width={1} height={1} fill="#000" /> : null; })}</svg>;
}
