'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { Plus, Wallet, Undo2, ArrowRightLeft, Lock, Split, FileText } from 'lucide-react';
import { post } from '@/lib/api';
import { useApi, useAction } from '@/lib/query';
import { useAuth } from '@/lib/auth';
import { PageHeader, Section } from '@/components/shared/page';
import { Button } from '@/components/ui/button';
import { Badge, StatusBadge } from '@/components/ui/badge';
import { Spinner, Checkbox } from '@/components/ui/misc';
import { ConfirmDialog, FormDialog } from '@/components/shared/form';
import { Modal } from '@/components/ui/dialog';
import { fmtDate, fmtDateTime, fmtMoney, titleCase, cn } from '@/lib/utils';
import { PaymentLineFields, type PaymentLine } from './payment-fields';
import { PrintButton, FolioDoc } from '@/lib/print';

const CHARGE_CATEGORIES = ['ROOM', 'FOOD', 'BEVERAGE', 'MINIBAR', 'LAUNDRY', 'SPA', 'TELEPHONE', 'TRANSPORT', 'MISC', 'DAMAGE', 'LATE_CHECKOUT', 'EXTRA_BED', 'SERVICE', 'EVENT'];
/** Ledger-style folio: charges (+) and payments (−) in posting order with running balance, reversal & transfer actions. */
export function FolioView({ folioId, compact }: { folioId: string; compact?: boolean }) {
  const { can, currency } = useAuth();
  const { data: f, isLoading, refetch } = useApi<any>(`/folios/${folioId}`);
  const [charge, setCharge] = useState(false); const [pay, setPay] = useState(false); const [reverse, setReverse] = useState<any>(null); const [transfer, setTransfer] = useState<any>(null); const [close, setClose] = useState(false); const [split, setSplit] = useState(false); const [sel, setSel] = useState<string[]>([]);
  const [payment, setPayment] = useState<PaymentLine>({ amount: '' }); const [payKind, setPayKind] = useState<'PAYMENT' | 'DEPOSIT' | 'REFUND'>('PAYMENT');
  const inv = ['/folios', '/stays', '/reservations', '/payments', '/dashboard'];
  const chargeM = useAction((v: any) => post(`/folios/${folioId}/charges`, v), { success: 'Charge posted', invalidate: inv, onSuccess: () => refetch() });
  const payM = useAction(() => post(`/folios/${folioId}/payments`, { ...payment, kind: payKind }, true), { success: 'Payment posted', invalidate: inv, onSuccess: () => { setPay(false); setPayment({ amount: '' }); refetch(); } });
  const reverseM = useAction((v: any) => post(`/folios/${folioId}/items/${reverse.id}/reverse`, v), { success: 'Item reversed', invalidate: inv, onSuccess: () => refetch() });
  const transferM = useAction((v: any) => post(`/folios/${folioId}/items/${transfer.id}/transfer`, v), { success: 'Item transferred', invalidate: inv, onSuccess: () => refetch() });
  const closeM = useAction(() => post(`/folios/${folioId}/close`, {}), { success: 'Folio closed', invalidate: inv, onSuccess: () => refetch() });
  const splitM = useAction((v: any) => post(`/folios/${folioId}/split`, { item_ids: sel, type: v.type, customer_id: v.customer_id || null }), { success: 'Folio split', invalidate: inv, onSuccess: () => { setSel([]); refetch(); } });
  if (isLoading || !f) return <Spinner />;
  const items: any[] = f.items ?? []; let running = 0; const open = f.status === 'OPEN';
  const table = <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead className="bg-muted/50 text-[11px] uppercase text-muted-foreground"><tr>{open && can('folios.transfer') && <th className="w-8 px-2" />}<th className="px-3 py-2 text-left">Date</th><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-left hidden md:table-cell">Category</th><th className="px-3 py-2 text-right">Charge</th><th className="px-3 py-2 text-right">Credit</th><th className="px-3 py-2 text-right">Balance</th><th className="px-2" /></tr></thead>
    <tbody className="divide-y">{items.map((i) => { const amt = Number(i.amount); running += i.is_reversed || i.reverses_id ? Number(i.amount) : amt; const dead = i.is_reversed; return <tr key={i.id} className={cn('hover:bg-accent/40', dead && 'text-muted-foreground line-through decoration-muted-foreground/60', i.reverses_id && 'text-muted-foreground')}>{open && can('folios.transfer') && <td className="px-2"><Checkbox checked={sel.includes(i.id)} disabled={dead || !!i.reverses_id} onCheckedChange={(v) => setSel((s) => (v ? [...s, i.id] : s.filter((x) => x !== i.id)))} /></td>}<td className="px-3 py-1.5 whitespace-nowrap">{fmtDate(i.business_date)}<div className="text-[10px] text-muted-foreground">#{i.line_no}</div></td><td className="px-3 py-1.5"><div>{i.description}</div><div className="text-[11px] text-muted-foreground">{i.quantity > 1 ? `${i.quantity} × ${fmtMoney(i.unit_price, currency)} · ` : ''}{Number(i.tax_amount) > 0 ? `incl. tax ${fmtMoney(i.tax_amount, currency)} · ` : ''}{i.posted_by_name ?? ''} {fmtDateTime(i.posted_at)}{i.reason ? ` · ${i.reason}` : ''}</div></td><td className="px-3 py-1.5 hidden md:table-cell"><Badge tone="muted">{titleCase(i.category)}</Badge></td><td className="px-3 py-1.5 text-right tabular">{amt > 0 ? fmtMoney(amt, currency) : ''}</td><td className="px-3 py-1.5 text-right tabular">{amt < 0 ? fmtMoney(-amt, currency) : ''}</td><td className="px-3 py-1.5 text-right tabular font-medium">{fmtMoney(running, currency)}</td><td className="px-1 whitespace-nowrap">{open && !dead && !i.reverses_id && <>{can('folios.reverse') && <Button size="icon" variant="ghost" className="h-7 w-7" title="Reverse" onClick={() => setReverse(i)}><Undo2 className="h-3.5 w-3.5" /></Button>}{can('folios.transfer') && amt > 0 && <Button size="icon" variant="ghost" className="h-7 w-7" title="Transfer to another folio" onClick={() => setTransfer(i)}><ArrowRightLeft className="h-3.5 w-3.5" /></Button>}</>}</td></tr>; })}</tbody>
    <tfoot className="bg-muted/30 font-medium"><tr><td colSpan={open && can('folios.transfer') ? 4 : 3} className="px-3 py-2 text-right">Totals</td><td className="px-3 py-2 text-right tabular">{fmtMoney(f.totals?.charges, currency)}</td><td className="px-3 py-2 text-right tabular">{fmtMoney(f.totals?.credits, currency)}</td><td className={cn('px-3 py-2 text-right tabular', Number(f.totals?.balance) > 0 ? 'text-destructive' : 'text-emerald-600')}>{fmtMoney(f.totals?.balance, currency)}</td><td /></tr></tfoot></table></div>;
  const actions = <>
    {!compact && <PrintButton doc="folio" title={`Folio ${f.number}`} render={(ctx) => <FolioDoc folio={f} ctx={ctx} />} />}
    {compact && <PrintButton doc="folio" size="icon" variant="ghost" title={`Folio ${f.number}`} render={(ctx) => <FolioDoc folio={f} ctx={ctx} />} />}
    {open && can('folios.post') && <Button variant="outline" onClick={() => setCharge(true)}><Plus />Charge</Button>}
    {open && can('payments.create') && <Button onClick={() => setPay(true)}><Wallet />Payment</Button>}
    {open && sel.length > 0 && can('folios.transfer') && <Button variant="outline" onClick={() => setSplit(true)}><Split />Split {sel.length} item(s)</Button>}
    {open && !compact && can('folios.post') && Math.abs(Number(f.totals?.balance)) < 0.005 && !f.stay_id && <Button variant="outline" onClick={() => setClose(true)}><Lock />Close folio</Button>}
  </>;
  const header = compact ? <div className="flex items-center justify-between mb-2"><div className="font-medium flex items-center gap-2"><FileText className="h-4 w-4" /><Link href={`/front-office/folios/${f.id}`} className="hover:underline">Folio {f.number}</Link> <StatusBadge status={f.status} /><Badge tone="muted">{f.type}</Badge></div><div className="flex gap-1">{actions}</div></div>
    : <PageHeader crumbs={[{ label: 'Front office', href: '/front-office' }, { label: 'Folios', href: '/front-office/folios' }, { label: f.number }]} title={<span className="flex items-center gap-2">Folio {f.number} <StatusBadge status={f.status} /><Badge tone="muted">{f.type}</Badge></span>} subtitle={<span>{f.guest_name ?? f.customer_name}{f.room_number ? ` · Room ${f.room_number}` : ''}{f.stay_id ? <> · <Link className="text-primary hover:underline" href={`/front-office/stays/${f.stay_id}`}>stay</Link></> : ''}{f.reservation_number ? ` · ${f.reservation_number}` : ''} · {f.currency}</span>} actions={actions} />;
  return <div className="space-y-3">
    {header}
    {!compact && <div className="grid grid-cols-2 md:grid-cols-5 gap-3 text-sm">{Object.entries(f.by_category ?? {}).slice(0, 4).map(([k, v]: any) => <div key={k} className="rounded-md border p-2"><div className="text-[11px] uppercase text-muted-foreground">{titleCase(k)}</div><div className="font-semibold tabular">{fmtMoney(v, currency)}</div></div>)}<div className="rounded-md border p-2"><div className="text-[11px] uppercase text-muted-foreground">Tax / service</div><div className="font-semibold tabular">{fmtMoney(f.tax_total, currency)} / {fmtMoney(f.service_charge_total, currency)}</div></div></div>}
    {table}
    <FormDialog open={charge} onOpenChange={setCharge} title="Post charge" fields={[{ name: 'category', label: 'Category', type: 'select', options: CHARGE_CATEGORIES, required: true, default: 'MISC' }, { name: 'description', label: 'Description', required: true }, { name: 'quantity', label: 'Quantity', type: 'number', default: 1, min: 0.01 }, { name: 'unit_price', label: 'Unit price', type: 'money', required: true }, { name: 'discount', label: 'Discount', type: 'money', default: 0 }, { name: 'tax_id', label: 'Tax', type: 'lookup', source: '/taxes' }, { name: 'apply_service_charge', label: 'Apply service charge', type: 'switch' }, { name: 'reason', label: 'Reason / reference', col: 2 }]} onSubmit={(v) => chargeM.mutateAsync(v)} />
    <Modal open={pay} onOpenChange={setPay} title="Post payment" size="sm"><div className="space-y-3"><div className="flex gap-1">{(['PAYMENT', 'DEPOSIT', 'REFUND'] as const).map((k) => <Button key={k} type="button" size="sm" variant={payKind === k ? 'default' : 'outline'} onClick={() => setPayKind(k)} disabled={k === 'REFUND' && !can('payments.refund')}>{titleCase(k)}</Button>)}</div><PaymentLineFields value={payment} onChange={setPayment} /><div className="text-xs text-muted-foreground">Outstanding: {fmtMoney(f.totals?.balance, currency)}</div><div className="flex justify-end"><Button loading={payM.isPending} disabled={!payment.payment_method_id || !(Number(payment.amount) > 0)} onClick={() => payM.mutate(undefined as any)}>Post {titleCase(payKind).toLowerCase()}</Button></div></div></Modal>
    <ConfirmDialog open={!!reverse} onOpenChange={(o) => !o && setReverse(null)} title="Reverse folio item" description={`Post a mirrored adjustment for “${reverse?.description}” (${fmtMoney(reverse?.amount, currency)}). The original line stays on record.`} destructive confirmLabel="Reverse" fields={[{ name: 'reason', label: 'Reason', type: 'textarea', required: true }]} onConfirm={(v) => reverseM.mutateAsync(v)} />
    <FormDialog open={!!transfer} onOpenChange={(o) => !o && setTransfer(null)} title="Transfer charge to another folio" cols={1} size="sm" fields={[{ name: 'to_folio_id', label: 'Destination folio', type: 'lookup', source: '/folios', sourceQuery: { status: 'OPEN', pageSize: 200 }, sourceLabel: (r: any) => `${r.number} · ${r.guest_name ?? r.customer_name ?? ''}${r.room_number ? ` · Rm ${r.room_number}` : ''}`, required: true }, { name: 'reason', label: 'Reason', required: true }]} onSubmit={(v) => transferM.mutateAsync(v)} />
    <FormDialog open={split} onOpenChange={setSplit} title={`Split ${sel.length} item(s) to a new folio`} cols={1} size="sm" fields={[{ name: 'type', label: 'New folio type', type: 'select', options: ['GUEST', 'COMPANY'], default: 'GUEST', required: true }, { name: 'customer_id', label: 'Bill to company', type: 'lookup', source: '/customers' }]} onSubmit={(v) => splitM.mutateAsync(v)} />
    <ConfirmDialog open={close} onOpenChange={setClose} title="Close folio" description="A closed folio cannot receive further postings." confirmLabel="Close" onConfirm={() => closeM.mutateAsync(undefined as any)} />
  </div>;
}
