'use client';
import React from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { ResourcePage } from '@/components/shared/resource-page';
import { Badge, StatusBadge } from '@/components/ui/badge';
import { titleCase } from '@/lib/utils';
const OUTLET_TYPES = ['RESTAURANT', 'BAR', 'CLUB', 'ROOM_SERVICE', 'COFFEE_SHOP', 'BANQUET', 'SPA', 'OTHER'];
/** Outlet master data: restaurants/bars/clubs share one model; tables, sections, kitchens and terminals hang off them. */
export default function OutletsPage() {
  return <Tabs defaultValue="outlets"><TabsList><TabsTrigger value="outlets">Outlets</TabsTrigger><TabsTrigger value="tables">Tables</TabsTrigger><TabsTrigger value="sections">Sections</TabsTrigger><TabsTrigger value="kitchens">Kitchens / bars stations</TabsTrigger><TabsTrigger value="terminals">POS terminals</TabsTrigger></TabsList>
    <TabsContent value="outlets"><ResourcePage title="Outlets" subtitle="Restaurants, bars, clubs and other revenue centres. Each outlet maps to a store (stock), kitchen and GL accounts." path="/outlets" permissions={{ create: 'outlets.manage', edit: 'outlets.manage', delete: 'outlets.manage' }} filters={[{ key: 'type', label: 'Type', type: 'select', options: OUTLET_TYPES }]}
      columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'type', label: 'Type', render: (r) => <Badge tone="muted">{titleCase(r.type)}</Badge> }, { key: 'store_name', label: 'Store' }, { key: 'kitchen_name', label: 'Default kitchen' }, { key: 'service_charge_percent', label: 'Svc %', type: 'number' }, { key: 'allows_room_charge', label: 'Room charge', type: 'bool' }, { key: 'table_count', label: 'Tables', type: 'number', decimals: 0 }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'type', label: 'Type', type: 'select', options: OUTLET_TYPES, required: true, default: 'RESTAURANT' }, { name: 'department_id', label: 'Department', type: 'lookup', source: '/departments' }, { name: 'store_id', label: 'Stock store', type: 'lookup', source: '/stores' }, { name: 'default_kitchen_id', label: 'Default kitchen', type: 'lookup', source: '/kitchens' }, { name: 'revenue_account_id', label: 'Revenue account', type: 'lookup', source: '/accounts', sourceLabel: (a: any) => `${a.code} ${a.name}`, sourceQuery: { type: 'REVENUE', pageSize: 500 } }, { name: 'cogs_account_id', label: 'COGS account', type: 'lookup', source: '/accounts', sourceLabel: (a: any) => `${a.code} ${a.name}`, sourceQuery: { type: 'EXPENSE', pageSize: 500 } }, { name: 'tax_id', label: 'Default tax', type: 'lookup', source: '/taxes' }, { name: 'service_charge_percent', label: 'Service charge %', type: 'number' }, { name: 'opening_time', label: 'Opens', type: 'time' }, { name: 'closing_time', label: 'Closes', type: 'time' }, { name: 'allows_room_charge', label: 'Allow room charge', type: 'switch', default: true }, { name: 'allows_takeaway', label: 'Allow takeaway', type: 'switch', default: true }, { name: 'allows_delivery', label: 'Allow delivery', type: 'switch' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
    <TabsContent value="tables"><ResourcePage title="Tables" path="/tables" permissions={{ create: 'outlets.manage', edit: 'outlets.manage', delete: 'outlets.manage' }} filters={[{ key: 'outlet_id', label: 'Outlet', type: 'select', source: '/outlets' }]} columns={[{ key: 'outlet_name', label: 'Outlet' }, { key: 'number', label: 'Table' }, { key: 'section_name', label: 'Section' }, { key: 'capacity', label: 'Seats', type: 'number', decimals: 0 }, { key: 'shape', label: 'Shape' }, { key: 'min_spend', label: 'Min spend', type: 'money' }, { key: 'status', label: 'Status', render: (r) => <StatusBadge status={r.status} /> }, { key: 'is_active', label: 'Active', type: 'bool' }]}
      fields={[{ name: 'outlet_id', label: 'Outlet', type: 'lookup', source: '/outlets', required: true }, { name: 'section_id', label: 'Section', type: 'lookup', source: '/sections' }, { name: 'number', label: 'Table number', required: true }, { name: 'capacity', label: 'Seats', type: 'number', default: 4 }, { name: 'shape', label: 'Shape', type: 'select', options: ['SQUARE', 'ROUND', 'RECT', 'BOOTH', 'BAR'], default: 'SQUARE' }, { name: 'min_spend', label: 'Minimum spend', type: 'money' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
    <TabsContent value="sections"><ResourcePage title="Sections" path="/sections" permissions={{ create: 'outlets.manage', edit: 'outlets.manage', delete: 'outlets.manage' }} columns={[{ key: 'outlet_name', label: 'Outlet' }, { key: 'name', label: 'Section' }, { key: 'is_vip', label: 'VIP', type: 'bool' }, { key: 'sort_order', label: 'Order', type: 'number', decimals: 0 }]} fields={[{ name: 'outlet_id', label: 'Outlet', type: 'lookup', source: '/outlets', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'is_vip', label: 'VIP area', type: 'switch' }, { name: 'sort_order', label: 'Sort order', type: 'number', default: 0 }]} /></TabsContent>
    <TabsContent value="kitchens"><ResourcePage title="Kitchens & bar stations" subtitle="Production stations that receive tickets (KDS). Link a store so recipe consumption deducts from the right stock." path="/kitchens" permissions={{ create: 'outlets.manage', edit: 'outlets.manage', delete: 'outlets.manage' }} columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'store_name', label: 'Store' }, { key: 'printer_name', label: 'Printer' }, { key: 'is_active', label: 'Active', type: 'bool' }]} fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'store_id', label: 'Stock store', type: 'lookup', source: '/stores' }, { name: 'printer_name', label: 'Printer name' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
    <TabsContent value="terminals"><ResourcePage title="POS terminals" path="/pos-terminals" permissions={{ create: 'outlets.manage', edit: 'outlets.manage', delete: 'outlets.manage' }} columns={[{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'outlet_name', label: 'Outlet' }, { key: 'is_active', label: 'Active', type: 'bool' }]} fields={[{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Name', required: true }, { name: 'outlet_id', label: 'Outlet', type: 'lookup', source: '/outlets' }, { name: 'is_active', label: 'Active', type: 'switch', default: true }]} /></TabsContent>
  </Tabs>;
}
